// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod attacker_order_performance_test;
pub mod cheer_pipeline_test;
pub mod draw_phase_single_draw_no_unwanted_discards_test;
pub mod live_success_fires_at_victory_determination_test;
pub mod live_success_rules_test;
pub mod opponent_live_success_flow_test;
pub mod performance_phase_rules_test;
pub mod performance_pipeline_test;
pub mod phase_machine_rules_test;
pub mod victory_success_cards_result_test;
