// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod center_highest_cost_constant_heart_edges_test;
pub mod center_highest_cost_constant_heart_tie_test;
pub mod deployed_member_blade_heart_wait_test;
pub mod discard_group_look_four_or_recover_live_test;
