// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod blade_option_exclude_self_pl_s_bp5_004_r_test;
pub mod forced_self_wait_excludes_immune_q275_test;
pub mod optional_energy_edelnote_deploy_or_requirement_test;
