/* Auto-generated by gen_sjis_table.py - Unicode -> Shift-JIS table */
#ifndef SJIS_TABLE_H
#define SJIS_TABLE_H

#include <stdint.h>

#define SJIS_TABLE_ENTRIES 6916

/* Returns the 2-byte Shift-JIS encoding of `cp` (big-endian in the low 16
 * bits: (lead<<8)|trail), or 0 if unmappable. */
uint16_t sjis_from_unicode(uint32_t cp);

#endif
