// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod dive_ab0_does_not_arm_without_own_main_phase_discard_to_hand_test;
pub mod dive_ab0_phase_gate_and_multi_copy_live_zone_limit_edges_test;
pub mod dive_in_live_zone_only_ab1_grants_blade_test;
pub mod dive_retrieved_to_hand_ab0_places_live_zone_ab1_grants_blade_test;
