// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod dive_auto_trigger_test;
pub mod dive_edge_test;
pub mod dive_false_trigger_test;
pub mod dive_live_card_test;
