// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod chika_debut_result_character_condition_test;
pub mod ginako_live_start_discard_group_blade_count_test;
pub mod hanamaru_debut_result_character_deploy_test;
pub mod kanon_debut_invalidate_recovers_discard_card_test;
pub mod position_gated_left_side_cost_reduction_test;
pub mod wien_live_start_empty_hand_energy_placement_test;
