// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod blade_heart_two_or_fewer_discard_all_and_re_yell_test;
pub mod dia_daisuki_both_activate_order_from_mixed_deck_test;
pub mod no_live_card_revealed_discard_all_and_re_yell_test;
pub mod yell_discard_liella_live_grants_two_extra_yells_test;
pub mod yell_revealed_no_blade_heart_discard_q251_test;
pub mod zero_yell_optional_live_discard_q264_test;
