#!/usr/bin/env python3
"""
Cross-reference test files with abilities.json to identify test coverage.
Generated by: cards/ability_docs_scripts/cross_reference_tests.py
"""

import json
import re
from pathlib import Path
from collections import defaultdict


def safe_write(text, file_obj):
    """Safely write text handling unicode characters."""
    try:
        file_obj.write(text)
    except UnicodeEncodeError:
        # Replace problematic characters
        safe_text = text.encode("utf-8", errors="replace").decode("utf-8")
        file_obj.write(safe_text)


def load_abilities():
    """Load abilities.json and extract all unique action types."""
    abilities_file = Path(__file__).parent.parent / "abilities.json"
    with open(abilities_file, encoding="utf-8") as f:
        data = json.load(f)

    actions_by_type = defaultdict(list)
    actions_by_name = {}
    unique_abilities = data.get("unique_abilities", [])

    for ab in unique_abilities:
        effect = ab.get("effect") or {}
        action = effect.get("action", "")
        if action:
            actions_by_type[action].append(ab.get("cards", []))
            if action not in actions_by_name:
                actions_by_name[action] = ab
        # Check for sequential actions
        actions = effect.get("actions", [])
        for act in actions:
            act_action = act.get("action", "")
            if act_action:
                actions_by_type[act_action].append(ab.get("cards", []))
        cost = ab.get("cost") or {}
        cost_type = cost.get("type", "")
        if cost_type:
            actions_by_type[cost_type].append(ab.get("cards", []))

    return actions_by_type, actions_by_name, unique_abilities


def parse_test_file(filepath):
    """Parse a test file to extract tested card IDs and test metadata."""
    with open(filepath, encoding="utf-8") as f:
        content = f.read()

    # Extract test function names
    test_functions = re.findall(r"pub fn (\w+)\s*\(", content)

    # Find card IDs in tests
    card_ids = re.findall(r'"(PL![^"]+)"', content)

    # Extract test descriptions from comments
    test_descriptions = []
    # Look for doc comments above test functions
    lines = content.split("\n")
    for i, line in enumerate(lines):
        if line.strip().startswith("///") and "ab#" in line:
            # Extract the description after the card reference
            desc_parts = line.split("ab#")
            if len(desc_parts) > 1:
                desc = desc_parts[1].split("\n")[0].strip()
                test_descriptions.append(desc)

    return {
        "card_ids": list(set(card_ids)),
        "test_functions": test_functions,
        "descriptions": test_descriptions,
        "file_path": str(filepath),
    }


def main():
    # Load abilities
    actions_by_type, actions_by_name, unique_abilities = load_abilities()

    # Find all test files
    test_dir = Path(__file__).parent.parent.parent / "engine/tests/test_modules"
    test_files = list(test_dir.glob("*.rs"))

    # Build card_to_test mapping with detailed info
    card_to_tests = defaultdict(list)
    test_file_info = {}

    for tf in test_files:
        info = parse_test_file(tf)
        test_file_info[tf.stem] = info
        for c in info["card_ids"]:
            card_to_tests[c].append(
                {
                    "test_file": tf.stem,
                    "test_functions": info["test_functions"],
                    "descriptions": info["descriptions"],
                    "file_path": str(tf),
                }
            )

    # Create output directory
    output_dir = Path(__file__).parent
    output_dir.mkdir(exist_ok=True)

    # For each action type, find which tests cover it
    covered_actions = {}
    uncovered_actions = set()

    for action, card_lists in sorted(actions_by_type.items()):
        # Flatten card lists and find tests
        all_cards = []
        for cl in card_lists:
            all_cards.extend(cl)

        tested = False
        covering_tests = []
        for card_entry in all_cards[:5]:  # Check first 5 examples for better coverage
            card_id = (
                card_entry.split("|")[0].strip() if "|" in card_entry else card_entry
            )
            if card_id in card_to_tests:
                tested = True
                for test_info in card_to_tests[card_id]:
                    # Avoid duplicate test files
                    if test_info["test_file"] not in [
                        t["test_file"] for t in covering_tests
                    ]:
                        covering_tests.append(test_info)

        if tested:
            covered_actions[action] = covering_tests
        else:
            uncovered_actions.add(action)

    # Write covered actions report with test details
    with open(output_dir / "test_coverage_report.txt", "w", encoding="utf-8") as f:
        safe_write("# Test Coverage Report\n", f)
        safe_write(
            "# Generated by: cards/ability_docs_scripts/cross_reference_tests.py\n\n", f
        )
        safe_write("=== Action Coverage Report ===\n\n", f)

        safe_write("COVERED ACTIONS (have tests):\n", f)
        for action, tests in sorted(covered_actions.items()):
            sample = actions_by_name.get(action, {})
            cards = sample.get("cards", [])[:3]
            safe_write("\n  - {}\n".format(action), f)
            if cards:
                safe_write(
                    "    Sample Cards: {}\n".format(
                        ", ".join(c.split("|")[0].strip() for c in cards)
                    ),
                    f,
                )

            safe_write("    Test Files:\n", f)
            for test_info in tests:
                safe_write(
                    "      - {} ({})\n".format(
                        test_info["test_file"],
                        ", ".join(test_info["test_functions"][:3])
                        if test_info["test_functions"]
                        else "no test functions",
                    ),
                    f,
                )
                if test_info["descriptions"]:
                    safe_write(
                        "        Description: {}\n".format(
                            test_info["descriptions"][0]
                            if test_info["descriptions"]
                            else ""
                        ),
                        f,
                    )

        safe_write("\n\nUNCOVERED ACTIONS (no tests found):\n", f)
        for action in sorted(uncovered_actions):
            sample = actions_by_name.get(action, {})
            cards = sample.get("cards", [])[:3]
            safe_write("\n  - {}\n".format(action), f)
            if cards:
                safe_write(
                    "    Sample Cards: {}\n".format(
                        ", ".join(c.split("|")[0].strip() for c in cards)
                    ),
                    f,
                )

    # Write detailed mapping with test file paths
    with open(output_dir / "detailed_test_coverage.txt", "w", encoding="utf-8") as f:
        safe_write("# Detailed Test Coverage Mapping\n", f)
        safe_write(
            "# Generated by: cards/ability_docs_scripts/cross_reference_tests.py\n\n", f
        )
        safe_write("=== Detailed Test Coverage Mapping ===\n\n", f)

        for action in sorted(actions_by_type.keys()):
            sample = actions_by_name.get(action, {})
            cards = sample.get("cards", [])[:5]
            effect = sample.get("effect", {})
            cost = sample.get("cost", {})

            safe_write("\n## `{}`\n".format(action), f)
            if cards:
                safe_write(
                    "  Cards: {}\n".format(
                        ", ".join(c.split("|")[0].strip() for c in cards)
                    ),
                    f,
                )
            if cost:
                cost_type = cost.get("type", "")
                if cost_type:
                    safe_write("  Cost type: `{}`\n".format(cost_type), f)

            # Find tests for this action
            tests_for_action = covered_actions.get(action, [])

            if tests_for_action:
                safe_write("  Test Coverage:\n", f)
                for test_info in tests_for_action:
                    safe_write("    - {}:\n".format(test_info["test_file"]), f)
                    safe_write(
                        "      Functions: {}\n".format(
                            ", ".join(test_info["test_functions"])
                            if test_info["test_functions"]
                            else "none"
                        ),
                        f,
                    )
                    if test_info["descriptions"]:
                        safe_write(
                            "      Description: {}\n".format(
                                test_info["descriptions"][0]
                            ),
                            f,
                        )
                    safe_write("      File: {}\n".format(test_info["file_path"]), f)
            else:
                safe_write("  Test Coverage: None\n", f)
            safe_write("\n", f)


if __name__ == "__main__":
    main()
