#!/usr/bin/env python3
"""
Find abilities that have no test coverage.

Scans all test files in engine/tests/test_modules/ and cross-references
card IDs from abilities.json to determine which abilities lack any test.

Output: untested_abilities_report.txt
"""

import json
import re
from pathlib import Path
from collections import defaultdict


def safe_write(text, file_obj):
    try:
        file_obj.write(text)
    except UnicodeEncodeError:
        safe_text = text.encode("utf-8", errors="replace").decode("utf-8")
        file_obj.write(safe_text)


def load_abilities():
    abilities_file = Path(__file__).parent.parent / "abilities.json"
    with open(abilities_file, encoding="utf-8") as f:
        data = json.load(f)
    return data.get("unique_abilities", [])


def scan_test_files():
    """Scan all test files and collect every card ID referenced."""
    test_dir = Path(__file__).parent.parent.parent / "engine" / "tests" / "test_modules"
    test_files = sorted(test_dir.glob("*.rs"))

    card_to_tests = defaultdict(list)
    all_tested_cards = set()

    for tf in test_files:
        content = tf.read_text(encoding="utf-8", errors="replace")

        card_ids = re.findall(r'"(PL![^"]+)"', content)
        ll_card_ids = re.findall(r'"(LL[^"]+)"', content)
        all_ids = set(card_ids + ll_card_ids)

        test_funcs = re.findall(r"pub fn (\w+)\s*\(", content)

        for cid in all_ids:
            card_to_tests[cid].append(
                {
                    "file": tf.name,
                    "functions": test_funcs,
                }
            )
            all_tested_cards.add(cid)

    return card_to_tests, all_tested_cards, test_files


def extract_card_id(card_ref):
    """Extract the card ID portion from a card reference string."""
    return card_ref.split("|")[0].strip() if "|" in card_ref else card_ref.strip()


def main():
    abilities = load_abilities()
    card_to_tests, all_tested_cards, test_files = scan_test_files()

    tested_abilities = []
    untested_abilities = []

    for ab in abilities:
        card_refs = ab.get("cards", [])
        card_ids = [extract_card_id(c) for c in card_refs]

        has_test = any(cid in all_tested_cards for cid in card_ids)

        effect = ab.get("effect") or {}
        action = effect.get("action", "unknown")
        cost = ab.get("cost") or {}
        cost_type = cost.get("type", "unknown")
        trigger = ab.get("triggers", "")
        full_text = ab.get("full_text", "")
        use_limit = ab.get("use_limit")

        entry = {
            "action": action,
            "cost_type": cost_type,
            "trigger": trigger,
            "card_count": len(card_refs),
            "cards": card_refs,
            "card_ids": card_ids,
            "full_text": full_text,
            "use_limit": use_limit,
            "tested_by": [],
        }

        if has_test:
            for cid in card_ids:
                if cid in card_to_tests:
                    for t in card_to_tests[cid]:
                        if t["file"] not in [x["file"] for x in entry["tested_by"]]:
                            entry["tested_by"].append(t)
            tested_abilities.append(entry)
        else:
            untested_abilities.append(entry)

    # Write report
    output_dir = Path(__file__).parent
    with open(output_dir / "untested_abilities_report.txt", "w", encoding="utf-8") as f:
        safe_write("# Untested Abilities Report\n", f)
        safe_write(
            "# Generated by: cards/ability_docs_scripts/find_untested_abilities.py\n\n",
            f,
        )

        safe_write("=" * 60 + "\n", f)
        safe_write("SUMMARY\n", f)
        safe_write("=" * 60 + "\n\n", f)
        safe_write("  Total unique abilities:    {}\n".format(len(abilities)), f)
        safe_write(
            "  Abilities WITH tests:      {} ({:.1f}%)\n".format(
                len(tested_abilities),
                100 * len(tested_abilities) / max(len(abilities), 1),
            ),
            f,
        )
        safe_write(
            "  Abilities WITHOUT tests:   {} ({:.1f}%)\n".format(
                len(untested_abilities),
                100 * len(untested_abilities) / max(len(abilities), 1),
            ),
            f,
        )
        safe_write("  Test files scanned:        {}\n".format(len(test_files)), f)
        safe_write(
            "  Unique tested card IDs:    {}\n\n".format(len(all_tested_cards)), f
        )

        # Group untested by action type
        untested_by_action = defaultdict(list)
        for ab in untested_abilities:
            untested_by_action[ab["action"]].append(ab)

        tested_by_action = defaultdict(list)
        for ab in tested_abilities:
            tested_by_action[ab["action"]].append(ab)

        safe_write("=" * 60 + "\n", f)
        safe_write("COVERAGE BY EFFECT ACTION\n", f)
        safe_write("=" * 60 + "\n\n", f)

        all_actions = sorted(
            set(list(untested_by_action.keys()) + list(tested_by_action.keys()))
        )
        safe_write(
            "  {:<30s} {:>6s} {:>6s} {:>6s}  {}\n".format(
                "Action", "Tested", "Untested", "Total", "Coverage"
            ),
            f,
        )
        safe_write("  " + "-" * 70 + "\n", f)
        for action in all_actions:
            t = len(tested_by_action.get(action, []))
            u = len(untested_by_action.get(action, []))
            total = t + u
            pct = 100 * t / max(total, 1)
            safe_write(
                "  {:<30s} {:>6d} {:>6d} {:>6d}  {:.0f}%\n".format(
                    action, t, u, total, pct
                ),
                f,
            )

        safe_write("\n\n", f)

        # Detailed untested list grouped by action
        safe_write("=" * 60 + "\n", f)
        safe_write(
            "UNTESTED ABILITIES BY ACTION ({} total)\n".format(len(untested_abilities)),
            f,
        )
        safe_write("=" * 60 + "\n\n", f)

        for action in sorted(untested_by_action.keys()):
            abs_list = untested_by_action[action]
            safe_write("--- {} ({} untested) ---\n\n".format(action, len(abs_list)), f)
            for ab in sorted(abs_list, key=lambda x: x["trigger"]):
                trigger_str = " [{}]".format(ab["trigger"]) if ab["trigger"] else ""
                limit_str = (
                    " (limit={})".format(ab["use_limit"]) if ab["use_limit"] else ""
                )
                sample_cards = ", ".join(ab["card_ids"])
                safe_write(
                    "  Trigger: {}{}\n".format(ab["trigger"] or "none", limit_str), f
                )
                safe_write("  Cost:    {}\n".format(ab["cost_type"]), f)
                safe_write(
                    "  Cards ({}): {}\n".format(ab["card_count"], sample_cards), f
                )
                safe_write("  Text:    {}\n\n".format(ab["full_text"]), f)

        # Also write a compact list for quick reference
        safe_write("\n" + "=" * 60 + "\n", f)
        safe_write("COMPACT UNTESTED LIST (card IDs only)\n", f)
        safe_write("=" * 60 + "\n\n", f)
        safe_write("Use these card IDs to search for and write tests.\n\n", f)
        for action in sorted(untested_by_action.keys()):
            abs_list = untested_by_action[action]
            safe_write("## {} ({} abilities)\n".format(action, len(abs_list)), f)
            for ab in abs_list:
                for cid in ab["card_ids"]:
                    safe_write("  {}\n".format(cid), f)
            safe_write("\n", f)

    print("Report written to: untested_abilities_report.txt")
    print(
        "Tested: {} / Untested: {} / Total: {}".format(
            len(tested_abilities), len(untested_abilities), len(abilities)
        )
    )


if __name__ == "__main__":
    main()
