#!/usr/bin/env python3
"""
Single entry point: runs all ability analysis and generates consolidated reports.

Usage:
    python generate_report.py

Outputs:
    FULL_REPORT.md          - single comprehensive report (coverage, key combos, gaps, reference)
    untested_card_ids.txt   - plain list of untested card IDs for quick test-writing lookup
"""

import json
import re
from pathlib import Path
from collections import defaultdict

HERE = Path(__file__).parent
REPO = HERE.parent
ABILITIES_FILE = REPO / "abilities.json"
TEST_DIR = REPO.parent / "engine" / "tests" / "test_modules"

# ── Helpers ──────────────────────────────────────────────────


def safe_write(text, f):
    try:
        f.write(text)
    except UnicodeEncodeError:
        f.write(text.encode("utf-8", errors="replace").decode("utf-8"))


def load_abilities():
    with open(ABILITIES_FILE, encoding="utf-8") as f:
        return json.load(f).get("unique_abilities", [])


def normalize_card_id(s):
    """Normalize card ID by converting Rust Unicode escapes to literal characters."""
    s = re.sub(r"\\u\{([0-9a-fA-F]+)\}", lambda m: chr(int(m.group(1), 16)), s)
    return s


def load_tested_ids():
    tested = set()
    for tf in sorted(TEST_DIR.glob("*.rs")):
        content = tf.read_text(encoding="utf-8", errors="replace")
        for m in re.finditer(r'"((?:PL|LL)![^"]+)"', content):
            tested.add(normalize_card_id(m.group(1)))
    return tested


def extract_id(ref):
    return ref.split("|")[0].strip() if "|" in ref else ref.strip()


def key_combo(obj, skip=None):
    if skip is None:
        skip = {"action", "type", "text", "full_text", "triggerless_text", "triggers"}
    return frozenset(k for k in (obj or {})) - skip


# ── Main ─────────────────────────────────────────────────────


def main():
    abilities = load_abilities()
    tested_ids = load_tested_ids()

    # ── 1. Classify each ability ──
    for ab in abilities:
        ab["_card_ids"] = [extract_id(c) for c in ab.get("cards", [])]
        ab["_tested"] = any(c in tested_ids for c in ab["_card_ids"])
        cost = ab.get("cost") or {}
        ab["_cost_type"] = cost.get("type", "unknown")
        effect = ab.get("effect") or {}
        ab["_action"] = effect.get("action", "unknown")
        ab["_combo"] = key_combo(effect)
        ab["_cost_combo"] = key_combo(cost)
        ab["_trigger"] = (ab.get("triggers") or "").strip()

    total = len(abilities)
    tested_total = sum(1 for a in abilities if a["_tested"])

    # ── 2. Group by action ──
    by_action = defaultdict(list)
    for a in abilities:
        by_action[a["_action"]].append(a)

    # ── 3. Key combos per action ──
    action_combos = {}
    for action, abs_list in by_action.items():
        combos = defaultdict(lambda: {"total": 0, "tested": 0, "cards": []})
        for a in abs_list:
            c = a["_combo"]
            combos[c]["total"] += 1
            if a["_tested"]:
                combos[c]["tested"] += 1
            else:
                combos[c]["cards"].extend(a["_card_ids"])
        action_combos[action] = combos

    # ── 4. Cost combos ──
    cost_combos = defaultdict(lambda: defaultdict(lambda: {"total": 0, "tested": 0}))
    for a in abilities:
        ct = a["_cost_type"]
        cc = a["_cost_combo"]
        cost_combos[ct][cc]["total"] += 1
        if a["_tested"]:
            cost_combos[ct][cc]["tested"] += 1

    # ── 5. Action+cost pairings ──
    pairs = defaultdict(lambda: {"total": 0, "tested": 0})
    for a in abilities:
        key = "{} + {}".format(a["_action"], a["_cost_type"])
        pairs[key]["total"] += 1
        if a["_tested"]:
            pairs[key]["tested"] += 1

    # ── 6. Trigger coverage ──
    triggers = defaultdict(lambda: {"total": 0, "tested": 0})
    for a in abilities:
        for t in a["_trigger"].split(",") if a["_trigger"] else []:
            t = t.strip()
            if t:
                triggers[t]["total"] += 1
                if a["_tested"]:
                    triggers[t]["tested"] += 1

    # ── 7. All tested card IDs for reference ──
    tested_card_ids = set()
    for a in abilities:
        if a["_tested"]:
            tested_card_ids.update(a["_card_ids"])

    # ══════════════════════════════════════════════════════════
    #  WRITE FULL_REPORT.md
    # ══════════════════════════════════════════════════════════

    rpt = HERE / "FULL_REPORT.md"

    with open(rpt, "w", encoding="utf-8") as f:
        safe_write("# Ability Coverage Report\n\n", f)
        safe_write(
            "> Generated by `generate_report.py` | {} unique abilities\n\n".format(
                total
            ),
            f,
        )

        # ── OVERALL ──
        safe_write("## Overall\n\n", f)
        safe_write("| Metric | Value |\n|---|---|\n", f)
        safe_write("| Total abilities | {} |\n".format(total), f)
        safe_write(
            "| Tested | {} ({:.0f}%) |\n".format(
                tested_total, 100 * tested_total / max(total, 1)
            ),
            f,
        )
        safe_write(
            "| Untested | {} ({:.0f}%) |\n".format(
                total - tested_total, 100 * (total - tested_total) / max(total, 1)
            ),
            f,
        )
        safe_write("| Unique card IDs in tests | {} |\n".format(len(tested_ids)), f)
        safe_write("| Effect action types | {} |\n".format(len(by_action)), f)
        safe_write(
            "| Untested key combos | {} |\n\n".format(
                sum(
                    1
                    for ac in action_combos.values()
                    for c in ac
                    if ac[c]["tested"] == 0
                )
            ),
            f,
        )

        # ── COVERAGE TABLE ──
        safe_write("## Coverage by Action Type\n\n", f)
        safe_write(
            "| Action | Tested | Total | % | Combos | Untested Combos |\n|---|---|---|---|---|---|\n",
            f,
        )
        rows = []
        for action, abs_list in by_action.items():
            t = sum(1 for a in abs_list if a["_tested"])
            total_a = len(abs_list)
            pct = 100 * t / max(total_a, 1)
            combos = action_combos[action]
            total_c = len(combos)
            untested_c = sum(1 for c in combos if combos[c]["tested"] == 0)
            rows.append((pct, action, t, total_a, total_c, untested_c))
        for pct, action, t, total_a, total_c, untested_c in sorted(rows):
            safe_write(
                "| {} | {} | {} | {:.0f}% | {} | {} |\n".format(
                    action, t, total_a, pct, total_c, untested_c
                ),
                f,
            )
        safe_write("\n", f)

        # ── TRIGGER COVERAGE ──
        safe_write("## Coverage by Trigger Type\n\n", f)
        safe_write("| Trigger | Tested | Total | % |\n|---|---|---|---|\n", f)
        for trig in sorted(triggers.keys()):
            s = triggers[trig]
            pct = 100 * s["tested"] / max(s["total"], 1)
            safe_write(
                "| {} | {} | {} | {:.0f}% |\n".format(
                    trig, s["tested"], s["total"], pct
                ),
                f,
            )
        safe_write("\n", f)

        # ── ACTION+COST PAIRINGS ──
        safe_write("## Coverage by Action + Cost Pairing\n\n", f)
        safe_write("| Pairing | Tested | Total | % |\n|---|---|---|---|\n", f)
        for key in sorted(pairs.keys()):
            s = pairs[key]
            pct = 100 * s["tested"] / max(s["total"], 1)
            safe_write(
                "| {} | {} | {} | {:.0f}% |\n".format(
                    key, s["tested"], s["total"], pct
                ),
                f,
            )
        safe_write("\n", f)

        # ── UNTESTED KEY COMBOS ──
        safe_write("## Untested Key Combinations\n\n", f)
        safe_write("These key combos have **zero** test coverage.\n\n", f)
        for action in sorted(action_combos.keys()):
            combos = action_combos[action]
            untested = [(c, s) for c, s in combos.items() if s["tested"] == 0]
            if not untested:
                continue
            total_a = len(by_action[action])
            safe_write("### {} ({} abilities)\n\n".format(action, total_a), f)
            safe_write("| # | Keys | Sample Card IDs |\n|---|---|---|\n", f)
            for combo, s in sorted(untested, key=lambda x: -x[1]["total"]):
                keys = ", ".join(sorted(combo)) if combo else "_(action only)_"
                samples = ", ".join(s["cards"][:3])
                if len(s["cards"]) > 3:
                    samples += " +{} more".format(len(s["cards"]) - 3)
                safe_write("| {} | `{}` | {} |\n".format(s["total"], keys, samples), f)
            safe_write("\n", f)

        # ── UNTESTED COST COMBOS ──
        safe_write("## Untested Cost Key Combinations\n\n", f)
        for ct in sorted(cost_combos.keys()):
            combos = cost_combos[ct]
            untested = [(c, s) for c, s in combos.items() if s["tested"] == 0]
            if not untested:
                continue
            safe_write("### {} cost\n\n".format(ct), f)
            safe_write("| # | Keys |\n|---|---|\n", f)
            for combo, s in sorted(untested, key=lambda x: -x[1]["total"]):
                keys = ", ".join(sorted(combo)) if combo else "_(no keys)_"
                safe_write("| {} | `{}` |\n".format(s["total"], keys), f)
            safe_write("\n", f)

        # ── COVERAGE GAPS SUMMARY (top-30 untested combos) ──
        safe_write("## Top Coverage Gaps\n\n", f)
        safe_write("The 30 largest untested key combinations:\n\n", f)
        all_untested = []
        for action, combos in action_combos.items():
            for combo, s in combos.items():
                if s["tested"] == 0:
                    all_untested.append(
                        (
                            s["total"],
                            action,
                            sorted(combo) if combo else [],
                            s["cards"][:3],
                        )
                    )
        safe_write("| Rank | Count | Action | Keys |\n|---|---|---|---|\n", f)
        for rank, (cnt, action, keys, cards) in enumerate(
            sorted(all_untested, key=lambda x: -x[0])[:30], 1
        ):
            safe_write(
                "| {} | {} | {} | `{}` |\n".format(rank, cnt, action, ", ".join(keys)),
                f,
            )
        safe_write("\n", f)

        # ── ALL EXISTING KEY COMBOS (reference) ──
        safe_write("## All Existing Key Combinations (Schema Reference)\n\n", f)
        safe_write(
            "Every key combination that appears in the data, with test coverage %.\n\n",
            f,
        )
        for action in sorted(action_combos.keys()):
            combos = action_combos[action]
            total_a = len(by_action[action])
            safe_write("### {} ({} abilities)\n\n".format(action, total_a), f)
            safe_write("| # | Tested % | Keys |\n|---|---|---|\n", f)
            for combo, s in sorted(combos.items(), key=lambda x: -x[1]["total"]):
                keys = ", ".join(sorted(combo)) if combo else "_(action only)_"
                pct = 100 * s["tested"] / max(s["total"], 1)
                safe_write("| {} | {:.0f}% | `{}` |\n".format(s["total"], pct, keys), f)
            safe_write("\n", f)

        # ── ALL EXISTING COST COMBOS ──
        safe_write("## All Cost Key Combinations\n\n", f)
        for ct in sorted(cost_combos.keys()):
            combos = cost_combos[ct]
            safe_write("### {} cost\n\n".format(ct), f)
            safe_write("| # | Tested % | Keys |\n|---|---|---|\n", f)
            for combo, s in sorted(combos.items(), key=lambda x: -x[1]["total"]):
                keys = ", ".join(sorted(combo)) if combo else "_(no keys)_"
                pct = 100 * s["tested"] / max(s["total"], 1)
                safe_write("| {} | {:.0f}% | `{}` |\n".format(s["total"], pct, keys), f)
            safe_write("\n", f)

    print("Wrote FULL_REPORT.md  ({:.0f} KB)".format(rpt.stat().st_size / 1024))

    # ══════════════════════════════════════════════════════════
    #  WRITE untested_card_ids.txt
    # ══════════════════════════════════════════════════════════

    untested_ids = set()
    for a in abilities:
        if not a["_tested"]:
            untested_ids.update(a["_card_ids"])

    path_ids = HERE / "untested_card_ids.txt"
    with open(path_ids, "w", encoding="utf-8") as f:
        safe_write("# Untested card IDs ({} total)\n".format(len(untested_ids)), f)
        safe_write("# Generated by generate_report.py\n", f)
        safe_write(
            "# Usage: grep -f untested_card_ids.txt engine/tests/test_modules/*.rs\n\n",
            f,
        )
        for cid in sorted(untested_ids):
            safe_write("{}\n".format(cid), f)

    print("Wrote untested_card_ids.txt  ({} IDs)".format(len(untested_ids)))

    # ── Summary ──
    print()
    print("=" * 50)
    print("SUMMARY")
    print("=" * 50)
    print("  Total abilities:      {}".format(total))
    print(
        "  Tested:               {} ({:.0f}%)".format(
            tested_total, 100 * tested_total / max(total, 1)
        )
    )
    print(
        "  Untested:             {} ({:.0f}%)".format(
            total - tested_total, 100 * (total - tested_total) / max(total, 1)
        )
    )
    print("  Untested card IDs:    {}".format(len(untested_ids)))
    print(
        "  Untested key combos:  {}".format(
            sum(1 for ac in action_combos.values() for c in ac if ac[c]["tested"] == 0)
        )
    )
    print("  Tested card IDs:      {}".format(len(tested_ids)))


if __name__ == "__main__":
    main()
