// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod ability_watch;
pub mod debut_watch;
pub mod discard_watch;
pub mod energy_watch;
pub mod leaves_stage;
pub mod movement;
pub mod state_watch;
pub mod title_once;
pub mod yell;
