// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod ability_resolution_watcher_test;
pub mod live_start_resolved_own_center_group_reposition_q255_test;
pub mod live_success_resolved_moved_own_center_group_gain_live_score_q255_test;
pub mod resolved_center_member_ability_movement_score_q255_test;
