"""Compile cards.json into a compact binary blob + cards_gen.rs."""

import json
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from build_lib import StringTable, encode_strtab, write_blob_and_offsets, compress_with_header, write_generation_manifest, sha256_short

HEART_COLORS = {
    "heart00": 0,
    "heart01": 1,
    "heart02": 2,
    "heart03": 3,
    "heart04": 4,
    "heart05": 5,
    "heart06": 6,
    "b_all": 7,
    "draw": 8,
    "score": 9,
    "all": 10,
}
CARDTYPE = {"メンバー": 0, "ライブ": 1, "エネルギー": 2}


def build_string_table(cards: list[dict]) -> StringTable:
    st = StringTable()
    for card in cards:
        st.intern(card.get("card_no", ""))
        st.intern(card.get("name", ""))
        st.intern(card.get("series", ""))
        st.intern(card.get("unit", ""))
        st.intern(card.get("img", ""))
        st.intern(card.get("product", ""))
        st.intern(card.get("rare", ""))
        st.intern(card.get("ability", ""))
    return st


def parse_hearts(h: dict | None) -> list[tuple[int, int]]:
    if not h:
        return []
    result = []
    for color_str, count in h.items():
        if color_str == "b_all":
            col_idx = 7
        elif color_str.startswith("b_"):
            col_idx = HEART_COLORS.get(color_str[2:], 0)
        else:
            col_idx = HEART_COLORS.get(color_str, 0)
        result.append((col_idx, min(count, 255)))
    return result


def encode_card(card: dict, st: StringTable) -> bytes:
    ctype = CARDTYPE.get(card.get("type", ""), 0)
    cost = card.get("cost", 0)
    blade = card.get("blade", 0)
    score = card.get("score", 0)

    base_hearts = parse_hearts(card.get("base_heart", {}))
    blade_hearts = parse_hearts(card.get("blade_heart", {}))
    need_hearts = parse_hearts(card.get("need_heart", {}))
    special = card.get("special_heart", None)
    if special and any(v > 0 for v in special.values()):
        has_special = 1
    else:
        has_special = 0
        special = None

    has_cost = 1 if "cost" in card else 0
    has_score = 1 if "score" in card else 0
    type_flags = ctype | (has_special << 2) | (has_cost << 3) | (has_score << 4)

    nb = len(base_hearts)
    nbl = len(blade_hearts)
    nn = len(need_hearts)

    out = bytearray()
    out.extend(struct.pack("<H", st.intern(card.get("card_no", ""))))
    out.extend(struct.pack("<H", st.intern(card.get("name", ""))))
    out.extend(struct.pack("<H", st.intern(card.get("series", ""))))
    out.extend(struct.pack("<H", st.intern(card.get("group", ""))))
    out.extend(struct.pack("<H", st.intern(card.get("unit", "")) if card.get("unit") else 0xFFFF))
    out.extend(struct.pack("<H", st.intern(card.get("img", ""))))
    out.extend(struct.pack("<H", st.intern(card.get("product", ""))))
    out.extend(struct.pack("<H", st.intern(card.get("rare", ""))))
    out.extend(struct.pack("<H", st.intern(card.get("ability", "")) if card.get("ability") else 0xFFFF))
    out.extend(struct.pack("<B", type_flags))
    out.extend(struct.pack("<B", min(cost, 255)))
    out.extend(struct.pack("<B", min(blade, 255)))
    out.extend(struct.pack("<B", min(score, 255)))
    out.extend(struct.pack("<B", nb))
    out.extend(struct.pack("<B", nbl))
    out.extend(struct.pack("<B", nn))

    for h in base_hearts + blade_hearts + need_hearts:
        out.extend(struct.pack("<BB", h[0], min(h[1], 255)))

    if special:
        for color_str, count in special.items():
            col_idx = HEART_COLORS.get(color_str, 0)
            out.extend(struct.pack("<BB", col_idx, min(count, 255)))
            break

    return bytes(out)


def compile_all(cards_dict: dict) -> tuple[bytes, list[int], list[str]]:
    items = sorted(cards_dict.items(), key=lambda x: x[0])
    cards = [c for _, c in items]

    st = build_string_table(cards)
    strings = st.get_strings()

    lengths = []
    card_data = bytearray()
    for card in cards:
        before = len(card_data)
        card_data.extend(encode_card(card, st))
        lengths.append(len(card_data) - before)

    header = struct.pack("<4sHI", b"CARD", len(cards), sum(len(s.encode("utf-8")) + 2 for s in strings))
    strtab = encode_strtab(strings)
    length_table = struct.pack(f"<{len(lengths)}B", *lengths)

    blob = header + strtab + length_table + bytes(card_data)
    return blob, lengths, strings


def generate_cards_gen(blob: bytes, lengths: list[int], strings: list[str], build_dir: Path):
    build_dir.mkdir(parents=True, exist_ok=True)
    (build_dir / "cards.bin").write_bytes(blob)

    str_lits = ", ".join(json.dumps(s, ensure_ascii=False) for s in strings)

    src = f"""// Auto-generated by compile_cards.py

/// The full card database (all cards). The 16-bit `snes` target cannot
/// represent a single >64KB object and uses per-deck blobs instead, so this is
/// excluded there.
#[cfg(not(feature = "snes"))]
pub const CARD_BLOB: &[u8] = include_bytes!("../../../cards/build/cards.bin");

/// String table for card data. Indexed by u16 references in the blob.
pub const CARD_STRINGS: &[&str] = &[{str_lits}];
"""
    (build_dir / "cards_gen.rs").write_text(src, encoding="utf-8")


def main():
    cards_path = Path(__file__).parent / "cards.json"
    if not cards_path.exists():
        print(f"cards.json not found at {cards_path}", file=sys.stderr)
        sys.exit(1)

    cards_dict = json.loads(cards_path.read_text(encoding="utf-8"))
    print(f"Loaded {len(cards_dict)} cards from {cards_path}")

    blob, lengths, strings = compile_all(cards_dict)
    print(f"Blob size: {len(blob)} bytes")
    print(f"Cards: {len(lengths)}")
    print(f"Strings: {len(strings)}")
    avg = sum(lengths) / max(len(lengths), 1)
    print(f"Avg bytes per card: {avg:.1f}")

    build_dir = Path(__file__).parent / "build"
    generate_cards_gen(blob, lengths, strings, build_dir)
    print(f"Wrote cards.bin ({len(blob)} bytes)")
    print("Wrote cards_gen.rs")

    engine_dir = Path(__file__).parent.parent / "engine" / "src" / "core"
    generate_cards_gen(blob, lengths, strings, engine_dir)
    print(f"Wrote cards_gen.rs to {engine_dir}")

    (build_dir / "cards.bin.z").write_bytes(compress_with_header(blob, b"CARD"))
    print(f"Compressed: {len(open(build_dir / 'cards.bin.z', 'rb').read())} bytes")

    write_generation_manifest(
        build_dir,
        "compiled_cards.v1",
        "cards/compile_cards.py",
        "cards/cards.json",
        sha256_short(cards_path),
        len(cards_dict),
        len(blob),
        len(open(build_dir / "cards.bin.z", "rb").read()),
        "cards",
    )
    print("  manifest: generation_manifest.json")

    return blob, lengths, strings


if __name__ == "__main__":
    main()