#!/usr/bin/env python3
"""Combine the chunked bytecode in src/bytecode_data.c into one array
engine_c/src/bytecode_blob.c exposing:
    const unsigned char RBKA_BYTECODE[] = { ... };
    const uint32_t RBKA_BYTECODE_LEN = N;
This avoids sizeof() on unsized extern chunk arrays.
"""
import re, pathlib

SRC = pathlib.Path(__file__).resolve().parents[1] / "src" / "bytecode_data.c"
OUT = pathlib.Path(__file__).resolve().parents[1] / "src" / "bytecode_blob.c"

text = SRC.read_text(encoding="utf-8", errors="replace")
# match: const unsigned char BYTECODE_C0[29942] = { 0x.., ... };
chunks = []
for m in re.finditer(r"const unsigned char (\w+)\[\d+\]\s*=\s*\{(.*?)\}\s*;", text, re.S):
    nums = re.findall(r"0x[0-9A-Fa-f]+", m.group(2))
    chunks.append([int(x, 16) for x in nums])

allb = []
for c in chunks:
    allb.extend(c)

lines = []
lines.append("/* Generated by tools/gen_bytecode.py — do not edit. */")
lines.append("#include \"rabuka.h\"")
lines.append("")
lines.append(f"const uint32_t RBKA_BYTECODE_LEN = {len(allb)};")
lines.append(f"const unsigned char RBKA_BYTECODE[] = {{")
for i in range(0, len(allb), 16):
    lines.append("  " + ",".join(str(x) for x in allb[i:i+16]) + ",")
lines.append("};")
lines.append("")

OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {OUT}: {len(allb)} bytes from {len(chunks)} chunks")
