#!/usr/bin/env python3
"""Extract the data tables the C engine needs from abilities_gen.rs.

Emits src/gen_data.c with:
  - RBKA_NUM_ABILITIES
  - RBKA_OFFSET_DELTAS[]   (u16, per-ability bytecode slice lengths)
  - RBKA_STRINGS_OFFSETS[] (u32, byte offsets into abilities_strings.bin)
"""
import re, sys, pathlib

SRC = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else \
    pathlib.Path(__file__).resolve().parents[1] / "cards" / "build" / "abilities_gen.rs"
OUT = pathlib.Path(__file__).resolve().parents[1] / "src" / "gen_data.c"
HDR = pathlib.Path(__file__).resolve().parents[1] / "src" / "gen_data.h"


def grab_array(text, name):
    # tolerate the `&[T] = &[ ... ];` form (skip the type param)
    m = re.search(name + r":\s*.*?=\s*&\[(.*?)\]\s*;", text, re.S)
    if not m:
        raise SystemExit(f"could not find {name}")
    inner = m.group(1)
    nums = re.findall(r"(\d+)", inner)
    return [int(x) for x in nums]


text = SRC.read_text(encoding="utf-8", errors="replace")

m = re.search(r"NUM_ABILITIES:\s*\w+\s*=\s*(\d+)", text)
if not m:
    raise SystemExit("could not find NUM_ABILITIES")
num_ab = int(m.group(1))

offsets = grab_array(text, r"OFFSET_DELTAS")
str_off = grab_array(text, r"STRINGS_OFFSETS")
pairs = grab_array(text, r"CARD_ABILITY_PAIRS")
assert len(offsets) == num_ab, f"OFFSET_DELTAS len {len(offsets)} != {num_ab}"
assert len(str_off) >= 2, "STRINGS_OFFSETS too short"
assert len(pairs) % 2 == 0, "CARD_ABILITY_PAIRS must be even"

lines = []
lines.append("/* Generated by tools/gen_from_rs.py — do not edit. */")
lines.append("#include \"rabuka.h\"")
lines.append("")
lines.append(f"#define RBKA_NUM_STRING_OFFSETS {len(str_off)}")
lines.append(f"const uint32_t RBKA_NUM_ABILITIES = {num_ab};")
lines.append("")
lines.append(f"const uint16_t RBKA_OFFSET_DELTAS[{num_ab}] = {{")
# chunk the u16 list
for i in range(0, len(offsets), 16):
    lines.append("  " + ",".join(str(x) for x in offsets[i:i+16]) + ",")
lines.append("};")
lines.append("")
lines.append(f"const uint32_t RBKA_STRINGS_OFFSETS[{len(str_off)}] = {{")
for i in range(0, len(str_off), 12):
    lines.append("  " + ",".join(str(x) for x in str_off[i:i+12]) + ",")
lines.append("};")
lines.append("")
lines.append(f"#define RBKA_NUM_CARD_ABILITY_PAIRS {len(pairs)//2}")
lines.append(f"const uint16_t RBKA_CARD_ABILITY_PAIRS[{len(pairs)}] = {{")
for i in range(0, len(pairs), 16):
    lines.append("  " + ",".join(str(x) for x in pairs[i:i+16]) + ",")
lines.append("};")
lines.append("")

OUT.write_text("\n".join(lines), encoding="utf-8")

hdr = [
    "/* Generated by tools/gen_from_rs.py — do not edit. */",
    "#ifndef RBKA_GEN_DATA_H",
    "#define RBKA_GEN_DATA_H",
    f"#define RBKA_NUM_STRING_OFFSETS {len(str_off)}",
    f"#define RBKA_NUM_ABILITIES_C {num_ab}",
    f"#define RBKA_NUM_CARD_ABILITY_PAIRS {len(pairs)//2}",
    "#endif",
    "",
]
HDR.write_text("\n".join(hdr), encoding="utf-8")
print(f"wrote {OUT} (+{HDR})  NUM_ABILITIES={num_ab}  STRINGS_OFFSETS={len(str_off)}  CARD_ABILITY_PAIRS={len(pairs)//2}  bytecode slices sum={sum(offsets)}")
