// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod cross_player_interaction_test;
pub mod cross_player_round5_test;
pub mod e2e_basic_game_test;
pub mod gameplay_test;
pub mod hard_abilities_tier_test;
pub mod integration_blindspot_test;
pub mod parser_issues_e2e_test;
pub mod parser_issues_e2e_test_part2;
pub mod parser_issues_e2e_test_part3;
pub mod remaining_quick_test;
pub mod sp_bp2_015_proper_gameplay_test;
pub mod untested_abilities_playthrough_test;
pub mod victory_road_test;
pub mod victory_tie_placement_test;
