// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod ability_golden_test;
pub mod action_coverage_test;
pub mod bp7_character_name_condition_test;
#[cfg(feature = "bytecode_abilities")]
    pub mod bytecode_deep_compare_test;
#[cfg(feature = "bytecode_abilities")]
    pub mod bytecode_validation_test;
pub mod candidate_pool_builder_test;
pub mod character_condition_fix_test;
pub mod corpus_smoke_test;
pub mod decode_audit_behavior_pins_test;
pub mod describe_parity_test;
pub mod kinako_hs_test;
pub mod logging_test;
pub mod performance_snapshot_audit_test;
pub mod pipeline_characterization_test;
pub mod prohibition_layer_characterization_test;
pub mod size_budget_test;
pub mod strict_engine_bug_expected_fail_test;
pub mod unique_abilities_test;
pub mod zero_tested_action_types_test;
