// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod ability_from_source_test;
pub mod chika_center_cost_test;
pub mod chisato_bp5_test;
pub mod chisato_test;
pub mod genki_zenkai_test;
pub mod honoka_test;
pub mod invalid_suppress_comprehensive_edge_test;
pub mod kinako_test;
pub mod mari_bp2_test;
pub mod nozomi_bp4_aggregate_test;
pub mod s_pb1_019_live_test;
pub mod sp_bp1_003_cost_total_test;
