// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod appearance_and_repeated_swaps_stack_blades_test;
pub mod area_move_timing_and_movement_state_conditions_test;
pub mod area_swap_grants_blade_heart_or_recovers_group_live_test;
pub mod debut_or_self_area_move_gain_two_blades_q94_q171_test;
pub mod shiki_wait_gate_arms_only_after_kidou_test;
