// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod chosen_color_transform_live_start_test;
pub mod chosen_color_transform_scope_options_test;
pub mod live_start_optional_energy_chosen_heart_test;
pub mod paid_discard_color_choice_heart_test;
pub mod paid_energy_color_choice_heart01_test;
pub mod paid_heart_color_choice_test;
pub mod success_pile_chosen_heart_color_test;
pub mod success_zone_color_count_chosen_heart_test;
