// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod group_only_stage_energy_count_wait_energy_test;
pub mod l0_gap_constant_test;
pub mod live_start_optional_payment_wait_energy_test;
pub mod live_success_waited_pl_sp_bp7_027_l_test;
pub mod pr_energy_place_cost_test;
pub mod revealed_live_wait_energy_test;
pub mod score_condition_integration_test;
pub mod self_wait_places_waited_energy_margarete_bp4_010_r_test;
pub mod seven_liella_reveals_pl_sp_pr_018_pr_test;
pub mod start_true_dreams_test;
