// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod baton_touch_arrival_turn_restriction_test;
pub mod baton_touch_cheaper_group_member_optional_energy_cost_test;
pub mod baton_touch_named_replacement_fires_test;
pub mod baton_touch_protected_zone_restrictions_test;
pub mod baton_touch_replacement_name_and_cost_gate_test;
pub mod baton_touch_test;
pub mod double_baton_touch_blade_grant_per_liella_moved_test;
pub mod double_baton_touch_draw_deploy_q193_q194_test;
pub mod no_ability_baton_touch_draws_one_test;
