// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod arise_gated_activate_blade_or_wait_private_wars_test;
pub mod conditional_choice_options_execution_test;
pub mod daydream_mermaid_live_success_energy_or_recover_choice_test;
pub mod discard_self_from_hand_no_named_blade_target_q258_test;
pub mod energy_or_recycle_live_pl_n_pb1_010_r_test;
pub mod kanan_bp7_two_debut_abilities_queue_test;
pub mod mill_or_wait_pl_hs_cl1_004_cl_test;
pub mod tang_keke_energy_or_heart06_choice_test;
pub mod wait_or_draw_pl_s_bp7_025_l_test;
