// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod bp7_under_member_per_unit_blade_test;
pub mod bp7_watanabe_under_card_blade_test;
pub mod live_start_distinct_under_member_blades_test;
pub mod member_under_aqours_constant_blade_test;
pub mod per_under_member_energy_constant_blades_test;
pub mod q278_q279_joint_card_under_member_blade_test;
pub mod shizuku_under_member_heart_copy_test;
pub mod under_liella_member_constant_host_blade_test;
