// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod area_move_triggered_auto_ability_stress_test;
pub mod chisato_pb1_003_both_stages_rotation_test;
pub mod debut_selected_member_fixed_center_test;
pub mod energy_return_cost_position_change_test;
pub mod formation_change_test;
pub mod group_only_debut_formation_move_subunit_gain_blades_test;
pub mod himeno_debut_opponent_member_moved_to_own_front_area_test;
pub mod live_start_subunit_threshold_formation_test;
pub mod position_change_multi_test;
pub mod position_change_non_optional_test;
pub mod position_change_triggers_jidou_move_test;
pub mod self_control_position_change_test;
pub mod wien_bp5_test;
