// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod activate_change_state_wait_grants_live_end_blade_test;
pub mod bp7_parser_gap_cards_test;
pub mod eri_debut_up_to_two_opponent_members_to_wait_test;
pub mod hazuki_activate_discard_per_liella_member_blade_test;
pub mod kanon_debut_one_per_group_deck_bottom_edge_test;
pub mod modifier_layer_characterization_test;
pub mod per_unit_discard_count_regression_test;
pub mod q148_waited_member_blade_total_test;
pub mod q271_colorful_dreams_test;
pub mod q273_fired_debut_ability_cost_paid_test;
pub mod q46_kanako_all_heart_timing_test;
pub mod ren_baton_touch_group_check_test;
pub mod turn_scope_regression_test;
pub mod yell_same_group_members_multi_color_hearts_test;
