// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod abilityless_member_play_cost_reduction_test;
pub mod distinct_group_activation_discount_q228_test;
pub mod hand_card_count_play_cost_reduction_test;
pub mod hand_size_play_cost_reduction_zero_floor_test;
pub mod per_unit_member_cost_reduction_q249_test;
pub mod play_time_three_named_member_discard_cost_ten_test;
pub mod shuffle_waitroom_members_optional_play_discount_test;
pub mod success_zone_group_member_play_discount_test;
pub mod success_zone_high_cost_group_deploy_discount_test;
