// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod bloom_hs_test;
pub mod discard_self_same_area_group_deploy_q63_q80_test;
pub mod eternalize_love_test;
pub mod fuyumari_test;
pub mod lower_cost_baton_optional_low_cost_hand_deploy_test;
pub mod n_pb1_015_shizuku_test;
pub mod n_pb1_017_miyashita_test;
pub mod optional_energy_deploy_two_total_cost_four_test;
pub mod optional_two_energy_named_member_deploy_q199_q200_test;
pub mod paid_energy_same_name_debut_chain_q200_q201_q202_test;
pub mod pl_sp_sd1_002_test;
pub mod s_bp3_006_cost_ref_test;
pub mod under_energy_cost_waited_empty_area_deploy_q268_test;
pub mod waitroom_low_cost_pl_hs_bp6_016_r_test;
