// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod ayumu_pb1_test;
pub mod bloom_hs_test;
pub mod bp7_q268_shioriko_empty_area_deploy_test;
pub mod eternalize_love_test;
pub mod fuyumari_test;
pub mod maki_appear_test;
pub mod n_pb1_015_shizuku_test;
pub mod n_pb1_017_miyashita_test;
pub mod paid_energy_same_name_debut_chain_q200_q201_q202_test;
pub mod pl_sp_sd1_002_test;
pub mod s_bp3_006_cost_ref_test;
pub mod sayaka_test;
pub mod waitroom_low_cost_pl_hs_bp6_016_r_test;
