// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod activation_discard_blade_heart_count_condition_test;
pub mod debut_discard_blade_heart_draw_test;
pub mod debut_reveal_success_zone_replacement_q256_test;
pub mod discard_placed_group_live_or_blade_condition_test;
pub mod live_phase_success_zone_replacement_q256_test;
pub mod opponent_hand_blind_reveal_no_live_card_draw_test;
pub mod success_zone_live_card_count_alternative_test;
pub mod umi_reveal_live_card_gains_live_total_score_test;
pub mod under_card_and_success_live_conditions_test;
