// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod opponent_forced_position_change_arms_opponent_area_move_watcher_test;
pub mod round5_seat_relative_live_success_and_live_start_cross_player_test;
pub mod sumire_wien_yell_no_blade_gain_through_real_live_test;
