// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod baton_displaced_self_placed_under_arriver_test;
pub mod baton_displaced_under_arriver_grants_host_blade_test;
pub mod baton_replacement_auto_effects_test;
pub mod hanabiko_discard_test;
pub mod hs_cl1_003_edge_test;
pub mod miyashita_ai_bp5_test;
pub mod optional_any_player_position_change_q238_test;
pub mod s_bp5_010_global_heart_test;
pub mod stage_to_discard_ability_test;
pub mod strawberry_trapper_test;
