// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod live_success_or_self_move_place_discard_group_member_under_self_test;
pub mod under_member_counted_for_both_players_test;
