#!/usr/bin/env python3
"""Produce NUL-terminated ROM data blobs + ROM pointer tables from engine_c.

The Genesis has only 64 KB RAM, so the string *pointer* arrays (~32 KB for the
full database) cannot live in the arena either. Instead we keep the strings
ROM-resident (NUL-terminated) AND emit their pointer tables into ROM (see
romdata.s, which `.include`s the *.inc files). The engine's RB_ROM_STRINGS path
then points g_card_strings / g_strings straight at these ROM tables.
"""
import struct, re

E = "/mnt/c/Users/trios/OneDrive/Documents/rabuka_reloaded/engine_c"

# ---- cards.bin: NUL-terminate each entry of the string table ----
cards = open(E + "/src/cards.bin", "rb").read()
assert cards[:4] == b"CARD", "bad cards.bin magic"
nc = struct.unpack("<H", cards[4:6])[0]
stl = struct.unpack("<I", cards[6:10])[0]
strtab = cards[10:10 + stl]
rest = cards[10 + stl:]          # lentab + card records (unchanged)

out = bytearray()
card_ptrs = []                    # ROM addresses of each string (relative to file)
p = 0
while p < len(strtab):
    sl = struct.unpack("<H", strtab[p:p + 2])[0]
    p += 2
    card_ptrs.append(10 + p)      # file offset of the string content
    out += strtab[p:p + sl]
    out += b"\x00"
    p += sl

new = bytearray()
new += cards[:4]
new += struct.pack("<H", nc)
new += struct.pack("<I", len(out))
new += out
new += rest
open("cards_gen.bin", "wb").write(new)

with open("card_ptrs.inc", "w") as f:
    f.write("/* auto-generated by pack.py - ROM pointer table into cards strtab */\n")
    f.write(".globl g_card_strings_rom\n")
    f.write("g_card_strings_rom:\n")
    for off in card_ptrs:
        f.write(".long cards_bin + %d\n" % off)

# ---- abilities_strings.bin: NUL-terminate each string by offset ----
abstr = open(E + "/src/abilities_strings.bin", "rb").read()
gd = open(E + "/src/core/generated/gen_data.c").read()
m = re.search(r"RBKA_STRINGS_OFFSETS\s*\[[^\]]*\]\s*=\s*\{(.*?)\};", gd, re.S)
assert m, "could not find RBKA_STRINGS_OFFSETS"
nums = [int(x, 0) for x in re.findall(r"0x[0-9A-Fa-f]+|\d+", m.group(1))]
assert len(nums) >= 2, "offset table too small"

out2 = bytearray()
abstr_ptrs = []
for i in range(len(nums) - 1):
    a, b = nums[i], nums[i + 1]
    abstr_ptrs.append(a)          # ROM offset of string content
    out2 += abstr[a:b]
    out2 += b"\x00"
open("abstr_gen.bin", "wb").write(out2)

with open("abstr_ptrs.inc", "w") as f:
    f.write("/* auto-generated by pack.py - ROM pointer table into abilities_strings */\n")
    f.write(".globl g_strings_rom\n")
    f.write("g_strings_rom:\n")
    for off in abstr_ptrs:
        f.write(".long abstr_bin + %d\n" % off)

print("cards_gen.bin : %d bytes (%d strings)" % (len(new), len(card_ptrs)))
print("abstr_gen.bin  : %d bytes (%d strings)" % (len(out2), len(abstr_ptrs)))
