// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod activation_draw_then_discard_test;
pub mod baton_source_cost_gated_draw_discard_test;
pub mod baton_touch_skips_discard_after_self_wait_draw_test;
pub mod card_ability_tests;
pub mod draw_discard_pl_hs_bp6_030_l_test;
pub mod draw_then_bottom_hand_card;
pub mod hand_debut_no_draw_pl_hs_bp6_015_r_test;
pub mod live_success_draw_then_discard_test;
pub mod lower_stage_cost_draw_then_topdeck_test;
pub mod named_baton_source_draw_then_discard_test;
pub mod natsumi_test;
pub mod opponent_success_pl_n_sd2_007_p_test;
pub mod optional_wait_draw_discard_pl_n_bp4_023_n_test;
pub mod self_wait_draw_then_discard_test;
pub mod sp_bp4_008_leftside_draw;
pub mod stage_group_pl_hs_sd1_017_sd_test;
pub mod waitroom_debut_draw_discard_pl_s_bp6_011_n_test;
