// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod look_five_take_group_live_card_test;
pub mod look_four_take_member_with_double_heart04_test;
pub mod look_four_take_member_with_heart05_or_heart06_test;
pub mod look_two_reveal_named_member_to_hand_test;
pub mod optional_discard_look_five_take_unit_live_test;
pub mod paid_discard_look_fetches_named_subunit_test;
pub mod paid_energy_look_five_fetches_group_member_test;
pub mod paid_energy_look_seven_fetches_group_member_test;
pub mod reveal_from_deck_until_chosen_type_found_test;
