// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod bp7_q275_forcepick_wait_test;
pub mod choice_bullet_test;
pub mod daydream_mermaid_test;
pub mod hanamaru_bp3_choose_player_test;
pub mod kanan_bp7_debut_queue_test;
pub mod ll_bp7_001_triple_member_test;
pub mod mari_test;
pub mod mill_or_wait_pl_hs_cl1_004_cl_test;
pub mod opponent_choice_tests;
pub mod q258_himege_no_target_test;
pub mod tang_keke_test;
pub mod untested_abilities_test;
pub mod untested_choice_change_target_test;
