// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod debut_or_energy_return_watcher_stage_presence_test;
pub mod debut_or_own_energy_return_place_waited_energy_test;
pub mod energy_placed_by_own_effect_gain_blade_test;
pub mod energy_placement_blade_excludes_area_move_and_under_member_test;
pub mod on_energy_placed_test;
pub mod own_effect_energy_placed_blade_upper_bound_test;
pub mod own_effect_self_move_or_energy_placed_draw_heart02_test;
pub mod real_card_effect_self_move_or_energy_placed_draw_heart02_test;
pub mod trigger_card_integration_test;
