// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod live_each_time_victory_road_through_real_live_rounds_test;
pub mod live_score_tie_live_zone_placement_across_rounds_test;
pub mod real_card_phase_walkthrough_and_ability_suite_test;
pub mod rps_through_turn3_main_phase_flow_test;
