// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod chosen_player_live_bottomdeck_then_draw_test;
pub mod chosen_player_look_two_reorder_discard_test;
pub mod opponent_accepts_blades_pl_n_pr_022_pr_test;
pub mod opponent_routed_optional_discard_choice_test;
pub mod target_player_deck_routing_pl_n_bp3_010_r_pl_n_bp4_002_r_test;
pub mod target_player_recycle_pl_s_bp7_013_n_test;
