// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod bottom_aqours_required_heart_pl_s_bp7_020_l_test;
pub mod bp7_q267_rinna_mill_refresh_test;
pub mod debut_fixed_count_mill_test;
pub mod debut_mill_and_all_member_draw_test;
pub mod discard_cost_mill_then_arise_recovery_test;
pub mod s9_replacement_timestamp_test;
