// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod all_active_stage_pl_s_bp7_020_l_test;
pub mod baton_arrivals_pl_hs_bp2_023_l_and_pl_hs_bp2_025_l_test;
pub mod bp7_aquarium_yell_source_test;
pub mod bp7_mia_play_cost_reduction_test;
pub mod bp7_tang_keke_cost_test;
pub mod chika_bp5_001_no_ability_member_cost_reduction_test;
pub mod distinct_stage_waitroom_members_required_hearts_test;
pub mod hanamusubi_exclude_self_test;
pub mod hanayo_bp4_constant_test;
pub mod hand_size_zero_floor_ll_bp2_001_r_plus_test;
pub mod himeno_test;
pub mod jellyfish_test;
pub mod ladybug_test;
pub mod ll_bp2_001_cost_reduction_test;
pub mod modify_required_hearts_13key_test;
pub mod modify_required_hearts_exclude_heart_test;
pub mod modify_required_hearts_global_test;
pub mod pl_s_bp5_010_test;
pub mod success_zone_group_pl_n_sd2_003_sd2_test;
pub mod umi_q228_test;
pub mod wien_cost_mod_test;
pub mod wien_yell_count_test;
pub mod wonder_zone_max_repeats_test;
