// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod ability_chain_combo_test;
pub mod appearance_and_repeated_swaps_stack_blades_test;
pub mod area_swap_auto_effects_test;
pub mod awaken_the_power_test;
pub mod chisato_jidou_move_analysis_test;
pub mod debut_or_self_area_move_gain_two_blades_q94_q171_test;
pub mod live_success_or_self_move_place_discard_group_member_under_self_test;
pub mod movement_condition_test;
pub mod pb2_under_member_test;
pub mod position_change_only_places_energy_test;
pub mod sd2_002_basic_test;
pub mod sd2_002_edge_test;
pub mod sd2_002_jidou_cause_test;
pub mod sd2_011_tomari_jidou_test;
