// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod any_number_reorder_to_deck_top_test;
pub mod cheer_mode_look_three_return_one_from_hand_test;
pub mod debut_optional_wait_look_two_reorder_test;
pub mod debut_top3_reorder_and_discard_activation_test;
pub mod live_success_look_three_deck_size_q36_test;
pub mod live_success_look_three_reorder_any_order_test;
pub mod live_success_reorder_does_not_trigger_on_debut_test;
pub mod live_success_surplus_any_number_reorder_test;
pub mod skip_all_reorder_sends_all_to_waitroom_test;
