// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod activation_offer_bounded_and_terminates_test;
pub mod appearance_and_baton_touch_trigger_regressions_test;
pub mod cross_player_jidou_triggers_test;
pub mod debut_watcher_baton_and_hand_activation_q196_q197_q198_test;
pub mod jidou_paired_ability_combination_test;
pub mod joint_card_live_start_test;
pub mod q159_debut_from_discard_self_cost_test;
pub mod retrieval_placement_blade_ability_chain_test;
pub mod sibling_abilities_on_one_card_interact_test;
pub mod trigger_scope_test;
pub mod turn_limited_activation_offered_once_test;
pub mod zone_change_gate_test;
