// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod ability_combination_test;
pub mod ability_trigger_fix_test;
pub mod combined_ability_chain_test;
pub mod cross_player_jidou_comprehensive_edge_test;
pub mod debut_watcher_baton_and_hand_activation_q196_q197_q198_test;
pub mod jidou_combo_edge_test;
pub mod joint_card_live_start_test;
pub mod kasumi_turn_limit_test;
pub mod q159_debut_from_discard_self_cost_test;
pub mod sayaka_loop_test;
pub mod trigger_scope_test;
pub mod zone_change_gate_test;
