#!/usr/bin/env python3
"""audit_placeholders.py — scan engine_c C sources for porting placeholders.

Walks engine_c/src/**/*.c and *.h, flags lines that look like unfinished
ports, and emits a Markdown table grouped by file. Designed to be re-run as
the port progresses so PROGRESS.md's placeholder list stays in sync with the
code.

A line is reported when it matches any of:
  * a marker comment: TODO / STUB / FIXME / XXX / not yet / no-op / placeholder
    / approximated / approximation / simplified / fallback / degrade / assume /
    unknown / unsupported / ignored / bypass / phantom / stub: / not tracked
  * a "silent return" stub: `return 0;` / `return 1;` whose line (or the
    preceding non-blank line) carries one of the above markers or words like
    `silent`, `default`, `not implemented`, `unimplemented`.

Usage:
    python3 tools/audit_placeholders.py            # print markdown
    python3 tools/audit_placeholders.py --root ..   # from elsewhere
"""
import os
import re
import sys

MARKERS = [
    r"\bTODO\b", r"\bSTUB\b", r"\bFIXME\b", r"\bXXX\b",
    r"not yet", r"no-op", r"\bplaceholder\b", r"approximat", r"simplified",
    r"fallback", r"degrade", r"\bassume\b", r"\bunknown\b", r"unsupported",
    r"\bignored\b", r"\bbypass\b", r"\bphantom\b", r"not tracked",
    r"\bstub\b", r"not implemented", r"unimplemented",
]
MARKER_RE = re.compile("|".join(MARKERS), re.IGNORECASE)
SILENT_RET = re.compile(r"^\s*return\s+[01]\s*;")
SILENT_WORDS = re.compile(r"silent|not implemented|unimplemented|default|skip\b", re.IGNORECASE)


def scan_file(path):
    hits = []
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        lines = f.readlines()
    prev = ""
    for i, line in enumerate(lines, 1):
        if MARKER_RE.search(line):
            hits.append((i, line.rstrip()))
            continue
        if SILENT_RET.match(line):
            ctx = prev if prev.strip() else line
            if SILENT_WORDS.search(prev) or MARKER_RE.search(prev):
                hits.append((i, line.rstrip()))
        prev = line
    return hits


def main():
    root = "."
    for a in sys.argv[1:]:
        if a.startswith("--root"):
            root = a.split("=", 1)[1] if "=" in a else None
    if root is None:
        idx = sys.argv.index("--root")
        root = sys.argv[idx + 1]
    src = os.path.join(root, "src")
    results = {}
    for dirpath, _, files in os.walk(src):
        for fn in files:
            if fn.endswith((".c", ".h")):
                p = os.path.join(dirpath, fn)
                h = scan_file(p)
                if h:
                    rel = os.path.relpath(p, root)
                    results[rel] = h
    if not results:
        print("_No placeholder markers found._")
        return
    print("\n## Auto-detected placeholders (generated by tools/audit_placeholders.py)\n")
    for rel in sorted(results):
        print(f"### {rel}\n")
        print("| line | snippet |")
        print("| ---: | --- |")
        for ln, snip in results[rel]:
            snip = snip.replace("|", "\\|").strip()
            if len(snip) > 200:
                snip = snip[:197] + "..."
            print(f"| {ln} | `{snip}` |")
        print()


if __name__ == "__main__":
    main()
