// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod kagayaiteru_test;
pub mod live_success_sequential_test;
pub mod mebius_loop_comprehensive_edge_test;
