// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod alone_on_stage_cannot_live_constant_test;
pub mod delayed_cannot_active_owner_tick_test;
pub mod kagayaiteru_test;
pub mod live_success_sequential_test;
pub mod mebius_loop_comprehensive_edge_test;
pub mod opponent_active_phase_lock_targeting_test;
