// AUTO-GENERATED by generate_condition_decoder.py — DO NOT EDIT
// Re-run: python cards/generate_condition_decoder.py
//
// Direct decoder for the serde internally-tagged `Condition` enum.
// `text`/`trigger_event` exist only under the `debug_conditions` feature
// and are skipped otherwise.

/// Accumulator for Condition fields during direct decode.
#[derive(Default)]
struct ConditionLocals {
    pub ability_filter: Option<ArcStr>,
    pub ability_filter_triggers: Option<Box<Vec<String>>>,
    pub activation_position: Option<ArcStr>,
    pub aggregate: Option<ArcStr>,
    pub all: Option<bool>,
    pub all_areas: Option<bool>,
    pub all_members: Option<bool>,
    pub any_of: Option<Vec<String>>,
    pub appearance: Option<bool>,
    pub appearance_source: Option<ArcStr>,
    pub area_direction: Option<ArcStr>,
    pub baton_touch_source: Option<ArcStr>,
    pub baton_touch_trigger: Option<bool>,
    pub cache: Option<bool>,
    pub card_property: Option<ArcStr>,
    pub card_type: Option<ArcStr>,
    pub cause: Option<Box<Condition>>,
    pub characters: Option<Box<Vec<String>>>,
    pub comparison_source: Option<ArcStr>,
    pub comparison_target: Option<ArcStr>,
    pub comparison_type: Option<ArcStr>,
    pub condition: Option<Box<Condition>>,
    pub conditions: Option<Vec<Box<Condition>>>,
    pub cost_limit: Option<u8>,
    pub cost_limit_operator: Option<Operator>,
    pub cost_reference_character: Option<ArcStr>,
    pub cost_reference_operator: Option<Operator>,
    pub cost_total: Option<u8>,
    pub cost_total_operator: Option<Operator>,
    pub count: Option<u8>,
    pub delta: Option<bool>,
    pub destination: Option<ArcStr>,
    pub distinct: Option<Box<DistinctInfo>>,
    pub effect: Option<Box<AbilityEffect>>,
    pub energy_placed: Option<bool>,
    pub energy_state: Option<ArcStr>,
    pub exclude_characters: Option<Box<Vec<String>>>,
    pub exclude_group_names: Option<Box<Vec<String>>>,
    pub exclude_self: Option<bool>,
    pub from_state: Option<ArcStr>,
    pub group_names: Option<Box<Vec<String>>>,
    pub group_reference: Option<ArcStr>,
    pub heart_colors: Option<Box<Vec<String>>>,
    pub heart_source: Option<ArcStr>,
    pub heart_type: Option<ArcStr>,
    pub location: Option<ArcStr>,
    pub locations: Option<Box<Vec<String>>>,
    pub min_baton_touch_count: Option<u8>,
    pub movement: Option<ArcStr>,
    pub negation: Option<bool>,
    pub no_excess_heart: Option<bool>,
    pub operator: Option<ArcStr>,
    pub options: Option<Box<Vec<Box<AbilityEffect>>>>,
    pub phase: Option<ArcStr>,
    pub phase_target: Option<ArcStr>,
    pub position: Option<Box<PositionInfo>>,
    pub position_compare: Option<ArcStr>,
    pub positions_characters: Option<Box<Vec<PositionCharacter>>>,
    pub require_position_cards: Option<bool>,
    pub resource_type: Option<ArcStr>,
    pub same_name: Option<bool>,
    pub scope: Option<ArcStr>,
    pub self_effect_only: Option<bool>,
    pub self_target: Option<bool>,
    pub source: Option<ArcStr>,
    pub state: Option<ArcStr>,
    pub sub_checks: Option<Box<LocationSubChecks>>,
    pub target: Option<ArcStr>,
    pub temporal: Option<ArcStr>,
    pub temporal_scope: Option<ArcStr>,
    #[cfg(feature = "debug_conditions")]
    pub text: Option<String>,
    pub to_state: Option<ArcStr>,
    #[cfg(feature = "debug_conditions")]
    pub trigger_event: Option<Box<TriggerEvent>>,
    pub turn_number: Option<u8>,
    pub unit: Option<ArcStr>,
    pub values: Option<Box<Vec<u8>>>,
    pub yell_trigger: Option<bool>,
}

/// Read one field from a condition object.
/// Returns true if the field was recognized and consumed, false to skip.
fn decode_condition_field(
    bc: &mut BcReader,
    key: &str,
    l: &mut ConditionLocals,
) -> Option<bool> {
    match key {
            "ability_filter" => { l.ability_filter = bc.read_arc_str_value(); return Some(true); }
            "ability_filter_triggers" => { l.ability_filter_triggers = bc.read_opt_str_vec_value(); return Some(true); }
            "activation_position" => { l.activation_position = bc.read_arc_str_value(); return Some(true); }
            "aggregate" => { l.aggregate = bc.read_arc_str_value(); return Some(true); }
            "all" => { l.all = bc.read_bool_value(); return Some(true); }
            "all_areas" => { l.all_areas = bc.read_bool_value(); return Some(true); }
            "all_members" => { l.all_members = bc.read_bool_value(); return Some(true); }
            "any_of" => { l.any_of = bc.read_opt_str_vec_value().map(|b| *b); return Some(true); }
            "appearance" => { l.appearance = bc.read_bool_value(); return Some(true); }
            "appearance_source" => { l.appearance_source = bc.read_arc_str_value(); return Some(true); }
            "area_direction" => { l.area_direction = bc.read_arc_str_value(); return Some(true); }
            "baton_touch_source" => { l.baton_touch_source = bc.read_arc_str_value(); return Some(true); }
            "baton_touch_trigger" => { l.baton_touch_trigger = bc.read_bool_value(); return Some(true); }
            "cache" => { l.cache = bc.read_bool_value(); return Some(true); }
            "card_property" => { l.card_property = bc.read_arc_str_value(); return Some(true); }
            "card_type" => { l.card_type = bc.read_arc_str_value(); return Some(true); }
            "cause" => { l.cause = bc.read_condition_value(); return Some(true); }
            "characters" => { l.characters = bc.read_opt_str_vec_value(); return Some(true); }
            "comparison_source" => { l.comparison_source = bc.read_arc_str_value(); return Some(true); }
            "comparison_target" => { l.comparison_target = bc.read_arc_str_value(); return Some(true); }
            "comparison_type" => { l.comparison_type = bc.read_arc_str_value(); return Some(true); }
            "condition" => { l.condition = bc.read_condition_value(); return Some(true); }
            "conditions" => { l.conditions = bc.read_condition_vec_value(); return Some(true); }
            "cost_limit" => { l.cost_limit = bc.read_u8_value(); return Some(true); }
            "cost_limit_operator" => { l.cost_limit_operator = bc.read_operator_value(); return Some(true); }
            "cost_reference_character" => { l.cost_reference_character = bc.read_arc_str_value(); return Some(true); }
            "cost_reference_operator" => { l.cost_reference_operator = bc.read_operator_value(); return Some(true); }
            "cost_total" => { l.cost_total = bc.read_u8_value(); return Some(true); }
            "cost_total_operator" => { l.cost_total_operator = bc.read_operator_value(); return Some(true); }
            "count" => { l.count = bc.read_u8_value(); return Some(true); }
            "delta" => { l.delta = bc.read_bool_value(); return Some(true); }
            "destination" => { l.destination = bc.read_arc_str_value(); return Some(true); }
            "distinct" => { l.distinct = bc.read_distinct_info_value(); return Some(true); }
            "effect" => { l.effect = bc.read_effect_value(); return Some(true); }
            "energy_placed" => { l.energy_placed = bc.read_bool_value(); return Some(true); }
            "energy_state" => { l.energy_state = bc.read_arc_str_value(); return Some(true); }
            "exclude_characters" => { l.exclude_characters = bc.read_opt_str_vec_value(); return Some(true); }
            "exclude_group_names" => { l.exclude_group_names = bc.read_opt_str_vec_value(); return Some(true); }
            "exclude_self" => { l.exclude_self = bc.read_bool_value(); return Some(true); }
            "from_state" => { l.from_state = bc.read_arc_str_value(); return Some(true); }
            "group_names" => { l.group_names = bc.read_opt_str_vec_value(); return Some(true); }
            "group_reference" => { l.group_reference = bc.read_arc_str_value(); return Some(true); }
            "heart_colors" => { l.heart_colors = bc.read_opt_str_vec_value(); return Some(true); }
            "heart_source" => { l.heart_source = bc.read_arc_str_value(); return Some(true); }
            "heart_type" => { l.heart_type = bc.read_arc_str_value(); return Some(true); }
            "location" => { l.location = bc.read_arc_str_value(); return Some(true); }
            "locations" => { l.locations = bc.read_opt_str_vec_value(); return Some(true); }
            "min_baton_touch_count" => { l.min_baton_touch_count = bc.read_u8_value(); return Some(true); }
            "movement" => { l.movement = bc.read_arc_str_value(); return Some(true); }
            "negation" => { l.negation = bc.read_bool_value(); return Some(true); }
            "no_excess_heart" => { l.no_excess_heart = bc.read_bool_value(); return Some(true); }
            "operator" => { l.operator = bc.read_arc_str_value(); return Some(true); }
            "options" => { l.options = bc.read_effect_vec_boxed_value(); return Some(true); }
            "phase" => { l.phase = bc.read_arc_str_value(); return Some(true); }
            "phase_target" => { l.phase_target = bc.read_arc_str_value(); return Some(true); }
            "position" => { l.position = bc.read_position_value(); return Some(true); }
            "position_compare" => { l.position_compare = bc.read_arc_str_value(); return Some(true); }
            "positions_characters" => { l.positions_characters = bc.read_positions_characters_value(); return Some(true); }
            "require_position_cards" => { l.require_position_cards = bc.read_bool_value(); return Some(true); }
            "resource_type" => { l.resource_type = bc.read_arc_str_value(); return Some(true); }
            "same_name" => { l.same_name = bc.read_bool_value(); return Some(true); }
            "scope" => { l.scope = bc.read_arc_str_value(); return Some(true); }
            "self_effect_only" => { l.self_effect_only = bc.read_bool_value(); return Some(true); }
            "self_target" => { l.self_target = bc.read_bool_value(); return Some(true); }
            "source" => { l.source = bc.read_arc_str_value(); return Some(true); }
            "state" => { l.state = bc.read_arc_str_value(); return Some(true); }
            "sub_checks" => { l.sub_checks = bc.read_location_sub_checks_value(); return Some(true); }
            "target" => { l.target = bc.read_arc_str_value(); return Some(true); }
            "temporal" => { l.temporal = bc.read_arc_str_value(); return Some(true); }
            "temporal_scope" => { l.temporal_scope = bc.read_arc_str_value(); return Some(true); }
            #[cfg(feature = "debug_conditions")] "text" => { l.text = bc.read_string_value(); return Some(true); }
            #[cfg(not(feature = "debug_conditions"))] "text" => { bc.skip_value()?; return Some(true); }
            "to_state" => { l.to_state = bc.read_arc_str_value(); return Some(true); }
            #[cfg(feature = "debug_conditions")] "trigger_event" => { l.trigger_event = bc.read_trigger_event_value(); return Some(true); }
            #[cfg(not(feature = "debug_conditions"))] "trigger_event" => { bc.skip_value()?; return Some(true); }
            "turn_number" => { l.turn_number = bc.read_u8_value(); return Some(true); }
            "unit" => { l.unit = bc.read_arc_str_value(); return Some(true); }
            "values" => { l.values = bc.read_opt_u8_vec_value(); return Some(true); }
            "yell_trigger" => { l.yell_trigger = bc.read_bool_value(); return Some(true); }
            "type" => { bc.skip_value()?; return Some(true); }
            _ => { bc.skip_value()?; return Some(true); }
        }
    }

fn build_compound(l: &ConditionLocals) -> Condition {
    Condition::Compound {
        #[cfg(feature = "debug_conditions")] text: l.text.clone(),
        negation: l.negation.clone(),
        phase: l.phase.clone(),
        phase_target: l.phase_target.clone(),
        cache: l.cache.clone(),
        #[cfg(feature = "debug_conditions")] trigger_event: l.trigger_event.clone(),
        operator: l.operator.clone(),
        target: l.target.clone(),
        conditions: l.conditions.clone(),
    }
}

fn build_location(l: &ConditionLocals) -> Condition {
    Condition::Location {
        #[cfg(feature = "debug_conditions")] text: l.text.clone(),
        negation: l.negation.clone(),
        phase: l.phase.clone(),
        phase_target: l.phase_target.clone(),
        cache: l.cache.clone(),
        #[cfg(feature = "debug_conditions")] trigger_event: l.trigger_event.clone(),
        location: l.location.clone(),
        locations: l.locations.clone(),
        target: l.target.clone(),
        count: l.count.clone(),
        operator: l.operator.clone(),
        card_type: l.card_type.as_deref().map(ConditionCardType::from_str),
        unit: l.unit.clone(),
        comparison_target: l.comparison_target.as_deref().map(ComparisonTarget::from_str),
        comparison_type: l.comparison_type.as_deref().map(ComparisonType::from_str),
        aggregate: l.aggregate.clone(),
        group_names: l.group_names.clone(),
        group_reference: l.group_reference.clone(),
        exclude_group_names: l.exclude_group_names.clone(),
        characters: l.characters.clone(),
        exclude_characters: l.exclude_characters.clone(),
        cost_limit: l.cost_limit.clone(),
        cost_limit_operator: l.cost_limit_operator.clone(),
        heart_colors: l.heart_colors.clone(),
        heart_type: l.heart_type.clone(),
        heart_source: l.heart_source.clone(),
        distinct: l.distinct.clone(),
        exclude_self: l.exclude_self.clone(),
        self_target: l.self_target.clone(),
        source: l.source.clone(),
        activation_position: l.activation_position.clone(),
        destination: l.destination.clone(),
        state: l.state.as_deref().map(CardState::from_str),
        position: l.position.clone(),
        position_compare: l.position_compare.clone(),
        require_position_cards: l.require_position_cards.clone(),
        all: l.all.clone(),
        all_areas: l.all_areas.clone(),
        temporal: l.temporal.clone(),
        yell_trigger: l.yell_trigger.clone(),
        same_name: l.same_name.clone(),
        card_property: l.card_property.as_deref().map(CardProperty::from_str),
        scope: l.scope.clone(),
        sub_checks: l.sub_checks.clone(),
        baton_touch_trigger: l.baton_touch_trigger.clone(),
        min_baton_touch_count: l.min_baton_touch_count.clone(),
    }
}

fn build_comparison(l: &ConditionLocals) -> Condition {
    Condition::Comparison {
        #[cfg(feature = "debug_conditions")] text: l.text.clone(),
        negation: l.negation.clone(),
        phase: l.phase.clone(),
        phase_target: l.phase_target.clone(),
        cache: l.cache.clone(),
        #[cfg(feature = "debug_conditions")] trigger_event: l.trigger_event.clone(),
        comparison_type: l.comparison_type.as_deref().map(ComparisonType::from_str),
        comparison_target: l.comparison_target.as_deref().map(ComparisonTarget::from_str),
        target: l.target.clone(),
        location: l.location.clone(),
        operator: l.operator.clone(),
        count: l.count.clone(),
        values: l.values.clone(),
        card_type: l.card_type.as_deref().map(ConditionCardType::from_str),
        group_names: l.group_names.clone(),
        position: l.position.clone(),
        position_compare: l.position_compare.clone(),
        aggregate: l.aggregate.clone(),
        heart_colors: l.heart_colors.clone(),
        scope: l.scope.clone(),
        cost_total: l.cost_total.clone(),
        cost_total_operator: l.cost_total_operator.clone(),
        resource_type: l.resource_type.clone(),
        delta: l.delta.clone(),
        cost_limit: l.cost_limit.clone(),
        source: l.source.clone(),
        comparison_source: l.comparison_source.clone(),
        locations: l.locations.clone(),
        exclude_group_names: l.exclude_group_names.clone(),
        characters: l.characters.clone(),
        exclude_characters: l.exclude_characters.clone(),
        same_name: l.same_name.clone(),
        distinct: l.distinct.clone(),
        all: l.all.clone(),
        all_areas: l.all_areas.clone(),
        exclude_self: l.exclude_self.clone(),
        self_target: l.self_target.clone(),
        destination: l.destination.clone(),
        state: l.state.as_deref().map(CardState::from_str),
        require_position_cards: l.require_position_cards.clone(),
        temporal: l.temporal.clone(),
        yell_trigger: l.yell_trigger.clone(),
        no_excess_heart: l.no_excess_heart.clone(),
        card_property: l.card_property.as_deref().map(CardProperty::from_str),
        ability_filter: l.ability_filter.clone(),
        ability_filter_triggers: l.ability_filter_triggers.clone(),
        baton_touch_trigger: l.baton_touch_trigger.clone(),
        min_baton_touch_count: l.min_baton_touch_count.clone(),
        from_state: l.from_state.clone(),
        to_state: l.to_state.clone(),
    }
}

fn build_movement(l: &ConditionLocals) -> Condition {
    Condition::Movement {
        #[cfg(feature = "debug_conditions")] text: l.text.clone(),
        negation: l.negation.clone(),
        phase: l.phase.clone(),
        phase_target: l.phase_target.clone(),
        cache: l.cache.clone(),
        #[cfg(feature = "debug_conditions")] trigger_event: l.trigger_event.clone(),
        movement: l.movement.clone(),
        location: l.location.clone(),
        target: l.target.clone(),
        cost_limit: l.cost_limit.clone(),
        cost_limit_operator: l.cost_limit_operator.clone(),
        baton_touch_trigger: l.baton_touch_trigger.clone(),
        min_baton_touch_count: l.min_baton_touch_count.clone(),
        exclude_self: l.exclude_self.clone(),
        group_names: l.group_names.clone(),
        card_type: l.card_type.as_deref().map(ConditionCardType::from_str),
        characters: l.characters.clone(),
        baton_touch_source: l.baton_touch_source.clone(),
        card_property: l.card_property.as_deref().map(CardProperty::from_str),
        comparison_type: l.comparison_type.as_deref().map(ComparisonType::from_str),
        operator: l.operator.clone(),
        self_effect_only: l.self_effect_only.clone(),
        energy_placed: l.energy_placed.clone(),
        area_direction: l.area_direction.clone(),
        position: l.position.clone(),
        self_target: l.self_target.clone(),
        ability_filter: l.ability_filter.as_deref().map(AbilityFilter::from_str),
        source: l.source.clone(),
        destination: l.destination.clone(),
        from_state: l.from_state.clone(),
        to_state: l.to_state.clone(),
    }
}

fn build_group(l: &ConditionLocals) -> Condition {
    Condition::Group {
        #[cfg(feature = "debug_conditions")] text: l.text.clone(),
        negation: l.negation.clone(),
        phase: l.phase.clone(),
        phase_target: l.phase_target.clone(),
        cache: l.cache.clone(),
        #[cfg(feature = "debug_conditions")] trigger_event: l.trigger_event.clone(),
        group_names: l.group_names.clone(),
        all_members: l.all_members.clone(),
        location: l.location.clone(),
        target: l.target.clone(),
        heart_colors: l.heart_colors.clone(),
        card_type: l.card_type.as_deref().map(ConditionCardType::from_str),
        operator: l.operator.clone(),
        count: l.count.clone(),
        aggregate: l.aggregate.clone(),
        exclude_characters: l.exclude_characters.clone(),
        temporal: l.temporal.clone(),
        self_target: l.self_target.clone(),
        exclude_self: l.exclude_self.clone(),
        heart_source: l.heart_source.clone(),
        source: l.source.clone(),
        locations: l.locations.clone(),
        position: l.position.clone(),
    }
}

fn build_appearance(l: &ConditionLocals) -> Condition {
    Condition::Appearance {
        #[cfg(feature = "debug_conditions")] text: l.text.clone(),
        negation: l.negation.clone(),
        phase: l.phase.clone(),
        phase_target: l.phase_target.clone(),
        cache: l.cache.clone(),
        #[cfg(feature = "debug_conditions")] trigger_event: l.trigger_event.clone(),
        appearance: l.appearance.clone(),
        baton_touch_trigger: l.baton_touch_trigger.clone(),
        location: l.location.clone(),
        target: l.target.clone(),
        group_names: l.group_names.clone(),
        cost_limit: l.cost_limit.clone(),
        card_type: l.card_type.as_deref().map(ConditionCardType::from_str),
        characters: l.characters.clone(),
        positions_characters: l.positions_characters.clone(),
        min_baton_touch_count: l.min_baton_touch_count.clone(),
        activation_position: l.activation_position.clone(),
        exclude_self: l.exclude_self.clone(),
        position_compare: l.position_compare.clone(),
        position: l.position.clone(),
        card_property: l.card_property.as_deref().map(CardProperty::from_str),
        all_areas: l.all_areas.clone(),
        cost_reference_character: l.cost_reference_character.clone(),
        cost_reference_operator: l.cost_reference_operator.clone(),
        appearance_source: l.appearance_source.clone(),
        operator: l.operator.clone(),
    }
}

fn build_temporal(l: &ConditionLocals) -> Condition {
    Condition::Temporal {
        #[cfg(feature = "debug_conditions")] text: l.text.clone(),
        negation: l.negation.clone(),
        phase: l.phase.clone(),
        phase_target: l.phase_target.clone(),
        cache: l.cache.clone(),
        #[cfg(feature = "debug_conditions")] trigger_event: l.trigger_event.clone(),
        temporal: l.temporal.clone(),
        turn_number: l.turn_number.clone(),
        count: l.count.clone(),
        location: l.location.clone(),
        card_type: l.card_type.as_deref().map(ConditionCardType::from_str),
        target: l.target.clone(),
        group_names: l.group_names.clone(),
        temporal_scope: l.temporal_scope.clone(),
        position: l.position.clone(),
        locations: l.locations.clone(),
        heart_colors: l.heart_colors.clone(),
        aggregate: l.aggregate.clone(),
        self_target: l.self_target.clone(),
        condition: l.condition.clone(),
    }
}

fn build_state(l: &ConditionLocals) -> Condition {
    Condition::State {
        #[cfg(feature = "debug_conditions")] text: l.text.clone(),
        negation: l.negation.clone(),
        phase: l.phase.clone(),
        phase_target: l.phase_target.clone(),
        cache: l.cache.clone(),
        #[cfg(feature = "debug_conditions")] trigger_event: l.trigger_event.clone(),
        state: l.state.as_deref().map(EffectState::from_str),
        energy_state: l.energy_state.clone(),
        target: l.target.clone(),
        resource_type: l.resource_type.clone(),
        all: l.all.clone(),
        group_names: l.group_names.clone(),
        card_type: l.card_type.as_deref().map(ConditionCardType::from_str),
        characters: l.characters.clone(),
        cost_limit: l.cost_limit.clone(),
        cost_limit_operator: l.cost_limit_operator.clone(),
        from_state: l.from_state.clone(),
        to_state: l.to_state.clone(),
        count: l.count.clone(),
        operator: l.operator.clone(),
    }
}

fn build_resource(l: &ConditionLocals) -> Condition {
    Condition::Resource {
        #[cfg(feature = "debug_conditions")] text: l.text.clone(),
        negation: l.negation.clone(),
        phase: l.phase.clone(),
        phase_target: l.phase_target.clone(),
        cache: l.cache.clone(),
        #[cfg(feature = "debug_conditions")] trigger_event: l.trigger_event.clone(),
        resource_type: l.resource_type.clone(),
        target: l.target.clone(),
        location: l.location.clone(),
        operator: l.operator.clone(),
        count: l.count.clone(),
        delta: l.delta.clone(),
        heart_colors: l.heart_colors.clone(),
        position: l.position.clone(),
        source: l.source.clone(),
    }
}

fn build_abilityfilter(l: &ConditionLocals) -> Condition {
    Condition::AbilityFilter {
        #[cfg(feature = "debug_conditions")] text: l.text.clone(),
        negation: l.negation.clone(),
        phase: l.phase.clone(),
        phase_target: l.phase_target.clone(),
        cache: l.cache.clone(),
        #[cfg(feature = "debug_conditions")] trigger_event: l.trigger_event.clone(),
        ability_filter: l.ability_filter.as_deref().map(AbilityFilter::from_str),
        ability_filter_triggers: l.ability_filter_triggers.clone(),
        target: l.target.clone(),
        location: l.location.clone(),
        operator: l.operator.clone(),
        count: l.count.clone(),
    }
}

fn build_scorethreshold(l: &ConditionLocals) -> Condition {
    Condition::ScoreThreshold {
        #[cfg(feature = "debug_conditions")] text: l.text.clone(),
        negation: l.negation.clone(),
        phase: l.phase.clone(),
        phase_target: l.phase_target.clone(),
        cache: l.cache.clone(),
        #[cfg(feature = "debug_conditions")] trigger_event: l.trigger_event.clone(),
        count: l.count.clone(),
        operator: l.operator.clone(),
        target: l.target.clone(),
    }
}

fn build_choice(l: &ConditionLocals) -> Condition {
    Condition::Choice {
        #[cfg(feature = "debug_conditions")] text: l.text.clone(),
        negation: l.negation.clone(),
        phase: l.phase.clone(),
        phase_target: l.phase_target.clone(),
        cache: l.cache.clone(),
        #[cfg(feature = "debug_conditions")] trigger_event: l.trigger_event.clone(),
        options: l.options.clone(),
    }
}

fn build_complex(l: &ConditionLocals) -> Condition {
    Condition::Complex {
        #[cfg(feature = "debug_conditions")] text: l.text.clone(),
        negation: l.negation.clone(),
        phase: l.phase.clone(),
        phase_target: l.phase_target.clone(),
        cache: l.cache.clone(),
        #[cfg(feature = "debug_conditions")] trigger_event: l.trigger_event.clone(),
        cause: l.cause.clone(),
        effect: l.effect.clone(),
    }
}

fn build_positioncond(l: &ConditionLocals) -> Condition {
    Condition::PositionCond {
        #[cfg(feature = "debug_conditions")] text: l.text.clone(),
        negation: l.negation.clone(),
        phase: l.phase.clone(),
        phase_target: l.phase_target.clone(),
        cache: l.cache.clone(),
        #[cfg(feature = "debug_conditions")] trigger_event: l.trigger_event.clone(),
        target: l.target.clone(),
        position: l.position.clone(),
    }
}

fn build_opponentchoice(l: &ConditionLocals) -> Condition {
    Condition::OpponentChoice {
        #[cfg(feature = "debug_conditions")] text: l.text.clone(),
        negation: l.negation.clone(),
        phase: l.phase.clone(),
        phase_target: l.phase_target.clone(),
        cache: l.cache.clone(),
        #[cfg(feature = "debug_conditions")] trigger_event: l.trigger_event.clone(),
        target: l.target.clone(),
    }
}

fn build_opponentlivesuccess(l: &ConditionLocals) -> Condition {
    Condition::OpponentLiveSuccess {
        #[cfg(feature = "debug_conditions")] text: l.text.clone(),
        negation: l.negation.clone(),
        phase: l.phase.clone(),
        phase_target: l.phase_target.clone(),
        cache: l.cache.clone(),
        #[cfg(feature = "debug_conditions")] trigger_event: l.trigger_event.clone(),
        no_excess_heart: l.no_excess_heart.clone(),
    }
}

fn build_noexcessheart(l: &ConditionLocals) -> Condition {
    Condition::NoExcessHeart {
        #[cfg(feature = "debug_conditions")] text: l.text.clone(),
        negation: l.negation.clone(),
        phase: l.phase.clone(),
        phase_target: l.phase_target.clone(),
        cache: l.cache.clone(),
        #[cfg(feature = "debug_conditions")] trigger_event: l.trigger_event.clone(),
        target: l.target.clone(),
    }
}

fn build_alwaystrue(l: &ConditionLocals) -> Condition {
    Condition::AlwaysTrue {
        #[cfg(feature = "debug_conditions")] text: l.text.clone(),
        negation: l.negation.clone(),
        phase: l.phase.clone(),
        phase_target: l.phase_target.clone(),
        cache: l.cache.clone(),
        #[cfg(feature = "debug_conditions")] trigger_event: l.trigger_event.clone(),
    }
}

fn build_anyof(l: &ConditionLocals) -> Condition {
    Condition::AnyOf {
        #[cfg(feature = "debug_conditions")] text: l.text.clone(),
        negation: l.negation.clone(),
        phase: l.phase.clone(),
        phase_target: l.phase_target.clone(),
        cache: l.cache.clone(),
        #[cfg(feature = "debug_conditions")] trigger_event: l.trigger_event.clone(),
        any_of: l.any_of.clone(),
    }
}

fn build_allrevealedmatchheartcolor(l: &ConditionLocals) -> Condition {
    Condition::AllRevealedMatchHeartColor {
        #[cfg(feature = "debug_conditions")] text: l.text.clone(),
        negation: l.negation.clone(),
        phase: l.phase.clone(),
        phase_target: l.phase_target.clone(),
        cache: l.cache.clone(),
        #[cfg(feature = "debug_conditions")] trigger_event: l.trigger_event.clone(),
        count: l.count.clone(),
        operator: l.operator.clone(),
    }
}

/// Direct decoder for TAG_OBJECT_VARIANT conditions.
fn decode_condition_direct(
    bc: &mut BcReader,
    variant: u8,
) -> Option<Condition> {
    let count = bc.read_len()?;
    let mut l = ConditionLocals::default();
    for _ in 0..count {
        let key = bc.key()?;
        decode_condition_field(bc, key, &mut l)?;
    }
    Some(match variant {
        0 => build_compound(&l),
        1 => build_location(&l),
        2 => build_comparison(&l),
        3 => build_movement(&l),
        4 => build_group(&l),
        5 => build_appearance(&l),
        6 => build_temporal(&l),
        7 => build_state(&l),
        8 => build_resource(&l),
        9 => build_abilityfilter(&l),
        10 => build_scorethreshold(&l),
        11 => build_choice(&l),
        12 => build_complex(&l),
        13 => build_positioncond(&l),
        14 => build_opponentchoice(&l),
        15 => build_opponentlivesuccess(&l),
        16 => build_noexcessheart(&l),
        17 => build_alwaystrue(&l),
        18 => build_anyof(&l),
        19 => build_allrevealedmatchheartcolor(&l),
        _ => return None,
    })
}
