// AUTO-GENERATED by generate_effect_decoder.py — DO NOT EDIT
// Re-run: python cards/generate_effect_decoder.py

/// Read one field from a TAG_OBJECT_VARIANT effect object.
/// Returns true if the field was recognized and consumed, false to skip.
fn decode_effect_field(bc: &mut BcReader, key: &str,
    // AbilityEffect fields
    text: &mut ArcStr, action: &mut ActionType,
    source: &mut Option<ArcStr>, destination: &mut Option<ArcStr>,
    count_val: &mut Option<u8>, target: &mut Option<ArcStr>,
    condition: &mut Option<Box<Condition>>,
    non_stackable: &mut Option<bool>, conditional: &mut Option<bool>,
    is_further: &mut Option<bool>, optional: &mut Option<bool>,
    max: &mut Option<bool>,
    effect_steps: &mut Option<Vec<Box<AbilityEffect>>>,
    // CompoundBranch fields
    look_action: &mut Option<Box<AbilityEffect>>,
    select_action: &mut Option<Box<AbilityEffect>>,
    actions: &mut Option<Vec<Box<AbilityEffect>>>,
    primary_effect: &mut Option<Box<AbilityEffect>>,
    alternative_condition: &mut Option<Box<Condition>>,
    result_condition: &mut Option<Box<Condition>>,
    followup_action: &mut Option<Box<AbilityEffect>>,
    optional_action: &mut Option<Box<AbilityEffect>>,
    conditional_action: &mut Option<Box<AbilityEffect>>,
    conditional_negation: &mut Option<bool>,
    // EffectKind shared fields (all variants)
    ek: &mut EffectKindLocals,
) -> Option<bool> {
    match key {
            "text" => { *text = bc.read_string_value().map(ArcStr::from).unwrap_or_default(); return Some(true); }
            "action" => { *action = ActionType::from_str(&bc.read_string_value().unwrap_or_default()).unwrap_or_default(); return Some(true); }
            "source" => { *source = bc.read_arc_str_value(); return Some(true); }
            "destination" => { *destination = bc.read_arc_str_value(); return Some(true); }
            "count" => { *count_val = bc.read_u8_value(); return Some(true); }
            "target" => { *target = bc.read_arc_str_value(); return Some(true); }
            "condition" => { *condition = bc.read_condition_value(); return Some(true); }
            "non_stackable" => { *non_stackable = bc.read_bool_value(); return Some(true); }
            "conditional" => { *conditional = bc.read_bool_value(); return Some(true); }
            "is_further" => { *is_further = bc.read_bool_value(); return Some(true); }
            "optional" => { *optional = bc.read_bool_value(); return Some(true); }
            "max" => { *max = bc.read_bool_value(); return Some(true); }
            "effect_steps" => { *effect_steps = bc.read_effect_vec_value(); return Some(true); }
            "look_action" => { *look_action = bc.read_effect_value(); return Some(true); }
            "select_action" => { *select_action = bc.read_effect_value(); return Some(true); }
            "actions" => { *actions = bc.read_effect_vec_value(); return Some(true); }
            "primary_effect" => { *primary_effect = bc.read_effect_value(); return Some(true); }
            "alternative_condition" => { *alternative_condition = bc.read_condition_value(); return Some(true); }
            "result_condition" => { *result_condition = bc.read_condition_value(); return Some(true); }
            "followup_action" => { *followup_action = bc.read_effect_value(); return Some(true); }
            "optional_action" => { *optional_action = bc.read_effect_value(); return Some(true); }
            "conditional_action" => { *conditional_action = bc.read_effect_value(); return Some(true); }
            "conditional_negation" => { *conditional_negation = bc.read_bool_value(); return Some(true); }
            "ability_filter" => { ek.ability_filter = bc.read_ability_filter_value(); return Some(true); }
            "ability_filter_triggers" => { ek.ability_filter_triggers = bc.read_opt_str_vec_value(); return Some(true); }
            "ability_gain" => { ek.ability_gain = bc.read_arc_str_value(); return Some(true); }
            "ability_gain_trigger" => { ek.ability_gain_trigger = bc.read_arc_str_value(); return Some(true); }
            "ability_text" => { ek.ability_text = bc.read_arc_str_value(); return Some(true); }
            "action_by" => { ek.action_by = bc.read_arc_str_value(); return Some(true); }
            "activation_condition_parsed" => { ek.activation_condition_parsed = bc.read_condition_value(); return Some(true); }
            "activation_position" => { ek.activation_position = bc.read_arc_str_value(); return Some(true); }
            "all" => { ek.all = bc.read_bool_value(); return Some(true); }
            "all_regions" => { ek.all_regions = bc.read_bool_value(); return Some(true); }
            "allow_occupied_stage" => { ek.allow_occupied_stage = bc.read_bool_value(); return Some(true); }
            "alternative_condition" => { ek.alternative_condition = bc.read_condition_value(); return Some(true); }
            "alternative_count_type" => { ek.alternative_count_type = bc.read_arc_str_value(); return Some(true); }
            "alternative_effect" => { ek.alternative_effect = bc.read_effect_value(); return Some(true); }
            "answers" => { ek.answers = bc.read_opt_str_vec_value(); return Some(true); }
            "any_number" => { ek.any_number = bc.read_bool_value(); return Some(true); }
            "baton_touch_trigger" => { ek.baton_touch_trigger = bc.read_bool_value(); return Some(true); }
            "blade_limit" => { ek.blade_limit = bc.read_u8_value(); return Some(true); }
            "blade_limit_operator" => { ek.blade_limit_operator = bc.read_operator_value(); return Some(true); }
            "blade_type" => { ek.blade_type = bc.read_arc_str_value().map(|s| Box::new(s)); return Some(true); }
            "blind" => { ek.blind = bc.read_bool_value(); return Some(true); }
            "card_names" => { ek.card_names = bc.read_str_vec_value(); return Some(true); }
            "card_property" => { ek.card_property = bc.read_arc_str_value(); return Some(true); }
            "card_type" => { ek.card_type = bc.read_card_type_value(); return Some(true); }
            "characters" => { ek.characters = bc.read_opt_str_vec_value(); return Some(true); }
            "choice" => { ek.choice = bc.read_bool_value(); return Some(true); }
            "choice_based" => { ek.choice_based = bc.read_bool_value(); return Some(true); }
            "choice_condition" => { ek.choice_condition = bc.read_condition_value(); return Some(true); }
            "choice_maker" => { ek.choice_maker = bc.read_arc_str_value(); return Some(true); }
            "choice_options" => { ek.choice_options = bc.read_opt_str_vec_value(); return Some(true); }
            "choice_type" => { ek.choice_type = bc.read_arc_str_value(); return Some(true); }
            "cost_from_revealed" => { ek.cost_from_revealed = bc.read_bool_value(); return Some(true); }
            "cost_limit" => { ek.cost_limit = bc.read_u8_value(); return Some(true); }
            "cost_limit_max" => { ek.cost_limit_max = bc.read_u8_value(); return Some(true); }
            "cost_limit_min" => { ek.cost_limit_min = bc.read_u8_value(); return Some(true); }
            "cost_limit_operator" => { ek.cost_limit_operator = bc.read_operator_value(); return Some(true); }
            "cost_offset" => { ek.cost_offset = bc.read_i8_value(); return Some(true); }
            "cost_reference" => { ek.cost_reference = bc.read_arc_str_value(); return Some(true); }
            "cost_total" => { ek.cost_total = bc.read_u8_value(); return Some(true); }
            "cost_total_operator" => { ek.cost_total_operator = bc.read_operator_value(); return Some(true); }
            "count" => { ek.count = bc.read_u8_value(); return Some(true); }
            "delayed" => { ek.delayed = bc.read_bool_value(); return Some(true); }
            "destination" => { ek.destination = bc.read_arc_str_value(); return Some(true); }
            "discard_remaining" => { ek.discard_remaining = bc.read_bool_value(); return Some(true); }
            "distinct" => { ek.distinct = bc.read_distinct_value(); return Some(true); }
            "duration" => { ek.duration = bc.read_arc_str_value(); return Some(true); }
            "dynamic_count" => { ek.dynamic_count = bc.read_dynamic_count_value(); return Some(true); }
            "effect_constraint" => { ek.effect_constraint = bc.read_arc_str_value(); return Some(true); }
            "effect_type" => { ek.effect_type = bc.read_arc_str_value(); return Some(true); }
            "energy_count" => { ek.energy_count = bc.read_u8_value(); return Some(true); }
            "exclude_by_name_source" => { ek.exclude_by_name_source = bc.read_arc_str_value(); return Some(true); }
            "exclude_characters" => { ek.exclude_characters = bc.read_opt_str_vec_value(); return Some(true); }
            "exclude_group_names" => { ek.exclude_group_names = bc.read_opt_str_vec_value(); return Some(true); }
            "exclude_heart_colors" => { ek.exclude_heart_colors = bc.read_opt_str_vec_value(); return Some(true); }
            "exclude_position" => { ek.exclude_position = bc.read_arc_str_value(); return Some(true); }
            "exclude_selected" => { ek.exclude_selected = bc.read_bool_value(); return Some(true); }
            "exclude_self" => { ek.exclude_self = bc.read_bool_value(); return Some(true); }
            "filter_targets_by_heart_colors" => { ek.filter_targets_by_heart_colors = bc.read_bool_value(); return Some(true); }
            "gained_effect" => { ek.gained_effect = bc.read_effect_value(); return Some(true); }
            "group_names" => { ek.group_names = bc.read_opt_str_vec_value(); return Some(true); }
            "group_reference" => { ek.group_reference = bc.read_arc_str_value(); return Some(true); }
            "heart_color" => { ek.heart_color = bc.read_arc_str_value(); return Some(true); }
            "heart_color_count" => { ek.heart_color_count = bc.read_u8_value(); return Some(true); }
            "heart_colors" => { ek.heart_colors = bc.read_str_vec_value(); return Some(true); }
            "heart_colors_from_selected_card" => { ek.heart_colors_from_selected_card = bc.read_bool_value(); return Some(true); }
            "heart_selection" => { ek.heart_selection = bc.read_bool_value(); return Some(true); }
            "heart_type" => { ek.heart_type = bc.read_arc_str_value(); return Some(true); }
            "id" => { ek.id = bc.read_arc_str_value().map(|s| Box::new(s)); return Some(true); }
            "identities" => { ek.identities = bc.read_opt_str_vec_value(); return Some(true); }
            "is_reveal" => { ek.is_reveal = bc.read_bool_value(); return Some(true); }
            "location" => { ek.location = bc.read_arc_str_value(); return Some(true); }
            "lose_blade_hearts" => { ek.lose_blade_hearts = bc.read_bool_value(); return Some(true); }
            "max_repeats" => { ek.max_repeats = bc.read_u8_value(); ek.repeat_limit = ek.max_repeats.clone(); return Some(true); }
            "multiple_targets" => { ek.multiple_targets = bc.read_bool_value(); return Some(true); }
            "name_constraint" => { ek.name_constraint = bc.read_arc_str_value(); return Some(true); }
            "name_constraint_source" => { ek.name_constraint_source = bc.read_arc_str_value(); return Some(true); }
            "need_heart_color" => { ek.need_heart_color = bc.read_arc_str_value(); return Some(true); }
            "need_heart_operator" => { ek.need_heart_operator = bc.read_operator_value(); return Some(true); }
            "need_heart_total" => { ek.need_heart_total = bc.read_u8_value(); return Some(true); }
            "negation" => { ek.negation = bc.read_bool_value(); return Some(true); }
            "non_stackable" => { ek.non_stackable = bc.read_bool_value(); return Some(true); }
            "operation" => { ek.operation = bc.read_arc_str_value(); return Some(true); }
            "opponent_action" => { ek.opponent_action = bc.read_effect_value(); return Some(true); }
            "option" => { ek.option = bc.read_arc_str_value(); return Some(true); }
            "optional" => { ek.optional = bc.read_bool_value(); return Some(true); }
            "options" => { ek.options = bc.read_effect_vec_boxed_value(); return Some(true); }
            "or_ability_filters" => { ek.or_ability_filters = bc.read_or_ability_filters_value(); return Some(true); }
            "or_card_types" => { ek.or_card_types = bc.read_opt_str_vec_value(); return Some(true); }
            "original_cost" => { ek.original_cost = bc.read_u8_value(); return Some(true); }
            "original_count" => { ek.original_count = bc.read_u8_value(); return Some(true); }
            "original_operator" => { ek.original_operator = bc.read_operator_value(); return Some(true); }
            "original_value" => { ek.original_value = bc.read_bool_value(); return Some(true); }
            "parenthetical" => { ek.parenthetical = bc.read_opt_str_vec_value(); return Some(true); }
            "per_group" => { ek.per_group = bc.read_bool_value(); return Some(true); }
            "per_group_count" => { ek.per_group_count = bc.read_u8_value(); return Some(true); }
            "per_unit" => { ek.per_unit = bc.read_bool_value(); return Some(true); }
            "per_unit_count" => { ek.per_unit_count = bc.read_u8_value(); return Some(true); }
            "per_unit_heart_colors" => { ek.per_unit_heart_colors = bc.read_str_vec_value(); return Some(true); }
            "per_unit_location" => { ek.per_unit_location = bc.read_arc_str_value(); return Some(true); }
            "per_unit_type" => { ek.per_unit_type = bc.read_arc_str_value(); return Some(true); }
            "phase" => { ek.phase = bc.read_arc_str_value(); return Some(true); }
            "picker" => { ek.picker = bc.read_arc_str_value(); return Some(true); }
            "placement_order" => { ek.placement_order = bc.read_placement_order_value(); return Some(true); }
            "position" => { ek.position = bc.read_position_value(); return Some(true); }
            "question" => { ek.question = bc.read_arc_str_value(); return Some(true); }
            "quoted_text" => { ek.quoted_text = bc.read_quoted_text_value(); return Some(true); }
            "ref_offset" => { ek.ref_offset = bc.read_i8_value(); return Some(true); }
            "ref_value" => { ek.ref_value = bc.read_arc_str_value().map(|s| Box::new(s)); return Some(true); }
            "repeat_limit" => { ek.repeat_limit = bc.read_u8_value(); return Some(true); }
            "replace_all" => { ek.replace_all = bc.read_bool_value(); return Some(true); }
            "replaces_event" => { ek.replaces_event = bc.read_arc_str_value(); return Some(true); }
            "require_all_heart_colors" => { ek.require_all_heart_colors = bc.read_bool_value(); return Some(true); }
            "resource" => { ek.resource = bc.read_arc_str_value(); return Some(true); }
            "resource_icon_count" => { ek.resource_icon_count = bc.read_u8_value(); return Some(true); }
            "resource_on_select" => { ek.resource_on_select = bc.read_effect_value(); return Some(true); }
            "restricted_destination" => { ek.restricted_destination = bc.read_arc_str_value(); return Some(true); }
            "restriction_type" => { ek.restriction_type = bc.read_arc_str_value(); return Some(true); }
            "reveal" => { ek.reveal = bc.read_bool_value(); return Some(true); }
            "same_name" => { ek.same_name = bc.read_bool_value(); return Some(true); }
            "same_unit_name" => { ek.same_unit_name = bc.read_bool_value(); return Some(true); }
            "self_cost" => { ek.self_cost = bc.read_bool_value(); return Some(true); }
            "self_target" => { ek.self_target = bc.read_bool_value(); return Some(true); }
            "shuffle" => { ek.shuffle = bc.read_bool_value(); return Some(true); }
            "sign" => { ek.sign = bc.read_arc_str_value(); return Some(true); }
            "source" => { ek.source = bc.read_arc_str_value(); return Some(true); }
            "source_card" => { ek.source_card = bc.read_arc_str_value(); return Some(true); }
            "source_position" => { ek.source_position = bc.read_arc_str_value(); return Some(true); }
            "state" => { ek.state = bc.read_effect_state_value(); return Some(true); }
            "state_change" => { ek.state_change = bc.read_effect_state_value(); return Some(true); }
            "suppressed_trigger" => { ek.suppressed_trigger = bc.read_arc_str_value(); return Some(true); }
            "target" => { ek.target = bc.read_arc_str_value(); return Some(true); }
            "target_count" => { ek.target_count = bc.read_u8_value(); return Some(true); }
            "target_from_selection" => { ek.target_from_selection = bc.read_bool_value(); return Some(true); }
            "target_member" => { ek.target_member = bc.read_arc_str_value(); return Some(true); }
            "target_trigger" => { ek.target_trigger = bc.read_arc_str_value(); return Some(true); }
            "timing" => { ek.timing = bc.read_arc_str_value(); return Some(true); }
            "timing_condition" => { ek.timing_condition = bc.read_arc_str_value(); return Some(true); }
            "treat_as" => { ek.treat_as = bc.read_arc_str_value(); return Some(true); }
            "trigger_filter" => { ek.trigger_filter = bc.read_opt_str_vec_value(); return Some(true); }
            "trigger_type" => { ek.trigger_type = bc.read_arc_str_value(); return Some(true); }
            "triggers" => { ek.triggers = bc.read_arc_str_value(); return Some(true); }
            "use_limit" => { ek.use_limit = bc.read_u8_value(); return Some(true); }
            "value" => { ek.value = bc.read_u8_value(); return Some(true); }
            "energy" => { ek.energy_count = bc.read_u8_value(); return Some(true); }
            "energy" => { ek.energy_count = bc.read_u8_value(); return Some(true); }
            _ => { bc.skip_value()?; return Some(true); }
        }
    }

/// Accumulator for EffectKind fields during direct decode.
#[derive(Default)]
pub(crate) struct EffectKindLocals {
    pub ability_filter: Option<AbilityFilter>,
    pub ability_filter_triggers: Option<Box<Vec<String>>>,
    pub ability_gain: Option<ArcStr>,
    pub ability_gain_trigger: Option<ArcStr>,
    pub ability_text: Option<ArcStr>,
    pub action_by: Option<ArcStr>,
    pub activation_condition_parsed: Option<Box<Condition>>,
    pub activation_position: Option<ArcStr>,
    pub all: Option<bool>,
    pub all_regions: Option<bool>,
    pub allow_occupied_stage: Option<bool>,
    pub alternative_condition: Option<Box<Condition>>,
    pub alternative_count_type: Option<ArcStr>,
    pub alternative_effect: Option<Box<AbilityEffect>>,
    pub answers: Option<Box<Vec<String>>>,
    pub any_number: Option<bool>,
    pub baton_touch_trigger: Option<bool>,
    pub blade_limit: Option<u8>,
    pub blade_limit_operator: Option<Operator>,
    pub blade_type: Option<Box<ArcStr>>,
    pub blind: Option<bool>,
    pub card_names: Box<Vec<String>>,
    pub card_property: Option<ArcStr>,
    pub card_type: Option<CardType>,
    pub characters: Option<Box<Vec<String>>>,
    pub choice: Option<bool>,
    pub choice_based: Option<bool>,
    pub choice_condition: Option<Box<Condition>>,
    pub choice_maker: Option<ArcStr>,
    pub choice_options: Option<Box<Vec<String>>>,
    pub choice_type: Option<ArcStr>,
    pub cost_from_revealed: Option<bool>,
    pub cost_limit: Option<u8>,
    pub cost_limit_max: Option<u8>,
    pub cost_limit_min: Option<u8>,
    pub cost_limit_operator: Option<Operator>,
    pub cost_offset: Option<i8>,
    pub cost_reference: Option<ArcStr>,
    pub cost_total: Option<u8>,
    pub cost_total_operator: Option<Operator>,
    pub count: Option<u8>,
    pub delayed: Option<bool>,
    pub destination: Option<ArcStr>,
    pub discard_remaining: Option<bool>,
    pub distinct: Option<Box<DistinctType>>,
    pub duration: Option<ArcStr>,
    pub dynamic_count: Option<Box<DynamicCount>>,
    pub effect_constraint: Option<ArcStr>,
    pub effect_type: Option<ArcStr>,
    pub energy_count: Option<u8>,
    pub exclude_by_name_source: Option<ArcStr>,
    pub exclude_characters: Option<Box<Vec<String>>>,
    pub exclude_group_names: Option<Box<Vec<String>>>,
    pub exclude_heart_colors: Option<Box<Vec<String>>>,
    pub exclude_position: Option<ArcStr>,
    pub exclude_selected: Option<bool>,
    pub exclude_self: Option<bool>,
    pub filter_targets_by_heart_colors: Option<bool>,
    pub gained_effect: Option<Box<AbilityEffect>>,
    pub group_names: Option<Box<Vec<String>>>,
    pub group_reference: Option<ArcStr>,
    pub heart_color: Option<ArcStr>,
    pub heart_color_count: Option<u8>,
    pub heart_colors: Box<Vec<String>>,
    pub heart_colors_from_selected_card: Option<bool>,
    pub heart_selection: Option<bool>,
    pub heart_type: Option<ArcStr>,
    pub id: Option<Box<ArcStr>>,
    pub identities: Option<Box<Vec<String>>>,
    pub is_reveal: Option<bool>,
    pub location: Option<ArcStr>,
    pub lose_blade_hearts: Option<bool>,
    pub max_repeats: Option<u8>,
    pub multiple_targets: Option<bool>,
    pub name_constraint: Option<ArcStr>,
    pub name_constraint_source: Option<ArcStr>,
    pub need_heart_color: Option<ArcStr>,
    pub need_heart_operator: Option<Operator>,
    pub need_heart_total: Option<u8>,
    pub negation: Option<bool>,
    pub non_stackable: Option<bool>,
    pub operation: Option<ArcStr>,
    pub opponent_action: Option<Box<AbilityEffect>>,
    pub option: Option<ArcStr>,
    pub optional: Option<bool>,
    pub options: Option<Box<Vec<Box<AbilityEffect>>>>,
    pub or_ability_filters: Option<Box<Vec<AbilityFilterBranch>>>,
    pub or_card_types: Option<Box<Vec<String>>>,
    pub original_cost: Option<u8>,
    pub original_count: Option<u8>,
    pub original_operator: Option<Operator>,
    pub original_value: Option<bool>,
    pub parenthetical: Option<Box<Vec<String>>>,
    pub per_group: Option<bool>,
    pub per_group_count: Option<u8>,
    pub per_unit: Option<bool>,
    pub per_unit_count: Option<u8>,
    pub per_unit_heart_colors: Box<Vec<String>>,
    pub per_unit_location: Option<ArcStr>,
    pub per_unit_type: Option<ArcStr>,
    pub phase: Option<ArcStr>,
    pub picker: Option<ArcStr>,
    pub placement_order: Option<PlacementOrder>,
    pub position: Option<Box<PositionInfo>>,
    pub question: Option<ArcStr>,
    pub quoted_text: Option<Box<QuotedText>>,
    pub ref_offset: Option<i8>,
    pub ref_value: Option<Box<ArcStr>>,
    pub repeat_limit: Option<u8>,
    pub replace_all: Option<bool>,
    pub replaces_event: Option<ArcStr>,
    pub require_all_heart_colors: Option<bool>,
    pub resource: Option<ArcStr>,
    pub resource_icon_count: Option<u8>,
    pub resource_on_select: Option<Box<AbilityEffect>>,
    pub restricted_destination: Option<ArcStr>,
    pub restriction_type: Option<ArcStr>,
    pub reveal: Option<bool>,
    pub same_name: Option<bool>,
    pub same_unit_name: Option<bool>,
    pub self_cost: Option<bool>,
    pub self_target: Option<bool>,
    pub shuffle: Option<bool>,
    pub sign: Option<ArcStr>,
    pub source: Option<ArcStr>,
    pub source_card: Option<ArcStr>,
    pub source_position: Option<ArcStr>,
    pub state: Option<Box<EffectState>>,
    pub state_change: Option<Box<EffectState>>,
    pub suppressed_trigger: Option<ArcStr>,
    pub target: Option<ArcStr>,
    pub target_count: Option<u8>,
    pub target_from_selection: Option<bool>,
    pub target_member: Option<ArcStr>,
    pub target_trigger: Option<ArcStr>,
    pub timing: Option<ArcStr>,
    pub timing_condition: Option<ArcStr>,
    pub treat_as: Option<ArcStr>,
    pub trigger_filter: Option<Box<Vec<String>>>,
    pub trigger_type: Option<ArcStr>,
    pub triggers: Option<ArcStr>,
    pub use_limit: Option<u8>,
    pub value: Option<u8>,
}

fn build_abilityop(ek: &EffectKindLocals) -> EffectKind {
    EffectKind::AbilityOp {
        source: ek.source.clone(),
        target: ek.target.clone(),
        destination: ek.destination.clone(),
        ability_gain: ek.ability_gain.clone(),
        ability_gain_trigger: ek.ability_gain_trigger.clone(),
        gained_effect: ek.gained_effect.clone(),
        ability_text: ek.ability_text.clone(),
        target_trigger: ek.target_trigger.clone(),
        source_card: ek.source_card.clone(),
        suppressed_trigger: ek.suppressed_trigger.clone(),
        card_type: ek.card_type.clone(),
        group_names: ek.group_names.clone(),
        exclude_group_names: ek.exclude_group_names.clone(),
        characters: ek.characters.clone(),
        exclude_characters: ek.exclude_characters.clone(),
        cost_limit: ek.cost_limit.clone(),
        cost_limit_operator: ek.cost_limit_operator.clone(),
        location: ek.location.clone(),
        trigger_filter: ek.trigger_filter.clone(),
        trigger_type: ek.trigger_type.clone(),
        duration: ek.duration.clone(),
        self_target: ek.self_target.clone(),
        exclude_self: ek.exclude_self.clone(),
        effect_type: ek.effect_type.clone(),
        use_limit: ek.use_limit.clone(),
        triggers: ek.triggers.clone(),
        activation_condition_parsed: ek.activation_condition_parsed.clone(),
        option: ek.option.clone(),
        all: ek.all.clone(),
        activation_position: ek.activation_position.clone(),
        heart_colors: ek.heart_colors.clone(),
        dynamic_count: ek.dynamic_count.clone(),
        same_name: ek.same_name.clone(),
        same_unit_name: ek.same_unit_name.clone(),
    }
}

fn build_changestate(ek: &EffectKindLocals) -> EffectKind {
    EffectKind::ChangeState {
        source: ek.source.clone(),
        target: ek.target.clone(),
        destination: ek.destination.clone(),
        state_change: ek.state_change.clone(),
        card_type: ek.card_type.clone(),
        cost_limit: ek.cost_limit.clone(),
        cost_limit_operator: ek.cost_limit_operator.clone(),
        cost_from_revealed: ek.cost_from_revealed.clone(),
        optional: ek.optional.clone(),
        self_cost: ek.self_cost.clone(),
        characters: ek.characters.clone(),
        exclude_characters: ek.exclude_characters.clone(),
        group_names: ek.group_names.clone(),
        exclude_group_names: ek.exclude_group_names.clone(),
        blade_limit: ek.blade_limit.clone(),
        blade_limit_operator: ek.blade_limit_operator.clone(),
        per_unit: ek.per_unit.clone(),
        per_unit_count: ek.per_unit_count.clone(),
        per_unit_type: ek.per_unit_type.clone(),
        per_unit_heart_colors: ek.per_unit_heart_colors.clone(),
        per_unit_location: ek.per_unit_location.clone(),
        location: ek.location.clone(),
        distinct: ek.distinct.clone(),
        exclude_self: ek.exclude_self.clone(),
        self_target: ek.self_target.clone(),
        identities: ek.identities.clone(),
        all_regions: ek.all_regions.clone(),
        card_names: ek.card_names.clone(),
        negation: ek.negation.clone(),
        cost_total: ek.cost_total.clone(),
        cost_total_operator: ek.cost_total_operator.clone(),
        card_property: ek.card_property.clone(),
        original_value: ek.original_value.clone(),
        name_constraint: ek.name_constraint.clone(),
        name_constraint_source: ek.name_constraint_source.clone(),
        filter_targets_by_heart_colors: ek.filter_targets_by_heart_colors.clone(),
        group_reference: ek.group_reference.clone(),
        activation_position: ek.activation_position.clone(),
        ability_filter: ek.ability_filter.clone(),
        ability_filter_triggers: ek.ability_filter_triggers.clone(),
        or_ability_filters: ek.or_ability_filters.clone(),
        exclude_heart_colors: ek.exclude_heart_colors.clone(),
        heart_colors: ek.heart_colors.clone(),
        all: ek.all.clone(),
        position: ek.position.clone(),
        state: ek.state.clone(),
        action_by: ek.action_by.clone(),
        activation_condition_parsed: ek.activation_condition_parsed.clone(),
        same_name: ek.same_name.clone(),
        same_unit_name: ek.same_unit_name.clone(),
    }
}

fn build_compoundeffect(ek: &EffectKindLocals) -> EffectKind {
    EffectKind::CompoundEffect {
        source: ek.source.clone(),
        target: ek.target.clone(),
        destination: ek.destination.clone(),
        repeat_limit: ek.repeat_limit.clone(),
        options: ek.options.clone(),
        choice_type: ek.choice_type.clone(),
        choice_options: ek.choice_options.clone(),
        question: ek.question.clone(),
        answers: ek.answers.clone(),
        choice_maker: ek.choice_maker.clone(),
        alternative_effect: ek.alternative_effect.clone(),
        optional: ek.optional.clone(),
        target_count: ek.target_count.clone(),
        group_names: ek.group_names.clone(),
        heart_colors: ek.heart_colors.clone(),
        exclude_self: ek.exclude_self.clone(),
        duration: ek.duration.clone(),
        position: ek.position.clone(),
        all: ek.all.clone(),
        activation_position: ek.activation_position.clone(),
        card_type: ek.card_type.clone(),
        trigger_type: ek.trigger_type.clone(),
        activation_condition_parsed: ek.activation_condition_parsed.clone(),
        original_value: ek.original_value.clone(),
        shuffle: ek.shuffle.clone(),
        distinct: ek.distinct.clone(),
        group_reference: ek.group_reference.clone(),
        per_unit: ek.per_unit.clone(),
        per_unit_count: ek.per_unit_count.clone(),
        per_unit_type: ek.per_unit_type.clone(),
        alternative_count_type: ek.alternative_count_type.clone(),
        choice_condition: ek.choice_condition.clone(),
        alternative_condition: ek.alternative_condition.clone(),
        same_name: ek.same_name.clone(),
        same_unit_name: ek.same_unit_name.clone(),
    }
}

fn build_customop(ek: &EffectKindLocals) -> EffectKind {
    EffectKind::CustomOp {
        action_by: ek.action_by.clone(),
        opponent_action: ek.opponent_action.clone(),
        effect_type: ek.effect_type.clone(),
        replaces_event: ek.replaces_event.clone(),
        choice_based: ek.choice_based.clone(),
        card_type: ek.card_type.clone(),
        group_names: ek.group_names.clone(),
        exclude_group_names: ek.exclude_group_names.clone(),
        characters: ek.characters.clone(),
        exclude_characters: ek.exclude_characters.clone(),
        identities: ek.identities.clone(),
        all_regions: ek.all_regions.clone(),
        question: ek.question.clone(),
        answers: ek.answers.clone(),
        choice_maker: ek.choice_maker.clone(),
        options: ek.options.clone(),
        card_property: ek.card_property.clone(),
        location: ek.location.clone(),
        duration: ek.duration.clone(),
        self_target: ek.self_target.clone(),
        exclude_self: ek.exclude_self.clone(),
        original_value: ek.original_value.clone(),
        timing: ek.timing.clone(),
        treat_as: ek.treat_as.clone(),
        trigger_type: ek.trigger_type.clone(),
        trigger_filter: ek.trigger_filter.clone(),
        activation_condition_parsed: ek.activation_condition_parsed.clone(),
        use_limit: ek.use_limit.clone(),
        triggers: ek.triggers.clone(),
        same_name: ek.same_name.clone(),
        same_unit_name: ek.same_unit_name.clone(),
    }
}

fn build_drawcards(ek: &EffectKindLocals) -> EffectKind {
    EffectKind::DrawCards {
        source: ek.source.clone(),
        target: ek.target.clone(),
        destination: ek.destination.clone(),
        target_count: ek.target_count.clone(),
        count: ek.count.clone(),
        card_type: ek.card_type.clone(),
        dynamic_count: ek.dynamic_count.clone(),
        card_names: ek.card_names.clone(),
        location: ek.location.clone(),
        exclude_self: ek.exclude_self.clone(),
        per_unit: ek.per_unit.clone(),
        per_unit_count: ek.per_unit_count.clone(),
        per_unit_type: ek.per_unit_type.clone(),
        per_unit_heart_colors: ek.per_unit_heart_colors.clone(),
        per_unit_location: ek.per_unit_location.clone(),
        position: ek.position.clone(),
        state: ek.state.clone(),
        heart_colors: ek.heart_colors.clone(),
        trigger_type: ek.trigger_type.clone(),
        original_value: ek.original_value.clone(),
        action_by: ek.action_by.clone(),
        same_name: ek.same_name.clone(),
        same_unit_name: ek.same_unit_name.clone(),
    }
}

fn build_gainresource(ek: &EffectKindLocals) -> EffectKind {
    EffectKind::GainResource {
        resource: ek.resource.clone(),
        heart_colors: ek.heart_colors.clone(),
        heart_colors_from_selected_card: ek.heart_colors_from_selected_card.clone(),
        sign: ek.sign.clone(),
        operation: ek.operation.clone(),
        value: ek.value.clone(),
        energy_count: ek.energy_count.clone(),
        dynamic_count: ek.dynamic_count.clone(),
        optional: ek.optional.clone(),
        duration: ek.duration.clone(),
        position: ek.position.clone(),
        any_number: ek.any_number.clone(),
        per_unit: ek.per_unit.clone(),
        per_unit_count: ek.per_unit_count.clone(),
        per_unit_type: ek.per_unit_type.clone(),
        per_unit_heart_colors: ek.per_unit_heart_colors.clone(),
        per_unit_location: ek.per_unit_location.clone(),
        location: ek.location.clone(),
        group_names: ek.group_names.clone(),
        card_type: ek.card_type.clone(),
        cost_limit: ek.cost_limit.clone(),
        cost_limit_operator: ek.cost_limit_operator.clone(),
        characters: ek.characters.clone(),
        exclude_characters: ek.exclude_characters.clone(),
        exclude_group_names: ek.exclude_group_names.clone(),
        self_target: ek.self_target.clone(),
        target_from_selection: ek.target_from_selection.clone(),
        card_property: ek.card_property.clone(),
        original_value: ek.original_value.clone(),
        negation: ek.negation.clone(),
        filter_targets_by_heart_colors: ek.filter_targets_by_heart_colors.clone(),
        activation_position: ek.activation_position.clone(),
        state: ek.state.clone(),
        heart_type: ek.heart_type.clone(),
        target_count: ek.target_count.clone(),
        all: ek.all.clone(),
        same_name: ek.same_name.clone(),
        exclude_self: ek.exclude_self.clone(),
        group_reference: ek.group_reference.clone(),
        trigger_type: ek.trigger_type.clone(),
        distinct: ek.distinct.clone(),
        heart_color: ek.heart_color.clone(),
        action_by: ek.action_by.clone(),
        activation_condition_parsed: ek.activation_condition_parsed.clone(),
        multiple_targets: ek.multiple_targets.clone(),
        repeat_limit: ek.repeat_limit.clone(),
        timing_condition: ek.timing_condition.clone(),
        require_all_heart_colors: ek.require_all_heart_colors.clone(),
        heart_color_count: ek.heart_color_count.clone(),
        same_unit_name: ek.same_unit_name.clone(),
    }
}

fn build_lookreveal(ek: &EffectKindLocals) -> EffectKind {
    EffectKind::LookReveal {
        source: ek.source.clone(),
        target: ek.target.clone(),
        destination: ek.destination.clone(),
        card_type: ek.card_type.clone(),
        characters: ek.characters.clone(),
        exclude_characters: ek.exclude_characters.clone(),
        group_names: ek.group_names.clone(),
        exclude_group_names: ek.exclude_group_names.clone(),
        cost_limit: ek.cost_limit.clone(),
        cost_limit_operator: ek.cost_limit_operator.clone(),
        cost_limit_min: ek.cost_limit_min.clone(),
        cost_limit_max: ek.cost_limit_max.clone(),
        card_names: ek.card_names.clone(),
        exclude_self: ek.exclude_self.clone(),
        distinct: ek.distinct.clone(),
        name_constraint: ek.name_constraint.clone(),
        name_constraint_source: ek.name_constraint_source.clone(),
        ability_filter: ek.ability_filter.clone(),
        ability_filter_triggers: ek.ability_filter_triggers.clone(),
        or_ability_filters: ek.or_ability_filters.clone(),
        card_property: ek.card_property.clone(),
        original_value: ek.original_value.clone(),
        negation: ek.negation.clone(),
        self_target: ek.self_target.clone(),
        per_unit: ek.per_unit.clone(),
        per_unit_count: ek.per_unit_count.clone(),
        per_unit_type: ek.per_unit_type.clone(),
        per_unit_heart_colors: ek.per_unit_heart_colors.clone(),
        per_unit_location: ek.per_unit_location.clone(),
        location: ek.location.clone(),
        group_reference: ek.group_reference.clone(),
        dynamic_count: ek.dynamic_count.clone(),
        heart_colors: ek.heart_colors.clone(),
        reveal: ek.reveal.clone(),
        filter_targets_by_heart_colors: ek.filter_targets_by_heart_colors.clone(),
        activation_position: ek.activation_position.clone(),
        state: ek.state.clone(),
        optional: ek.optional.clone(),
        blind: ek.blind.clone(),
        is_reveal: ek.is_reveal.clone(),
        picker: ek.picker.clone(),
        multiple_targets: ek.multiple_targets.clone(),
        options: ek.options.clone(),
        resource_on_select: ek.resource_on_select.clone(),
        require_all_heart_colors: ek.require_all_heart_colors.clone(),
        heart_color_count: ek.heart_color_count.clone(),
        same_name: ek.same_name.clone(),
        same_unit_name: ek.same_unit_name.clone(),
    }
}

fn build_miscop(ek: &EffectKindLocals) -> EffectKind {
    EffectKind::MiscOp {
        source: ek.source.clone().map(|s| Box::new(s)),
        target: ek.target.clone().map(|s| Box::new(s)),
        destination: ek.destination.clone().map(|s| Box::new(s)),
        operation: ek.operation.clone().map(|s| Box::new(s)),
        value: ek.value.clone(),
        card_type: ek.card_type.clone(),
        group_names: ek.group_names.clone(),
        exclude_group_names: ek.exclude_group_names.clone(),
        characters: ek.characters.clone(),
        exclude_characters: ek.exclude_characters.clone(),
        cost_limit: ek.cost_limit.clone(),
        cost_limit_operator: ek.cost_limit_operator.clone(),
        location: ek.location.clone().map(|s| Box::new(s)),
        duration: ek.duration.clone().map(|s| Box::new(s)),
        heart_colors: ek.heart_colors.clone(),
        heart_type: ek.heart_type.clone().map(|s| Box::new(s)),
        heart_selection: ek.heart_selection.clone(),
        blade_type: ek.blade_type.clone(),
        self_target: ek.self_target.clone(),
        exclude_self: ek.exclude_self.clone(),
        choice: ek.choice.clone(),
        lose_blade_hearts: ek.lose_blade_hearts.clone(),
        dynamic_count: ek.dynamic_count.clone(),
        per_unit: ek.per_unit.clone(),
        per_unit_count: ek.per_unit_count.clone(),
        per_unit_type: ek.per_unit_type.clone().map(|s| Box::new(s)),
        per_unit_heart_colors: ek.per_unit_heart_colors.clone(),
        per_unit_location: ek.per_unit_location.clone().map(|s| Box::new(s)),
        repeat_limit: ek.repeat_limit.clone(),
        identities: ek.identities.clone(),
        all_regions: ek.all_regions.clone(),
        timing: ek.timing.clone().map(|s| Box::new(s)),
        treat_as: ek.treat_as.clone().map(|s| Box::new(s)),
        effect_constraint: ek.effect_constraint.clone().map(|s| Box::new(s)),
        original_value: ek.original_value.clone(),
        original_count: ek.original_count.clone(),
        original_operator: ek.original_operator.clone(),
        original_cost: ek.original_cost.clone(),
        blade_limit: ek.blade_limit.clone(),
        blade_limit_operator: ek.blade_limit_operator.clone(),
        negation: ek.negation.clone(),
        activation_position: ek.activation_position.clone().map(|s| Box::new(s)),
        target_count: ek.target_count.clone(),
        group_reference: ek.group_reference.clone().map(|s| Box::new(s)),
        parenthetical: ek.parenthetical.clone(),
        quoted_text: ek.quoted_text.clone(),
        same_unit_name: ek.same_unit_name.clone(),
        alternative_count_type: ek.alternative_count_type.clone().map(|s| Box::new(s)),
        per_group: ek.per_group.clone(),
        per_group_count: ek.per_group_count.clone(),
        resource_icon_count: ek.resource_icon_count.clone(),
        cost_total: ek.cost_total.clone(),
        cost_total_operator: ek.cost_total_operator.clone(),
        cost_reference: ek.cost_reference.clone().map(|s| Box::new(s)),
        cost_offset: ek.cost_offset.clone(),
        blind: ek.blind.clone(),
        picker: ek.picker.clone().map(|s| Box::new(s)),
        all: ek.all.clone(),
        sign: ek.sign.clone().map(|s| Box::new(s)),
        heart_color_count: ek.heart_color_count.clone(),
        require_all_heart_colors: ek.require_all_heart_colors.clone(),
        energy_count: ek.energy_count.clone(),
        placement_order: ek.placement_order.clone(),
        ref_value: ek.ref_value.clone(),
        ref_offset: ek.ref_offset.clone(),
        id: ek.id.clone(),
        card_names: ek.card_names.clone(),
        or_card_types: ek.or_card_types.clone(),
        options: ek.options.clone(),
        position: ek.position.clone(),
        ability_filter: ek.ability_filter.clone(),
        same_name: ek.same_name.clone(),
    }
}

fn build_modifyhearts(ek: &EffectKindLocals) -> EffectKind {
    EffectKind::ModifyHearts {
        operation: ek.operation.clone(),
        value: ek.value.clone(),
        duration: ek.duration.clone(),
        heart_colors: ek.heart_colors.clone(),
        group_names: ek.group_names.clone(),
        per_unit: ek.per_unit.clone(),
        per_unit_count: ek.per_unit_count.clone(),
        per_unit_heart_colors: ek.per_unit_heart_colors.clone(),
        location: ek.location.clone(),
        timing_condition: ek.timing_condition.clone(),
        original_value: ek.original_value.clone(),
        original_count: ek.original_count.clone(),
        original_operator: ek.original_operator.clone(),
        exclude_self: ek.exclude_self.clone(),
        self_target: ek.self_target.clone(),
        exclude_heart_colors: ek.exclude_heart_colors.clone(),
        repeat_limit: ek.repeat_limit.clone(),
        card_type: ek.card_type.clone(),
        target_count: ek.target_count.clone(),
        filter_targets_by_heart_colors: ek.filter_targets_by_heart_colors.clone(),
        cost_total: ek.cost_total.clone(),
        cost_total_operator: ek.cost_total_operator.clone(),
        group_reference: ek.group_reference.clone(),
        negation: ek.negation.clone(),
        replace_all: ek.replace_all.clone(),
        position: ek.position.clone(),
        all: ek.all.clone(),
        per_unit_type: ek.per_unit_type.clone(),
        distinct: ek.distinct.clone(),
        same_name: ek.same_name.clone(),
        same_unit_name: ek.same_unit_name.clone(),
    }
}

fn build_modifyscore(ek: &EffectKindLocals) -> EffectKind {
    EffectKind::ModifyScore {
        source: ek.source.clone(),
        target: ek.target.clone(),
        destination: ek.destination.clone(),
        operation: ek.operation.clone(),
        value: ek.value.clone(),
        duration: ek.duration.clone(),
        card_type: ek.card_type.clone(),
        group_names: ek.group_names.clone(),
        per_unit: ek.per_unit.clone(),
        per_unit_count: ek.per_unit_count.clone(),
        per_unit_type: ek.per_unit_type.clone(),
        per_unit_location: ek.per_unit_location.clone(),
        per_unit_heart_colors: ek.per_unit_heart_colors.clone(),
        location: ek.location.clone(),
        effect_constraint: ek.effect_constraint.clone(),
        self_target: ek.self_target.clone(),
        heart_colors: ek.heart_colors.clone(),
        exclude_self: ek.exclude_self.clone(),
        target_count: ek.target_count.clone(),
        repeat_limit: ek.repeat_limit.clone(),
        filter_targets_by_heart_colors: ek.filter_targets_by_heart_colors.clone(),
        cost_total: ek.cost_total.clone(),
        cost_total_operator: ek.cost_total_operator.clone(),
        distinct: ek.distinct.clone(),
        position: ek.position.clone(),
        activation_position: ek.activation_position.clone(),
        card_names: ek.card_names.clone(),
        card_property: ek.card_property.clone(),
        state: ek.state.clone(),
        negation: ek.negation.clone(),
        max_repeats: ek.max_repeats.clone(),
        need_heart_operator: ek.need_heart_operator.clone(),
        need_heart_total: ek.need_heart_total.clone(),
        same_name: ek.same_name.clone(),
        same_unit_name: ek.same_unit_name.clone(),
    }
}

fn build_movecards(ek: &EffectKindLocals) -> EffectKind {
    EffectKind::MoveCards {
        source: ek.source.clone(),
        target: ek.target.clone(),
        destination: ek.destination.clone(),
        count: ek.count.clone(),
        card_type: ek.card_type.clone(),
        target_count: ek.target_count.clone(),
        characters: ek.characters.clone(),
        exclude_characters: ek.exclude_characters.clone(),
        group_names: ek.group_names.clone(),
        exclude_group_names: ek.exclude_group_names.clone(),
        cost_limit: ek.cost_limit.clone(),
        cost_limit_operator: ek.cost_limit_operator.clone(),
        cost_limit_min: ek.cost_limit_min.clone(),
        cost_limit_max: ek.cost_limit_max.clone(),
        card_names: ek.card_names.clone(),
        placement_order: ek.placement_order.clone(),
        shuffle: ek.shuffle.clone(),
        any_number: ek.any_number.clone(),
        discard_remaining: ek.discard_remaining.clone(),
        multiple_targets: ek.multiple_targets.clone(),
        exclude_self: ek.exclude_self.clone(),
        exclude_selected: ek.exclude_selected.clone(),
        exclude_by_name_source: ek.exclude_by_name_source.clone(),
        name_constraint: ek.name_constraint.clone(),
        name_constraint_source: ek.name_constraint_source.clone(),
        ability_filter: ek.ability_filter.clone(),
        ability_filter_triggers: ek.ability_filter_triggers.clone(),
        or_ability_filters: ek.or_ability_filters.clone(),
        card_property: ek.card_property.clone(),
        original_value: ek.original_value.clone(),
        source_position: ek.source_position.clone(),
        exclude_position: ek.exclude_position.clone(),
        allow_occupied_stage: ek.allow_occupied_stage.clone(),
        target_from_selection: ek.target_from_selection.clone(),
        group_reference: ek.group_reference.clone(),
        cost_from_revealed: ek.cost_from_revealed.clone(),
        self_target: ek.self_target.clone(),
        per_group: ek.per_group.clone(),
        per_group_count: ek.per_group_count.clone(),
        state: ek.state.clone(),
        negation: ek.negation.clone(),
        location: ek.location.clone(),
        activation_position: ek.activation_position.clone(),
        exclude_heart_colors: ek.exclude_heart_colors.clone(),
        filter_targets_by_heart_colors: ek.filter_targets_by_heart_colors.clone(),
        cost_total: ek.cost_total.clone(),
        cost_total_operator: ek.cost_total_operator.clone(),
        need_heart_total: ek.need_heart_total.clone(),
        need_heart_operator: ek.need_heart_operator.clone(),
        need_heart_color: ek.need_heart_color.clone(),
        distinct: ek.distinct.clone(),
        state_change: ek.state_change.clone(),
        self_cost: ek.self_cost.clone(),
        dynamic_count: ek.dynamic_count.clone(),
        or_card_types: ek.or_card_types.clone(),
        position: ek.position.clone(),
        cost_reference: ek.cost_reference.clone(),
        cost_offset: ek.cost_offset.clone(),
        all: ek.all.clone(),
        energy_count: ek.energy_count.clone(),
        heart_colors: ek.heart_colors.clone(),
        baton_touch_trigger: ek.baton_touch_trigger.clone(),
        target_member: ek.target_member.clone(),
        same_unit_name: ek.same_unit_name.clone(),
        action_by: ek.action_by.clone(),
        activation_condition_parsed: ek.activation_condition_parsed.clone(),
        quoted_text: ek.quoted_text.clone(),
        same_name: ek.same_name.clone(),
    }
}

fn build_positionop(ek: &EffectKindLocals) -> EffectKind {
    EffectKind::PositionOp {
        source: ek.source.clone(),
        target: ek.target.clone(),
        destination: ek.destination.clone(),
        position: ek.position.clone(),
        target_member: ek.target_member.clone(),
        source_position: ek.source_position.clone(),
        exclude_position: ek.exclude_position.clone(),
        allow_occupied_stage: ek.allow_occupied_stage.clone(),
        optional: ek.optional.clone(),
        card_type: ek.card_type.clone(),
        group_names: ek.group_names.clone(),
        exclude_group_names: ek.exclude_group_names.clone(),
        characters: ek.characters.clone(),
        exclude_characters: ek.exclude_characters.clone(),
        cost_limit: ek.cost_limit.clone(),
        cost_limit_operator: ek.cost_limit_operator.clone(),
        energy_count: ek.energy_count.clone(),
        dynamic_count: ek.dynamic_count.clone(),
        any_number: ek.any_number.clone(),
        cost_from_revealed: ek.cost_from_revealed.clone(),
        exclude_self: ek.exclude_self.clone(),
        multiple_targets: ek.multiple_targets.clone(),
        self_target: ek.self_target.clone(),
        state: ek.state.clone(),
        activation_position: ek.activation_position.clone(),
        group_reference: ek.group_reference.clone(),
        same_name: ek.same_name.clone(),
        same_unit_name: ek.same_unit_name.clone(),
    }
}

fn build_restrictionop(ek: &EffectKindLocals) -> EffectKind {
    EffectKind::RestrictionOp {
        restriction_type: ek.restriction_type.clone(),
        restricted_destination: ek.restricted_destination.clone(),
        delayed: ek.delayed.clone(),
        timing: ek.timing.clone(),
        treat_as: ek.treat_as.clone(),
        timing_condition: ek.timing_condition.clone(),
        phase: ek.phase.clone(),
        non_stackable: ek.non_stackable.clone(),
        operation: ek.operation.clone(),
        card_type: ek.card_type.clone(),
        location: ek.location.clone(),
        effect_type: ek.effect_type.clone(),
        replaces_event: ek.replaces_event.clone(),
        choice_based: ek.choice_based.clone(),
        trigger_type: ek.trigger_type.clone(),
        trigger_filter: ek.trigger_filter.clone(),
        duration: ek.duration.clone(),
        self_target: ek.self_target.clone(),
        exclude_self: ek.exclude_self.clone(),
        group_names: ek.group_names.clone(),
        exclude_group_names: ek.exclude_group_names.clone(),
        characters: ek.characters.clone(),
        exclude_characters: ek.exclude_characters.clone(),
        same_name: ek.same_name.clone(),
        same_unit_name: ek.same_unit_name.clone(),
    }
}

fn build_selecttarget(ek: &EffectKindLocals) -> EffectKind {
    EffectKind::SelectTarget {
        source: ek.source.clone(),
        target: ek.target.clone(),
        destination: ek.destination.clone(),
        target_count: ek.target_count.clone(),
        card_type: ek.card_type.clone(),
        characters: ek.characters.clone(),
        exclude_characters: ek.exclude_characters.clone(),
        group_names: ek.group_names.clone(),
        exclude_group_names: ek.exclude_group_names.clone(),
        cost_limit: ek.cost_limit.clone(),
        cost_limit_operator: ek.cost_limit_operator.clone(),
        cost_limit_min: ek.cost_limit_min.clone(),
        cost_limit_max: ek.cost_limit_max.clone(),
        card_names: ek.card_names.clone(),
        exclude_self: ek.exclude_self.clone(),
        exclude_selected: ek.exclude_selected.clone(),
        placement_order: ek.placement_order.clone(),
        distinct: ek.distinct.clone(),
        name_constraint: ek.name_constraint.clone(),
        name_constraint_source: ek.name_constraint_source.clone(),
        ability_filter: ek.ability_filter.clone(),
        ability_filter_triggers: ek.ability_filter_triggers.clone(),
        or_ability_filters: ek.or_ability_filters.clone(),
        card_property: ek.card_property.clone(),
        original_value: ek.original_value.clone(),
        negation: ek.negation.clone(),
        self_target: ek.self_target.clone(),
        per_unit: ek.per_unit.clone(),
        per_unit_count: ek.per_unit_count.clone(),
        per_unit_type: ek.per_unit_type.clone(),
        per_unit_heart_colors: ek.per_unit_heart_colors.clone(),
        per_unit_location: ek.per_unit_location.clone(),
        optional: ek.optional.clone(),
        location: ek.location.clone(),
        state: ek.state.clone(),
        activation_position: ek.activation_position.clone(),
        group_reference: ek.group_reference.clone(),
        multiple_targets: ek.multiple_targets.clone(),
        question: ek.question.clone(),
        answers: ek.answers.clone(),
        choice_maker: ek.choice_maker.clone(),
        choice_type: ek.choice_type.clone(),
        choice_options: ek.choice_options.clone(),
        filter_targets_by_heart_colors: ek.filter_targets_by_heart_colors.clone(),
        heart_colors: ek.heart_colors.clone(),
        cost_total: ek.cost_total.clone(),
        cost_total_operator: ek.cost_total_operator.clone(),
        or_card_types: ek.or_card_types.clone(),
        action_by: ek.action_by.clone(),
        require_all_heart_colors: ek.require_all_heart_colors.clone(),
        heart_color_count: ek.heart_color_count.clone(),
        options: ek.options.clone(),
        per_group: ek.per_group.clone(),
        per_group_count: ek.per_group_count.clone(),
        reveal: ek.reveal.clone(),
        any_number: ek.any_number.clone(),
        discard_remaining: ek.discard_remaining.clone(),
        same_name: ek.same_name.clone(),
        same_unit_name: ek.same_unit_name.clone(),
    }
}
