// Auto-generated by compile_abilities.py — DO NOT EDIT

fn default_condition_abilityFilter() -> Condition {
    Condition::AbilityFilter {
        text: Default::default(),
        negation: Default::default(),
        phase: Default::default(),
        phase_target: Default::default(),
        cache: Default::default(),
        trigger_event: Default::default(),
        ability_filter: Default::default(),
        ability_filter_triggers: Default::default(),
        target: Default::default(),
        location: Default::default(),
        operator: Default::default(),
        count: Default::default(),
    }
}

fn default_condition_allRevealedMatchHeartColor() -> Condition {
    Condition::AllRevealedMatchHeartColor {
        text: Default::default(),
        negation: Default::default(),
        phase: Default::default(),
        phase_target: Default::default(),
        cache: Default::default(),
        trigger_event: Default::default(),
        count: Default::default(),
        operator: Default::default(),
    }
}

fn default_condition_alwaysTrue() -> Condition {
    Condition::AlwaysTrue {
        text: Default::default(),
        negation: Default::default(),
        phase: Default::default(),
        phase_target: Default::default(),
        cache: Default::default(),
        trigger_event: Default::default(),
    }
}

fn default_condition_anyOf() -> Condition {
    Condition::AnyOf {
        text: Default::default(),
        negation: Default::default(),
        phase: Default::default(),
        phase_target: Default::default(),
        cache: Default::default(),
        trigger_event: Default::default(),
        any_of: Default::default(),
    }
}

fn default_condition_appearance() -> Condition {
    Condition::Appearance {
        text: Default::default(),
        negation: Default::default(),
        phase: Default::default(),
        phase_target: Default::default(),
        cache: Default::default(),
        trigger_event: Default::default(),
        appearance: Default::default(),
        baton_touch_trigger: Default::default(),
        location: Default::default(),
        target: Default::default(),
        group_names: Default::default(),
        cost_limit: Default::default(),
        card_type: Default::default(),
        characters: Default::default(),
        positions_characters: Default::default(),
        min_baton_touch_count: Default::default(),
        activation_position: Default::default(),
        exclude_self: Default::default(),
        position_compare: Default::default(),
        position: Default::default(),
        card_property: Default::default(),
        all_areas: Default::default(),
        cost_reference_character: Default::default(),
        cost_reference_operator: Default::default(),
        appearance_source: Default::default(),
        operator: Default::default(),
    }
}

fn default_condition_choice() -> Condition {
    Condition::Choice {
        text: Default::default(),
        negation: Default::default(),
        phase: Default::default(),
        phase_target: Default::default(),
        cache: Default::default(),
        trigger_event: Default::default(),
        options: Default::default(),
    }
}

fn default_condition_comparison() -> Condition {
    Condition::Comparison {
        text: Default::default(),
        negation: Default::default(),
        phase: Default::default(),
        phase_target: Default::default(),
        cache: Default::default(),
        trigger_event: Default::default(),
        comparison_type: Default::default(),
        comparison_target: Default::default(),
        target: Default::default(),
        location: Default::default(),
        operator: Default::default(),
        count: Default::default(),
        values: Default::default(),
        card_type: Default::default(),
        group_names: Default::default(),
        position: Default::default(),
        position_compare: Default::default(),
        aggregate: Default::default(),
        heart_colors: Default::default(),
        scope: Default::default(),
        cost_total: Default::default(),
        cost_total_operator: Default::default(),
        resource_type: Default::default(),
        delta: Default::default(),
        cost_limit: Default::default(),
        source: Default::default(),
        comparison_source: Default::default(),
        locations: Default::default(),
        exclude_group_names: Default::default(),
        characters: Default::default(),
        exclude_characters: Default::default(),
        same_name: Default::default(),
        distinct: Default::default(),
        all: Default::default(),
        all_areas: Default::default(),
        exclude_self: Default::default(),
        self_target: Default::default(),
        destination: Default::default(),
        state: Default::default(),
        require_position_cards: Default::default(),
        temporal: Default::default(),
        yell_trigger: Default::default(),
        no_excess_heart: Default::default(),
        card_property: Default::default(),
        ability_filter: Default::default(),
        ability_filter_triggers: Default::default(),
        baton_touch_trigger: Default::default(),
        min_baton_touch_count: Default::default(),
        from_state: Default::default(),
        to_state: Default::default(),
    }
}

fn default_condition_complex() -> Condition {
    Condition::Complex {
        text: Default::default(),
        negation: Default::default(),
        phase: Default::default(),
        phase_target: Default::default(),
        cache: Default::default(),
        trigger_event: Default::default(),
        cause: Default::default(),
        effect: Default::default(),
    }
}

fn default_condition_compound() -> Condition {
    Condition::Compound {
        text: Default::default(),
        negation: Default::default(),
        phase: Default::default(),
        phase_target: Default::default(),
        cache: Default::default(),
        trigger_event: Default::default(),
        operator: Default::default(),
        target: Default::default(),
        conditions: Default::default(),
    }
}

fn default_condition_group() -> Condition {
    Condition::Group {
        text: Default::default(),
        negation: Default::default(),
        phase: Default::default(),
        phase_target: Default::default(),
        cache: Default::default(),
        trigger_event: Default::default(),
        group_names: Default::default(),
        all_members: Default::default(),
        location: Default::default(),
        target: Default::default(),
        heart_colors: Default::default(),
        card_type: Default::default(),
        operator: Default::default(),
        count: Default::default(),
        aggregate: Default::default(),
        exclude_characters: Default::default(),
        temporal: Default::default(),
        self_target: Default::default(),
        exclude_self: Default::default(),
        heart_source: Default::default(),
        source: Default::default(),
        locations: Default::default(),
        position: Default::default(),
    }
}

fn default_condition_location() -> Condition {
    Condition::Location {
        text: Default::default(),
        negation: Default::default(),
        phase: Default::default(),
        phase_target: Default::default(),
        cache: Default::default(),
        trigger_event: Default::default(),
        location: Default::default(),
        locations: Default::default(),
        target: Default::default(),
        count: Default::default(),
        operator: Default::default(),
        card_type: Default::default(),
        unit: Default::default(),
        comparison_target: Default::default(),
        comparison_type: Default::default(),
        aggregate: Default::default(),
        group_names: Default::default(),
        group_reference: Default::default(),
        exclude_group_names: Default::default(),
        characters: Default::default(),
        exclude_characters: Default::default(),
        cost_limit: Default::default(),
        cost_limit_operator: Default::default(),
        heart_colors: Default::default(),
        heart_type: Default::default(),
        heart_source: Default::default(),
        distinct: Default::default(),
        exclude_self: Default::default(),
        self_target: Default::default(),
        source: Default::default(),
        activation_position: Default::default(),
        destination: Default::default(),
        state: Default::default(),
        position: Default::default(),
        position_compare: Default::default(),
        require_position_cards: Default::default(),
        all: Default::default(),
        all_areas: Default::default(),
        temporal: Default::default(),
        yell_trigger: Default::default(),
        same_name: Default::default(),
        card_property: Default::default(),
        scope: Default::default(),
        sub_checks: Default::default(),
        baton_touch_trigger: Default::default(),
        min_baton_touch_count: Default::default(),
    }
}

fn default_condition_movement() -> Condition {
    Condition::Movement {
        text: Default::default(),
        negation: Default::default(),
        phase: Default::default(),
        phase_target: Default::default(),
        cache: Default::default(),
        trigger_event: Default::default(),
        movement: Default::default(),
        location: Default::default(),
        target: Default::default(),
        cost_limit: Default::default(),
        cost_limit_operator: Default::default(),
        baton_touch_trigger: Default::default(),
        min_baton_touch_count: Default::default(),
        exclude_self: Default::default(),
        group_names: Default::default(),
        card_type: Default::default(),
        characters: Default::default(),
        baton_touch_source: Default::default(),
        card_property: Default::default(),
        comparison_type: Default::default(),
        operator: Default::default(),
        self_effect_only: Default::default(),
        energy_placed: Default::default(),
        area_direction: Default::default(),
        position: Default::default(),
        self_target: Default::default(),
        ability_filter: Default::default(),
        source: Default::default(),
        destination: Default::default(),
        from_state: Default::default(),
        to_state: Default::default(),
    }
}

fn default_condition_noExcessHeart() -> Condition {
    Condition::NoExcessHeart {
        text: Default::default(),
        negation: Default::default(),
        phase: Default::default(),
        phase_target: Default::default(),
        cache: Default::default(),
        trigger_event: Default::default(),
        target: Default::default(),
    }
}

fn default_condition_opponentChoice() -> Condition {
    Condition::OpponentChoice {
        text: Default::default(),
        negation: Default::default(),
        phase: Default::default(),
        phase_target: Default::default(),
        cache: Default::default(),
        trigger_event: Default::default(),
        target: Default::default(),
    }
}

fn default_condition_opponentLiveSuccess() -> Condition {
    Condition::OpponentLiveSuccess {
        text: Default::default(),
        negation: Default::default(),
        phase: Default::default(),
        phase_target: Default::default(),
        cache: Default::default(),
        trigger_event: Default::default(),
        no_excess_heart: Default::default(),
    }
}

fn default_condition_positionCond() -> Condition {
    Condition::PositionCond {
        text: Default::default(),
        negation: Default::default(),
        phase: Default::default(),
        phase_target: Default::default(),
        cache: Default::default(),
        trigger_event: Default::default(),
        target: Default::default(),
        position: Default::default(),
    }
}

fn default_condition_resource() -> Condition {
    Condition::Resource {
        text: Default::default(),
        negation: Default::default(),
        phase: Default::default(),
        phase_target: Default::default(),
        cache: Default::default(),
        trigger_event: Default::default(),
        resource_type: Default::default(),
        target: Default::default(),
        location: Default::default(),
        operator: Default::default(),
        count: Default::default(),
        delta: Default::default(),
        heart_colors: Default::default(),
        position: Default::default(),
        source: Default::default(),
    }
}

fn default_condition_scoreThreshold() -> Condition {
    Condition::ScoreThreshold {
        text: Default::default(),
        negation: Default::default(),
        phase: Default::default(),
        phase_target: Default::default(),
        cache: Default::default(),
        trigger_event: Default::default(),
        count: Default::default(),
        operator: Default::default(),
        target: Default::default(),
    }
}

fn default_condition_state() -> Condition {
    Condition::State {
        text: Default::default(),
        negation: Default::default(),
        phase: Default::default(),
        phase_target: Default::default(),
        cache: Default::default(),
        trigger_event: Default::default(),
        state: Default::default(),
        energy_state: Default::default(),
        target: Default::default(),
        resource_type: Default::default(),
        all: Default::default(),
        group_names: Default::default(),
        card_type: Default::default(),
        characters: Default::default(),
        cost_limit: Default::default(),
        cost_limit_operator: Default::default(),
        from_state: Default::default(),
        to_state: Default::default(),
        count: Default::default(),
        operator: Default::default(),
    }
}

fn default_condition_temporal() -> Condition {
    Condition::Temporal {
        text: Default::default(),
        negation: Default::default(),
        phase: Default::default(),
        phase_target: Default::default(),
        cache: Default::default(),
        trigger_event: Default::default(),
        temporal: Default::default(),
        turn_number: Default::default(),
        count: Default::default(),
        location: Default::default(),
        card_type: Default::default(),
        target: Default::default(),
        group_names: Default::default(),
        temporal_scope: Default::default(),
        position: Default::default(),
        locations: Default::default(),
        heart_colors: Default::default(),
        aggregate: Default::default(),
        self_target: Default::default(),
        condition: Default::default(),
    }
}

fn default_abilityOp() -> EffectKind {
    EffectKind::AbilityOp {
        source: Default::default(),
        target: Default::default(),
        destination: Default::default(),
        ability_gain: Default::default(),
        ability_gain_trigger: Default::default(),
        gained_effect: Default::default(),
        ability_text: Default::default(),
        target_trigger: Default::default(),
        source_card: Default::default(),
        suppressed_trigger: Default::default(),
        card_type: Default::default(),
        group_names: Default::default(),
        exclude_group_names: Default::default(),
        characters: Default::default(),
        exclude_characters: Default::default(),
        cost_limit: Default::default(),
        cost_limit_operator: Default::default(),
        location: Default::default(),
        trigger_filter: Default::default(),
        trigger_type: Default::default(),
        duration: Default::default(),
        self_target: Default::default(),
        exclude_self: Default::default(),
        effect_type: Default::default(),
        use_limit: Default::default(),
        triggers: Default::default(),
        activation_condition_parsed: Default::default(),
        option: Default::default(),
        all: Default::default(),
        activation_position: Default::default(),
        heart_colors: Default::default(),
        dynamic_count: Default::default(),
    }
}

fn default_changeState() -> EffectKind {
    EffectKind::ChangeState {
        source: Default::default(),
        target: Default::default(),
        destination: Default::default(),
        state_change: Default::default(),
        card_type: Default::default(),
        cost_limit: Default::default(),
        cost_limit_operator: Default::default(),
        cost_from_revealed: Default::default(),
        optional: Default::default(),
        self_cost: Default::default(),
        characters: Default::default(),
        exclude_characters: Default::default(),
        group_names: Default::default(),
        exclude_group_names: Default::default(),
        blade_limit: Default::default(),
        blade_limit_operator: Default::default(),
        per_unit: Default::default(),
        per_unit_count: Default::default(),
        per_unit_type: Default::default(),
        per_unit_heart_colors: Default::default(),
        per_unit_location: Default::default(),
        location: Default::default(),
        distinct: Default::default(),
        exclude_self: Default::default(),
        self_target: Default::default(),
        identities: Default::default(),
        all_regions: Default::default(),
        card_names: Default::default(),
        negation: Default::default(),
        cost_total: Default::default(),
        cost_total_operator: Default::default(),
        card_property: Default::default(),
        original_value: Default::default(),
        name_constraint: Default::default(),
        name_constraint_source: Default::default(),
        filter_targets_by_heart_colors: Default::default(),
        group_reference: Default::default(),
        activation_position: Default::default(),
        ability_filter: Default::default(),
        ability_filter_triggers: Default::default(),
        or_ability_filters: Default::default(),
        exclude_heart_colors: Default::default(),
        heart_colors: Default::default(),
        all: Default::default(),
        position: Default::default(),
        state: Default::default(),
        action_by: Default::default(),
        activation_condition_parsed: Default::default(),
    }
}

fn default_customOp() -> EffectKind {
    EffectKind::CustomOp {
        action_by: Default::default(),
        opponent_action: Default::default(),
        effect_type: Default::default(),
        replaces_event: Default::default(),
        choice_based: Default::default(),
        card_type: Default::default(),
        group_names: Default::default(),
        exclude_group_names: Default::default(),
        characters: Default::default(),
        exclude_characters: Default::default(),
        identities: Default::default(),
        all_regions: Default::default(),
        question: Default::default(),
        answers: Default::default(),
        choice_maker: Default::default(),
        options: Default::default(),
        location: Default::default(),
        duration: Default::default(),
        self_target: Default::default(),
        exclude_self: Default::default(),
        original_value: Default::default(),
        timing: Default::default(),
        treat_as: Default::default(),
        trigger_type: Default::default(),
        trigger_filter: Default::default(),
        activation_condition_parsed: Default::default(),
        use_limit: Default::default(),
        triggers: Default::default(),
    }
}

fn default_drawCards() -> EffectKind {
    EffectKind::DrawCards {
        source: Default::default(),
        target: Default::default(),
        destination: Default::default(),
        target_count: Default::default(),
        card_type: Default::default(),
        dynamic_count: Default::default(),
        card_names: Default::default(),
        location: Default::default(),
        exclude_self: Default::default(),
        per_unit: Default::default(),
        per_unit_count: Default::default(),
        per_unit_type: Default::default(),
        per_unit_heart_colors: Default::default(),
        per_unit_location: Default::default(),
        position: Default::default(),
        state: Default::default(),
        heart_colors: Default::default(),
        trigger_type: Default::default(),
        original_value: Default::default(),
        action_by: Default::default(),
    }
}

fn default_gainResource() -> EffectKind {
    EffectKind::GainResource {
        resource: Default::default(),
        heart_colors: Default::default(),
        heart_colors_from_selected_card: Default::default(),
        sign: Default::default(),
        operation: Default::default(),
        value: Default::default(),
        energy_count: Default::default(),
        dynamic_count: Default::default(),
        optional: Default::default(),
        duration: Default::default(),
        position: Default::default(),
        any_number: Default::default(),
        per_unit: Default::default(),
        per_unit_count: Default::default(),
        per_unit_type: Default::default(),
        per_unit_heart_colors: Default::default(),
        per_unit_location: Default::default(),
        location: Default::default(),
        group_names: Default::default(),
        card_type: Default::default(),
        cost_limit: Default::default(),
        cost_limit_operator: Default::default(),
        characters: Default::default(),
        exclude_characters: Default::default(),
        exclude_group_names: Default::default(),
        self_target: Default::default(),
        target_from_selection: Default::default(),
        card_property: Default::default(),
        original_value: Default::default(),
        negation: Default::default(),
        filter_targets_by_heart_colors: Default::default(),
        activation_position: Default::default(),
        state: Default::default(),
        heart_type: Default::default(),
        target_count: Default::default(),
        all: Default::default(),
        same_name: Default::default(),
        exclude_self: Default::default(),
        group_reference: Default::default(),
        trigger_type: Default::default(),
        distinct: Default::default(),
        heart_color: Default::default(),
        action_by: Default::default(),
        activation_condition_parsed: Default::default(),
        multiple_targets: Default::default(),
        repeat_limit: Default::default(),
        timing_condition: Default::default(),
        require_all_heart_colors: Default::default(),
        heart_color_count: Default::default(),
    }
}

fn default_miscOp() -> EffectKind {
    EffectKind::MiscOp {
        source: Default::default(),
        target: Default::default(),
        destination: Default::default(),
        operation: Default::default(),
        value: Default::default(),
        card_type: Default::default(),
        group_names: Default::default(),
        exclude_group_names: Default::default(),
        characters: Default::default(),
        exclude_characters: Default::default(),
        cost_limit: Default::default(),
        cost_limit_operator: Default::default(),
        location: Default::default(),
        duration: Default::default(),
        heart_colors: Default::default(),
        heart_type: Default::default(),
        heart_selection: Default::default(),
        blade_type: Default::default(),
        self_target: Default::default(),
        exclude_self: Default::default(),
        choice: Default::default(),
        lose_blade_hearts: Default::default(),
        dynamic_count: Default::default(),
        per_unit: Default::default(),
        per_unit_count: Default::default(),
        per_unit_type: Default::default(),
        per_unit_heart_colors: Default::default(),
        per_unit_location: Default::default(),
        repeat_limit: Default::default(),
        identities: Default::default(),
        all_regions: Default::default(),
        timing: Default::default(),
        treat_as: Default::default(),
        effect_constraint: Default::default(),
        original_value: Default::default(),
        original_count: Default::default(),
        original_operator: Default::default(),
        original_cost: Default::default(),
        blade_limit: Default::default(),
        blade_limit_operator: Default::default(),
        negation: Default::default(),
        activation_position: Default::default(),
        target_count: Default::default(),
        group_reference: Default::default(),
        parenthetical: Default::default(),
        quoted_text: Default::default(),
        same_unit_name: Default::default(),
        alternative_count_type: Default::default(),
        per_group: Default::default(),
        per_group_count: Default::default(),
        resource_icon_count: Default::default(),
        cost_total: Default::default(),
        cost_total_operator: Default::default(),
        cost_reference: Default::default(),
        cost_offset: Default::default(),
        blind: Default::default(),
        picker: Default::default(),
        all: Default::default(),
        sign: Default::default(),
        heart_color_count: Default::default(),
        require_all_heart_colors: Default::default(),
        energy_count: Default::default(),
        placement_order: Default::default(),
        ref_value: Default::default(),
        ref_offset: Default::default(),
        id: Default::default(),
        card_names: Default::default(),
        character_effects: Default::default(),
        or_card_types: Default::default(),
        options: Default::default(),
        position: Default::default(),
        ability_filter: Default::default(),
    }
}

fn default_modifyHearts() -> EffectKind {
    EffectKind::ModifyHearts {
        operation: Default::default(),
        value: Default::default(),
        duration: Default::default(),
        heart_colors: Default::default(),
        group_names: Default::default(),
        per_unit: Default::default(),
        per_unit_count: Default::default(),
        per_unit_heart_colors: Default::default(),
        location: Default::default(),
        timing_condition: Default::default(),
        original_value: Default::default(),
        original_count: Default::default(),
        original_operator: Default::default(),
        exclude_self: Default::default(),
        self_target: Default::default(),
        exclude_heart_colors: Default::default(),
        repeat_limit: Default::default(),
        card_type: Default::default(),
        target_count: Default::default(),
        filter_targets_by_heart_colors: Default::default(),
        cost_total: Default::default(),
        cost_total_operator: Default::default(),
        group_reference: Default::default(),
        negation: Default::default(),
        replace_all: Default::default(),
        position: Default::default(),
        all: Default::default(),
        per_unit_type: Default::default(),
        distinct: Default::default(),
    }
}

fn default_modifyScore() -> EffectKind {
    EffectKind::ModifyScore {
        source: Default::default(),
        target: Default::default(),
        destination: Default::default(),
        operation: Default::default(),
        value: Default::default(),
        duration: Default::default(),
        card_type: Default::default(),
        group_names: Default::default(),
        per_unit: Default::default(),
        per_unit_count: Default::default(),
        per_unit_type: Default::default(),
        per_unit_location: Default::default(),
        per_unit_heart_colors: Default::default(),
        location: Default::default(),
        effect_constraint: Default::default(),
        self_target: Default::default(),
        heart_colors: Default::default(),
        exclude_self: Default::default(),
        target_count: Default::default(),
        repeat_limit: Default::default(),
        filter_targets_by_heart_colors: Default::default(),
        cost_total: Default::default(),
        cost_total_operator: Default::default(),
        distinct: Default::default(),
        position: Default::default(),
        activation_position: Default::default(),
        card_names: Default::default(),
        card_property: Default::default(),
        state: Default::default(),
        negation: Default::default(),
        max_repeats: Default::default(),
        need_heart_operator: Default::default(),
        need_heart_total: Default::default(),
    }
}

fn default_moveCards() -> EffectKind {
    EffectKind::MoveCards {
        source: Default::default(),
        target: Default::default(),
        destination: Default::default(),
        count: Default::default(),
        card_type: Default::default(),
        target_count: Default::default(),
        characters: Default::default(),
        exclude_characters: Default::default(),
        group_names: Default::default(),
        exclude_group_names: Default::default(),
        cost_limit: Default::default(),
        cost_limit_operator: Default::default(),
        cost_limit_min: Default::default(),
        cost_limit_max: Default::default(),
        card_names: Default::default(),
        placement_order: Default::default(),
        shuffle: Default::default(),
        any_number: Default::default(),
        discard_remaining: Default::default(),
        multiple_targets: Default::default(),
        exclude_self: Default::default(),
        exclude_selected: Default::default(),
        exclude_by_name_source: Default::default(),
        name_constraint: Default::default(),
        name_constraint_source: Default::default(),
        ability_filter: Default::default(),
        ability_filter_triggers: Default::default(),
        or_ability_filters: Default::default(),
        card_property: Default::default(),
        original_value: Default::default(),
        source_position: Default::default(),
        exclude_position: Default::default(),
        allow_occupied_stage: Default::default(),
        target_from_selection: Default::default(),
        group_reference: Default::default(),
        cost_from_revealed: Default::default(),
        self_target: Default::default(),
        per_group: Default::default(),
        per_group_count: Default::default(),
        state: Default::default(),
        negation: Default::default(),
        location: Default::default(),
        activation_position: Default::default(),
        exclude_heart_colors: Default::default(),
        filter_targets_by_heart_colors: Default::default(),
        cost_total: Default::default(),
        cost_total_operator: Default::default(),
        need_heart_total: Default::default(),
        need_heart_operator: Default::default(),
        need_heart_color: Default::default(),
        distinct: Default::default(),
        state_change: Default::default(),
        self_cost: Default::default(),
        dynamic_count: Default::default(),
        or_card_types: Default::default(),
        position: Default::default(),
        cost_reference: Default::default(),
        cost_offset: Default::default(),
        all: Default::default(),
        energy_count: Default::default(),
        heart_colors: Default::default(),
        baton_touch_trigger: Default::default(),
        target_member: Default::default(),
        same_unit_name: Default::default(),
        action_by: Default::default(),
        activation_condition_parsed: Default::default(),
        quoted_text: Default::default(),
    }
}

fn default_positionOp() -> EffectKind {
    EffectKind::PositionOp {
        source: Default::default(),
        target: Default::default(),
        destination: Default::default(),
        position: Default::default(),
        target_member: Default::default(),
        source_position: Default::default(),
        exclude_position: Default::default(),
        allow_occupied_stage: Default::default(),
        optional: Default::default(),
        card_type: Default::default(),
        group_names: Default::default(),
        exclude_group_names: Default::default(),
        characters: Default::default(),
        exclude_characters: Default::default(),
        cost_limit: Default::default(),
        cost_limit_operator: Default::default(),
        energy_count: Default::default(),
        dynamic_count: Default::default(),
        any_number: Default::default(),
        cost_from_revealed: Default::default(),
        exclude_self: Default::default(),
        multiple_targets: Default::default(),
        self_target: Default::default(),
        state: Default::default(),
        activation_position: Default::default(),
        group_reference: Default::default(),
    }
}

fn default_restrictionOp() -> EffectKind {
    EffectKind::RestrictionOp {
        restriction_type: Default::default(),
        restricted_destination: Default::default(),
        delayed: Default::default(),
        timing: Default::default(),
        treat_as: Default::default(),
        timing_condition: Default::default(),
        phase: Default::default(),
        non_stackable: Default::default(),
        operation: Default::default(),
        card_type: Default::default(),
        location: Default::default(),
        effect_type: Default::default(),
        replaces_event: Default::default(),
        choice_based: Default::default(),
        trigger_type: Default::default(),
        trigger_filter: Default::default(),
        duration: Default::default(),
        self_target: Default::default(),
        exclude_self: Default::default(),
        group_names: Default::default(),
        exclude_group_names: Default::default(),
        characters: Default::default(),
        exclude_characters: Default::default(),
    }
}

fn default_selectTarget() -> EffectKind {
    EffectKind::SelectTarget {
        source: Default::default(),
        target: Default::default(),
        destination: Default::default(),
        target_count: Default::default(),
        card_type: Default::default(),
        characters: Default::default(),
        exclude_characters: Default::default(),
        group_names: Default::default(),
        exclude_group_names: Default::default(),
        cost_limit: Default::default(),
        cost_limit_operator: Default::default(),
        cost_limit_min: Default::default(),
        cost_limit_max: Default::default(),
        card_names: Default::default(),
        exclude_self: Default::default(),
        exclude_selected: Default::default(),
        placement_order: Default::default(),
        distinct: Default::default(),
        name_constraint: Default::default(),
        name_constraint_source: Default::default(),
        ability_filter: Default::default(),
        ability_filter_triggers: Default::default(),
        or_ability_filters: Default::default(),
        card_property: Default::default(),
        original_value: Default::default(),
        negation: Default::default(),
        self_target: Default::default(),
        per_unit: Default::default(),
        per_unit_count: Default::default(),
        per_unit_type: Default::default(),
        per_unit_heart_colors: Default::default(),
        per_unit_location: Default::default(),
        optional: Default::default(),
        location: Default::default(),
        state: Default::default(),
        activation_position: Default::default(),
        group_reference: Default::default(),
        multiple_targets: Default::default(),
        question: Default::default(),
        answers: Default::default(),
        choice_maker: Default::default(),
        choice_type: Default::default(),
        choice_options: Default::default(),
        filter_targets_by_heart_colors: Default::default(),
        heart_colors: Default::default(),
        cost_total: Default::default(),
        cost_total_operator: Default::default(),
        or_card_types: Default::default(),
        action_by: Default::default(),
        require_all_heart_colors: Default::default(),
        heart_color_count: Default::default(),
        options: Default::default(),
        per_group: Default::default(),
        per_group_count: Default::default(),
        reveal: Default::default(),
        any_number: Default::default(),
        discard_remaining: Default::default(),
    }
}

fn decode_effect_kind(op: Opcode, cursor: &mut &[u8]) -> Option<Box<EffectKind>> {
    match op {
        Opcode::ActivateAbility => {
            let mut ek = default_abilityOp();
            Some(Box::new(ek))
        }
        Opcode::ChangeState => {
            let state_change = decode_state(read_u8(cursor));
            let target = decode_player(read_u8(cursor));
            let mut ek = default_changeState();
            if let EffectKind::ChangeState { state_change: ref mut _bc_state_change, target: ref mut _bc_target, .. } = &mut ek {
                *_bc_state_change = Some(state_change.into());
                *_bc_target = Some(target.into());
            }
            Some(Box::new(ek))
        }
        Opcode::ChooseTargetPlayer => {
            let target = decode_player(read_u8(cursor));
            let mut ek = default_selectTarget();
            if let EffectKind::SelectTarget { target: ref mut _bc_target, .. } = &mut ek {
                *_bc_target = Some(target.into());
            }
            Some(Box::new(ek))
        }
        Opcode::DrawCard => {
            let target_count = read_u8(cursor);
            let source = decode_zone(read_u8(cursor));
            let mut ek = default_drawCards();
            if let EffectKind::DrawCards { target_count: ref mut _bc_target_count, source: ref mut _bc_source, .. } = &mut ek {
                *_bc_target_count = Some(target_count as u32);
                *_bc_source = Some(source.into());
            }
            Some(Box::new(ek))
        }
        Opcode::DrawUntilCount => {
            let target_count = read_u8(cursor);
            let source = decode_zone(read_u8(cursor));
            let mut ek = default_drawCards();
            if let EffectKind::DrawCards { target_count: ref mut _bc_target_count, source: ref mut _bc_source, .. } = &mut ek {
                *_bc_target_count = Some(target_count as u32);
                *_bc_source = Some(source.into());
            }
            Some(Box::new(ek))
        }
        Opcode::GainAbility => {
            let _id = read_u16(cursor);
            let _dur = read_u8(cursor);
            let mut ek = default_abilityOp();
            Some(Box::new(ek))
        }
        Opcode::GainAbilityFromSource => {
            let _id = read_u16(cursor);
            let mut ek = default_abilityOp();
            Some(Box::new(ek))
        }
        Opcode::GainResource => {
            let _resource = decode_resource(read_u8(cursor));
            let count = read_u8(cursor);
            let _heart_color = decode_heart(read_u8(cursor));
            let _duration = decode_duration(read_u8(cursor));
            let _char = read_str(cursor);
            let mut ek = default_gainResource();
            if let EffectKind::GainResource { value: ref mut _bc_value, .. } = &mut ek {
                *_bc_value = Some(count as u32);
            }
            Some(Box::new(ek))
        }
        Opcode::InvalidateAbility => {
            let mut ek = default_abilityOp();
            Some(Box::new(ek))
        }
        Opcode::ModifyCost => {
            let _value = read_i8(cursor);
            let _target = decode_player(read_u8(cursor));
            let mut ek = default_customOp();
            Some(Box::new(ek))
        }
        Opcode::ModifyRequiredHearts => {
            let value = read_i8(cursor);
            let _target = decode_player(read_u8(cursor));
            let mut ek = default_modifyHearts();
            if let EffectKind::ModifyHearts { value: ref mut _bc_value, .. } = &mut ek {
                *_bc_value = Some(value as u32);
            }
            Some(Box::new(ek))
        }
        Opcode::ModifyRequiredHeartsGlobal => {
            let value = read_i8(cursor);
            let mut ek = default_modifyHearts();
            if let EffectKind::ModifyHearts { value: ref mut _bc_value, .. } = &mut ek {
                *_bc_value = Some(value as u32);
            }
            Some(Box::new(ek))
        }
        Opcode::ModifyScore => {
            let value = read_i8(cursor);
            let per_unit = read_u8(cursor) != 0;
            let target = decode_player(read_u8(cursor));
            let mut ek = default_modifyScore();
            if let EffectKind::ModifyScore { value: ref mut _bc_value, per_unit: ref mut _bc_per_unit, target: ref mut _bc_target, .. } = &mut ek {
                *_bc_value = Some(value as u32);
                *_bc_per_unit = Some(per_unit);
                *_bc_target = Some(target.into());
            }
            Some(Box::new(ek))
        }
        Opcode::ModifyYellCount => {
            let value = read_i8(cursor);
            let mut ek = default_modifyScore();
            if let EffectKind::ModifyScore { value: ref mut _bc_value, .. } = &mut ek {
                *_bc_value = Some(value as u32);
            }
            Some(Box::new(ek))
        }
        Opcode::MoveCards => {
            let count = read_u8(cursor);
            let source = decode_zone(read_u8(cursor));
            let destination = decode_zone(read_u8(cursor));
            let card_type = decode_card_type(read_u8(cursor));
            let target = decode_player(read_u8(cursor));
            let mut ek = default_moveCards();
            if let EffectKind::MoveCards { count: ref mut _bc_count, source: ref mut _bc_source, destination: ref mut _bc_destination, card_type: ref mut _bc_card_type, target: ref mut _bc_target, .. } = &mut ek {
                *_bc_count = Some(count as u32);
                *_bc_source = Some(source.into());
                *_bc_destination = Some(destination.into());
                *_bc_card_type = Some(card_type.into());
                *_bc_target = Some(target.into());
            }
            Some(Box::new(ek))
        }
        Opcode::PlaceEnergyUnderMember => {
            let count = read_u8(cursor);
            let mut ek = default_moveCards();
            if let EffectKind::MoveCards { count: ref mut _bc_count, .. } = &mut ek {
                *_bc_count = Some(count as u32);
            }
            Some(Box::new(ek))
        }
        Opcode::PlayBatonTouch => {
            let mut ek = default_moveCards();
            Some(Box::new(ek))
        }
        Opcode::PositionChange => {
            let target = decode_player(read_u8(cursor));
            let mut ek = default_positionOp();
            if let EffectKind::PositionOp { target: ref mut _bc_target, .. } = &mut ek {
                *_bc_target = Some(target.into());
            }
            Some(Box::new(ek))
        }
        Opcode::Restriction => {
            let mut ek = default_restrictionOp();
            Some(Box::new(ek))
        }
        Opcode::SetBladeCount => {
            let value = read_u8(cursor);
            let mut ek = default_miscOp();
            if let EffectKind::MiscOp { value: ref mut _bc_value, .. } = &mut ek {
                *_bc_value = Some(value as u32);
            }
            Some(Box::new(ek))
        }
        Opcode::SetBladeType => {
            let _placeholder = read_u8(cursor);
            let mut ek = default_customOp();
            Some(Box::new(ek))
        }
        Opcode::SetCardIdentity => {
            let _value = read_str(cursor);
            let mut ek = default_changeState();
            Some(Box::new(ek))
        }
        Opcode::SetHeartType => {
            let value = decode_heart(read_u8(cursor));
            let mut ek = default_miscOp();
            if let EffectKind::MiscOp { heart_type: ref mut _bc_heart_type, .. } = &mut ek {
                *_bc_heart_type = Some(value.into());
            }
            Some(Box::new(ek))
        }
        Opcode::SuppressAbilityTrigger => {
            let mut ek = default_abilityOp();
            Some(Box::new(ek))
        }
        _ => None,
    }
}

fn decode_simple_effect(op: Opcode, cursor: &mut &[u8]) -> &'static str {
    match op {
        Opcode::ActivateAbility => {
            "activate_ability"
        }
        Opcode::ChangeState => {
            let _state_change = decode_state(read_u8(cursor));
            let _target = decode_player(read_u8(cursor));
            "change_state"
        }
        Opcode::ChooseTargetPlayer => {
            let _target = decode_player(read_u8(cursor));
            "choose_target_player"
        }
        Opcode::DrawCard => {
            let _target_count = read_u8(cursor);
            let _source = decode_zone(read_u8(cursor));
            "draw_card"
        }
        Opcode::DrawUntilCount => {
            let _target_count = read_u8(cursor);
            let _source = decode_zone(read_u8(cursor));
            "draw_until_count"
        }
        Opcode::GainAbility => {
            let __id = read_u16(cursor);
            let __dur = read_u8(cursor);
            "gain_ability"
        }
        Opcode::GainAbilityFromSource => {
            let __id = read_u16(cursor);
            "gain_ability_from_source"
        }
        Opcode::GainResource => {
            let __resource = decode_resource(read_u8(cursor));
            let _count = read_u8(cursor);
            let __heart_color = decode_heart(read_u8(cursor));
            let __duration = decode_duration(read_u8(cursor));
            let __char = read_str(cursor);
            "gain_resource"
        }
        Opcode::InvalidateAbility => {
            "invalidate_ability"
        }
        Opcode::ModifyCost => {
            let __value = read_i8(cursor);
            let __target = decode_player(read_u8(cursor));
            "modify_cost"
        }
        Opcode::ModifyRequiredHearts => {
            let _value = read_i8(cursor);
            let __target = decode_player(read_u8(cursor));
            "modify_required_hearts"
        }
        Opcode::ModifyRequiredHeartsGlobal => {
            let _value = read_i8(cursor);
            "modify_required_hearts_global"
        }
        Opcode::ModifyScore => {
            let _value = read_i8(cursor);
            let _per_unit = read_u8(cursor) != 0;
            let _target = decode_player(read_u8(cursor));
            "modify_score"
        }
        Opcode::ModifyYellCount => {
            let _value = read_i8(cursor);
            "modify_yell_count"
        }
        Opcode::MoveCards => {
            let _count = read_u8(cursor);
            let _source = decode_zone(read_u8(cursor));
            let _destination = decode_zone(read_u8(cursor));
            let _card_type = decode_card_type(read_u8(cursor));
            let _target = decode_player(read_u8(cursor));
            "move_cards"
        }
        Opcode::PlaceEnergyUnderMember => {
            let _count = read_u8(cursor);
            "place_energy_under_member"
        }
        Opcode::PlayBatonTouch => {
            "play_baton_touch"
        }
        Opcode::PositionChange => {
            let _target = decode_player(read_u8(cursor));
            "position_change"
        }
        Opcode::Restriction => {
            "restriction"
        }
        Opcode::SetBladeCount => {
            let _value = read_u8(cursor);
            "set_blade_count"
        }
        Opcode::SetBladeType => {
            let __placeholder = read_u8(cursor);
            "set_blade_type"
        }
        Opcode::SetCardIdentity => {
            let __value = read_str(cursor);
            "set_card_identity"
        }
        Opcode::SetHeartType => {
            let _value = decode_heart(read_u8(cursor));
            "set_heart_type"
        }
        Opcode::SuppressAbilityTrigger => {
            "suppress_ability_trigger"
        }
        _ => "",
    }
}

fn decode_cond_card_type(v: u8) -> ConditionCardType {
    match v { 1 => ConditionCardType::MemberCard, 2 => ConditionCardType::LiveCard, 3 => ConditionCardType::EnergyCard, _ => ConditionCardType::MemberCard }
}

pub fn decode_condition(cursor: &mut &[u8]) -> Condition {
    if cursor.is_empty() { return default_condition_alwaysTrue(); }
    let op_val = cursor[0];
    match op_val {
        81 => {
            let _ = read_u8(cursor);
            let __ability_filter = read_str(cursor);
            let mut c = default_condition_abilityFilter();
            c
        }
        80 => {
            let _ = read_u8(cursor);
            let __operator = decode_operator(read_u8(cursor));
            let __count = read_u16(cursor);
            let mut c = default_condition_comparison();
            c
        }
        70 => {
            let _ = read_u8(cursor);
            let __location = decode_zone(read_u8(cursor));
            let __count = read_u8(cursor);
            let mut c = default_condition_appearance();
            c
        }
        79 => {
            let _ = read_u8(cursor);
            let __operator = decode_operator(read_u8(cursor));
            let __count = read_u8(cursor);
            let mut c = default_condition_resource();
            c
        }
        64 => {
            let _ = read_u8(cursor);
            let __location = decode_zone(read_u8(cursor));
            let __operator = decode_operator(read_u8(cursor));
            let __count = read_u8(cursor);
            let _card_type_raw = read_u8(cursor);
            let __group_names = read_str(cursor);
            let __target = decode_player(read_u8(cursor));
            let mut c = default_condition_location();
            c
        }
        66 => {
            let _ = read_u8(cursor);
            let location = decode_zone(read_u8(cursor));
            let __comp_type = read_u8(cursor);
            let __agg = read_u8(cursor);
            let operator = decode_operator(read_u8(cursor));
            let count = read_u16(cursor);
            let target = decode_player(read_u8(cursor));
            let resource_type = decode_resource(read_u8(cursor));
            let card_type_raw = read_u8(cursor);
            let __group_names = read_str(cursor);
            let mut c = default_condition_comparison();
            if let Condition::Comparison { location: ref mut _bc_location, operator: ref mut _bc_operator, count: ref mut _bc_count, target: ref mut _bc_target, resource_type: ref mut _bc_resource_type, card_type: ref mut _bc_card_type, .. } = &mut c {
                *_bc_location = Some(location.into());
                *_bc_operator = Some(operator.into());
                *_bc_count = Some(count as u32);
                *_bc_target = Some(target.into());
                *_bc_resource_type = Some(resource_type.into());
                *_bc_card_type = Some(decode_cond_card_type(card_type_raw));
            }
            c
        }
        72 => {
            let _ = read_u8(cursor);
            let __operator = decode_operator(read_u8(cursor));
            let __count = read_u8(cursor);
            let mut c = default_condition_state();
            c
        }
        67 => {
            let _ = read_u8(cursor);
            let __group_names = read_str(cursor);
            let __count = read_u8(cursor);
            let __operator = decode_operator(read_u8(cursor));
            let mut c = default_condition_group();
            c
        }
        82 => {
            let _ = read_u8(cursor);
            let __position = decode_zone(read_u8(cursor));
            let __group_names = read_str(cursor);
            let mut c = default_condition_movement();
            c
        }
        77 => {
            let _ = read_u8(cursor);
            let mut c = default_condition_scoreThreshold();
            c
        }
        65 => {
            let _ = read_u8(cursor);
            let __location = decode_zone(read_u8(cursor));
            let __ct_str = decode_card_type(read_u8(cursor));
            let __exclude_self = read_u8(cursor) != 0;
            let __target = decode_player(read_u8(cursor));
            let mut c = default_condition_location();
            c
        }
        68 => {
            let _ = read_u8(cursor);
            let __location = decode_zone(read_u8(cursor));
            let __ct_str = decode_card_type(read_u8(cursor));
            let __count = read_u8(cursor);
            let __operator = decode_operator(read_u8(cursor));
            let mut c = default_condition_movement();
            c
        }
        85 => {
            let _ = read_u8(cursor);
            let mut c = default_condition_noExcessHeart();
            c
        }
        83 => {
            let _ = read_u8(cursor);
            let mut c = default_condition_movement();
            c
        }
        84 => {
            let _ = read_u8(cursor);
            let __no_excess_heart = read_u8(cursor) != 0;
            let mut c = default_condition_opponentLiveSuccess();
            c
        }
        73 => {
            let _ = read_u8(cursor);
            let __location = decode_zone(read_u8(cursor));
            let mut c = default_condition_positionCond();
            c
        }
        78 => {
            let _ = read_u8(cursor);
            let __from_state = decode_state(read_u8(cursor));
            let mut c = default_condition_state();
            c
        }
        71 => {
            let _ = read_u8(cursor);
            let __state_val = decode_state(read_u8(cursor));
            let __operator = decode_operator(read_u8(cursor));
            let __value = read_u8(cursor) != 0;
            let mut c = default_condition_state();
            c
        }
        69 => {
            let _ = read_u8(cursor);
            let __count = read_u8(cursor);
            let __operator = decode_operator(read_u8(cursor));
            let mut c = default_condition_temporal();
            c
        }
        0x4A | 0x4B => {
            let _ = read_u8(cursor);
            let op_str = if op_val == 0x4A { "or" } else { "and" };
            let mut conditions = Vec::new();
            loop {
                if cursor.is_empty() || cursor[0] == 0x4C {
                    if !cursor.is_empty() { let _ = read_u8(cursor); }
                    break;
                }
                conditions.push(Box::new(decode_condition(cursor)));
            }
            if conditions.is_empty() {
                default_condition_alwaysTrue()
            } else if conditions.len() == 1 {
                *conditions.into_iter().next().unwrap()
            } else {
                let mut c = default_condition_compound();
                if let Condition::Compound { operator: ref mut _bc_o, conditions: ref mut _bc_cond, .. } = &mut c {
                    *_bc_o = Some(op_str.into());
                    *_bc_cond = Some(conditions);
                }
                c
            }
        }
        _ => default_condition_alwaysTrue(),
    }
}
