#!/usr/bin/env python3
"""Bake a deck-card subset blob for the PS1 port.

The full card blob is 532KB because its string table carries the complete
Japanese ability text + img URLs for all 2280 cards. The PS1 only ever plays
the 196 unique cards across the baked decks, and its `compact_cards` build
never decodes display-only fields (ability/img/product/rare/faq). So we bake
only those cards *and* skip the display-only strings -> ~11KB embedded in the
EXE rodata instead of a 532KB buffer in RAM.

Emits platforms/ps1/src/decks_card_blob.rs:
    pub static DECKS_CARD_BLOB: &[u8] = &[ ... ];
using the exact same CARD binary format as cards/compile_cards.py, so the
engine's card_binary decoder works unchanged (EXTERN_CARD_BLOB is pointed at
this static at boot).
"""

import json
import re
import struct
import sys
from pathlib import Path


def find_repo_root() -> Path:
    """Locate the repo root robustly (Windows batch and MSYS mangle __file__
    differently; also tolerate being run from the repo root with a bare name)."""
    candidates = [Path.cwd()]
    try:
        candidates.append(Path(__file__).resolve().parent.parent)
    except NameError:  # not set in some embedded invocations
        pass
    for start in candidates:
        for p in [start, *start.parents]:
            if (p / "cards" / "compile_cards.py").exists():
                return p
    return candidates[0]


REPO = find_repo_root()
sys.path.insert(0, str(REPO / "cards"))
import compile_cards  # reuse encode_card / parse_hearts / HEART_COLORS

# Default energy card the deck builder may add as filler.
DEFAULT_ENERGY = "LL-E-001-SD"

CARDNO_RE = re.compile(r"^[A-Z0-9!+\-]+$")


def normalize(raw: str) -> str:
    out = []
    for ch in raw:
        if "a" <= ch <= "z":
            out.append(chr(ord(ch) - 32))
        elif "\uff41" <= ch <= "\uff5a":
            out.append(chr(ord(ch) - 0xFEE0))
        elif ch == "\uff0b":
            out.append("+")
        elif ch == "\uff01":
            out.append("!")
        elif ch == "\uff0d":
            out.append("-")
        else:
            out.append(ch)
    return "".join(out)


def deck_card_numbers(decks_rs: Path) -> set[str]:
    """Collect the (normalized) card numbers referenced by decks_baked.rs."""
    text = decks_rs.read_text(encoding="utf-8")
    found = set()
    for s in re.findall(r'"([^"]+)"', text):
        if CARDNO_RE.match(s) and re.match(r"^(PL|LL|SP|MU|RA|L|H)", s.upper()):
            found.add(normalize(s))
    return found


def build_subset_blob(cards_dict: dict, wanted: set[str]) -> bytes:
    """Compile only `wanted` cards, interning only fields the compact runtime
    actually decodes (card_no/name/series/unit). Returns the CARD blob."""
    # Map normalized card_no -> raw key (first wins, deterministic).
    by_norm: dict[str, str] = {}
    for key in sorted(cards_dict.keys()):
        by_norm.setdefault(normalize(key), key)

    wanted.add(DEFAULT_ENERGY)
    chosen = []
    for cn in sorted(wanted):
        raw = by_norm.get(cn)
        if raw is None:
            print(f"  [WARN] card not in cards.json: {cn}", file=sys.stderr)
            continue
        chosen.append((cn, cards_dict[raw]))

    strings = [""]  # index 0 = empty string
    idx_map = {"": 0}

    def intern(s: str) -> int:
        if s not in idx_map:
            idx_map[s] = len(strings)
            strings.append(s)
        return idx_map[s]

    for _, card in chosen:
        intern(card.get("card_no", ""))
        intern(card.get("name", ""))
        intern(card.get("series", ""))
        intern(card.get("unit", ""))
        # Deliberately NOT interned: img, product, rare, ability, faq, group.
        # compact_cards strips these from the decoded Card on console targets.

    strtab = compile_cards.encode_strtab(strings)

    lengths = []
    card_data = bytearray()
    for _, card in chosen:
        before = len(card_data)
        card_data.extend(compile_cards.encode_card(card, idx_map))
        lengths.append(len(card_data) - before)

    header = struct.pack("<4sHI", b"CARD", len(chosen), len(strtab))
    length_table = struct.pack(f"<{len(lengths)}B", *lengths)
    blob = header + strtab + length_table + bytes(card_data)
    return blob


def main() -> None:
    repo = REPO
    cards_json = repo / "cards" / "cards.json"
    decks_rs = repo / "platforms" / "ps1" / "src" / "decks_baked.rs"
    out_rs = repo / "platforms" / "ps1" / "src" / "decks_card_blob.rs"

    cards_dict = json.loads(cards_json.read_text(encoding="utf-8"))
    wanted = deck_card_numbers(decks_rs)
    print(f"deck unique cards: {len(wanted)}")

    blob = build_subset_blob(cards_dict, wanted)
    print(f"subset blob: {len(blob)} bytes")
    print(f"  (full blob would be 532,378 bytes)")

    hex_lines = []
    for i in range(0, len(blob), 24):
        chunk = blob[i : i + 24]
        hex_lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")

    src = f"""// Auto-generated by tools/bake_ps1_decks.py -- do not edit.
//
// Deck-card subset of the CARD blob: only the {len(wanted)} unique cards the
// baked decks reference, with display-only strings (ability/img/product/rare)
// omitted because compact_cards never decodes them on console. This is ~11KB
// instead of the full 532KB blob, so it can be baked into the EXE instead of
// holding the whole card database in RAM.

pub static DECKS_CARD_BLOB: &[u8] = &[
{chr(10).join(hex_lines)}
];
"""
    out_rs.write_text(src, encoding="utf-8")
    print(f"wrote {out_rs}")
    out_rs.with_suffix(".bin").write_bytes(blob)
    print(f"wrote {out_rs.with_suffix('.bin')} ({len(blob)} bytes)")


if __name__ == "__main__":
    main()
