#!/usr/bin/env python3
"""Bake per-deck card data into the main engine.

Each port's deck list is just card numbers (web_ui/decks/*.txt). Instead of each
port baking its own copy (PSP's deck_*.json, PS1's blob/CD machinery), bake one
compact CARD-format blob per deck into the ENGINE, and let
engine::game::deck_parser::load_two_decks decode only the two selected decks.

Emits engine/src/decks_cards_gen.rs:
    pub static DECK_CARD_BLOBS: &[&[u8]] = &[ deck0, deck1, ... ];
Each element is a CARD-format blob (header + strtab + length table + records)
containing only that deck's unique cards, with display-only strings stripped.
Deck index 0 = first web_ui/decks/*.txt when sorted by name.
"""

import json
import re
import struct
import sys
from pathlib import Path


def find_repo_root() -> Path:
    candidates = [Path.cwd()]
    try:
        candidates.append(Path(__file__).resolve().parent.parent)
    except (NameError, OSError):
        pass
    for start in candidates:
        for p in [start, *start.parents]:
            if (p / "cards" / "compile_cards.py").exists():
                return p
    return candidates[0]


REPO = find_repo_root()
sys.path.insert(0, str(REPO / "cards"))
import compile_cards  # noqa: E402


def normalize(raw: str) -> str:
    out = []
    for ch in raw:
        if "a" <= ch <= "z":
            out.append(chr(ord(ch) - 32))
        elif "\uff41" <= ch <= "\uff5a":
            out.append(chr(ord(ch) - 0xFEE0))
        elif "\uff10" <= ch <= "\uff19":
            out.append(chr(ord(ch) - 0xFEE0))
        elif ch == "\uff0b":
            out.append("+")
        elif ch == "\uff01":
            out.append("!")
        elif ch == "\uff0d":
            out.append("-")
        else:
            out.append(ch)
    return "".join(out)


def make_deck_blob(cards_dict, card_nos: list[str]) -> bytes:
    """CARD-format blob with exactly the (deduped, normalized) deck's cards."""
    cards_by_no = {}
    for k, v in cards_dict.items():
        cards_by_no.setdefault(normalize(k), v)

    wanted = []
    seen = set()
    for cn in card_nos:
        n = normalize(cn)
        if n in seen:
            continue
        seen.add(n)
        card = cards_by_no.get(n)
        if card is not None:
            wanted.append((n, card))

    strings = [""]
    idx = {"": 0}

    def intern(s: str) -> int:
        if s not in idx:
            idx[s] = len(strings)
            strings.append(s)
        return idx[s]

    for _, card in wanted:
        for f in ("card_no", "name", "series", "unit"):
            v = card.get(f)
            if isinstance(v, str):
                intern(v)

    strtab = compile_cards.encode_strtab(strings)
    lengths = []
    records = bytearray()
    for _, card in wanted:
        before = len(records)
        records.extend(compile_cards.encode_card(card, idx))
        lengths.append(len(records) - before)

    n = len(wanted)
    header = struct.pack("<4sHI", b"CARD", n, len(strtab))
    return header + strtab + struct.pack(f"<{n}B", *lengths) + bytes(records)


def main() -> None:
    cards_dict = json.loads((REPO / "cards" / "cards.json").read_text(encoding="utf-8"))
    deck_files = sorted((REPO / "web_ui" / "decks").glob("*.txt"))
    print(f"{len(deck_files)} deck files")

    blobs = []
    for f in deck_files:
        card_nos = []
        for line in f.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            # Three formats are valid: bare card_no, "card x count",
            # and "count x card". Expand quantities.
            m = re.match(r"^(\d+)\s*x\s*(.+)$", line)
            if m:
                qty = int(m.group(1))
                card_nos.extend([m.group(2).strip()] * qty)
                continue
            m = re.match(r"^(.*?)\s*x\s*(\d+)$", line)
            if m:
                qty = int(m.group(2))
                card_nos.extend([m.group(1).strip()] * qty)
                continue
            card_nos.append(line)
        blob = make_deck_blob(cards_dict, card_nos)
        blobs.append((f.stem, len(card_nos), blob))
        print(f"  {f.stem:24s} {len(card_nos):4d} cards -> {len(blob):6d} bytes blob")

    # Keep the 16-slot layout the PSP used; pad the rest empty.
    while len(blobs) < 16:
        blobs.append((f"slot{len(blobs)}", 0, b"CARD\x00\x00\x00\x00"))

    total = sum(len(b[2]) for b in blobs)
    print(f"total baked deck data: {total} bytes across {len(blobs)} slots")

    # Write each blob as its own .bin file; decks_cards_gen.rs embeds them via
    # include_bytes! so rustc never parses megabytes of hex tokens on rebuild.
    bins_dir = REPO / "engine" / "baked" / "decks"
    bins_dir.mkdir(parents=True, exist_ok=True)
    for name, count, blob in blobs:
        (bins_dir / f"{name}.bin").write_bytes(blob)

    lines = []
    lines.append("// Auto-generated by tools/bake_deck_cards.py -- do not edit.")
    lines.append("//")
    lines.append("// Per-deck card data in the compact CARD blob format. Each element")
    lines.append(
        "// holds only that deck's unique cards (display-only strings stripped)."
    )
    lines.append(
        "// load_two_decks() decodes just the two selected decks. Deck index 0"
    )
    lines.append("// is the first web_ui/decks/*.txt when sorted by name.")
    lines.append("")
    lines.append("pub static DECK_CARD_BLOBS: &[&[u8]] = &[")
    for name, count, blob in blobs:
        lines.append(f"    // {name}: {count} cards, {len(blob)} bytes")
        lines.append(f'    include_bytes!("../baked/decks/{name}.bin"),')
    lines.append("];")
    lines.append("")

    out = REPO / "engine" / "src" / "decks_cards_gen.rs"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")

    # ---- decks_baked.rs for every platform crate ----
    # Same glob, same sort order as the blobs above, so menu index i always
    # corresponds to blob i. Generating these HERE (not elsewhere) is what
    # prevents the menu list and the baked data from drifting apart — that
    # drift caused "AI player has an empty deck" on every console port.
    real_decks = [(name, count, blob) for name, count, blob in blobs
                  if not name.startswith("slot")]
    template = """// Auto-generated by tools/bake_deck_cards.py -- do not edit.
// Deck index order is ALIGNED with engine/src/decks_cards_gen.rs
// (both come from web_ui/decks/*.txt sorted by filename).

pub struct DeckInfo {{
    pub name: &'static str,
    pub cards: &'static [&'static str],
}}

pub const DECKS: &[DeckInfo] = &[
{entries}
];
"""
    entries = []
    for f in deck_files:
        card_nos = []
        for line in f.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            m = re.match(r"^(\d+)\s*x\s*(.+)$", line)
            if m:
                qty = int(m.group(1))
                card_nos.extend([m.group(2).strip()] * qty)
                continue
            m = re.match(r"^(.*?)\s*x\s*(\d+)$", line)
            if m:
                qty = int(m.group(2))
                card_nos.extend([m.group(1).strip()] * qty)
                continue
            card_nos.append(line)
        cards_js = ",\n            ".join(f'"{c}"' for c in card_nos)
        entries.append(
            "    DeckInfo {\n"
            f'        name: "{f.stem}",\n'
            "        cards: &[\n            "
            + cards_js
            + ",\n        ],\n    },"
        )
    baked_rs = template.format(entries="\n".join(entries))
    for crate in ("ds", "gba", "jaguar", "ps1", "wasm"):
        p = REPO / "platforms" / crate / "src" / "decks_baked.rs"
        if p.parent.exists():
            p.write_text(baked_rs, encoding="utf-8")
            print(f"wrote {p}")


if __name__ == "__main__":
    main()
