#!/usr/bin/env python3
"""Bake GBA card art from the 3DS pipeline's PNG cache.

The 3DS already converts every card's WebP to a resized PNG cache and a
manifest (card_no -> image). We reuse that directly — no re-deriving the
card_no -> image mapping. Each card's PNG basename IS its cards.json card_no.

For each card referenced by any deck (same resolution as bake_deck_cards.py),
resize the cached PNG to a fixed portrait grid, quantize to 240 colours
(reserving palette bank 15 / indices 240-255 for the 4bpp text palette), and
emit platforms/gba/src/card_art_gen.rs with:

    pub struct CardArt { pub card_no: &'static str, pub palette: &'static [u8; 480], pub tiles: &'static [u8; 192*64] }
    pub static CARD_ART: &[CardArt] = &[ ... ];

Run:  py -3 tools/bake_card_art.py
"""

import json
import os
import sys
from pathlib import Path

from PIL import Image

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "cards"))
sys.path.insert(0, str(REPO / "tools"))
from bake_deck_cards import normalize, REPO as _REPO  # noqa: E402

ART_W = 96  # 12 tiles
ART_H = 128  # 16 tiles
N_COLORS = 240  # leave indices 240-255 (bank 15) for the 4bpp text palette
TILE = 8

CACHE = REPO / "platforms" / "3ds" / ".card_png_cache"
OUT = REPO / "platforms" / "gba" / "src" / "card_art_gen.rs"


def deck_card_nos() -> set:
    """Union of normalized cards.json card_nos used by all decks."""
    cards_dict = json.loads((REPO / "cards" / "cards.json").read_text(encoding="utf-8"))
    by_no = {}
    for k, v in cards_dict.items():
        by_no.setdefault(normalize(k), k)  # normalized -> original cards.json key
    used = set()
    for f in sorted((REPO / "web_ui" / "decks").glob("*.txt")):
        for line in f.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            card_no = None
            parts = line.split()
            if parts:
                if parts[0].isdigit() and len(parts) >= 2:
                    card_no = " ".join(parts[1:]).split("x")[0].strip()
                elif parts[-1].isdigit() and len(parts) >= 2:
                    card_no = " ".join(parts[:-2]) if len(parts) >= 2 else parts[0]
                else:
                    card_no = line
            if card_no:
                n = normalize(card_no)
                if n in by_no:
                    used.add(by_no[n])
    return used


def to_rgb15(r, g, b):
    return ((r >> 3) & 31) | (((g >> 3) & 31) << 5) | (((b >> 3) & 31) << 10)


def main():
    used = deck_card_nos()
    print(f"{len(used)} unique deck cards to bake")

    entries = []
    missing = []
    for card_no in sorted(used):
        png = CACHE / f"{card_no}.png"
        if not png.exists():
            missing.append(card_no)
            continue
        img = Image.open(png).convert("RGB")
        img = img.resize((ART_W, ART_H), Image.LANCZOS)
        q = img.quantize(colors=N_COLORS, method=Image.Quantize.MEDIANCUT)  # P mode
        # palette as rgb15 little-endian
        pal = q.getpalette()[: N_COLORS * 3]
        pal_bytes = bytearray()
        for i in range(N_COLORS):
            r, g, b = pal[i * 3], pal[i * 3 + 1], pal[i * 3 + 2]
            c = to_rgb15(r, g, b)
            pal_bytes += bytes([c & 0xFF, c >> 8])
        # 8bpp tile indices (P-mode pixel values are palette indices)
        px = q.load()
        tiles = bytearray()
        for ty in range(ART_H // TILE):
            for tx in range(ART_W // TILE):
                tile = bytearray(64)
                for rr in range(TILE):
                    for cc in range(TILE):
                        tile[rr * TILE + cc] = px[tx * TILE + cc, ty * TILE + rr] & 0xFF
                tiles += tile
        entries.append((card_no, bytes(pal_bytes), bytes(tiles)))

    print(f"baked {len(entries)} cards, missing {len(missing)}")
    if missing:
        print("missing:", missing[:20])

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by tools/bake_card_art.py -- do not edit.\n")
        f.write("// Card art as 8bpp tiles (96x128 = 12x16 tiles) + 240-colour\n")
        f.write("// rgb15 palette (bank 15 reserved for text).\n\n")
        f.write("pub struct CardArt {\n")
        f.write("    pub card_no: &'static str,\n")
        f.write("    pub palette: &'static [u8; 480],\n")
        f.write("    pub tiles: &'static [u8; 12288],\n")
        f.write("}\n\n")
        f.write(f"pub static CARD_ART: &[CardArt] = &[\n")
        for card_no, pal, tiles in entries:
            f.write(f"    CardArt {{\n        card_no: {json.dumps(card_no, ensure_ascii=False)},\n")
            f.write("        palette: &[\n")
            for i in range(0, len(pal), 24):
                f.write("            " + ", ".join(str(b) for b in pal[i:i + 24]) + ",\n")
            f.write("        ],\n        tiles: &[\n")
            for i in range(0, len(tiles), 32):
                f.write("            " + ", ".join(str(b) for b in tiles[i:i + 32]) + ",\n")
            f.write("        ],\n    },\n")
        f.write("];\n")
    print(f"wrote {OUT} ({os.path.getsize(OUT)} bytes)")


if __name__ == "__main__":
    main()
