// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod erena_self_wait_constant_heart05_test;
pub mod nico_cannot_activate_test;
pub mod two_or_more_opponent_wait_members_constant_heart06_test;
pub mod wait_state_condition_constants_test;
