// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod area_move_energy_placement_resolution_order_test;
pub mod position_change_only_places_energy_test;
