#!/usr/bin/env python3
"""Generate a Unicode -> Shift-JIS (CP932) conversion table as C source.

Used by the Dreamcast shell to display the engine's UTF-8 Japanese text
with the console BIOS font (bfont_set_encoding(BFONT_CODE_SJIS)).
Output: sjis_table.h / sjis_table.c with a sorted (unicode, sjis) array
for binary search. Single-byte ASCII passes through unchanged.
"""
import sys

def main():
    pairs = {}  # unicode codepoint -> sjis bytes (2-byte range only)
    # Standard SJIS double-byte lead ranges: 0x81-0x9F, 0xE0-0xEF (skip 0xEF-fc vendor rows past EA)
    leads = list(range(0x81, 0xA0)) + list(range(0xE0, 0xEB))
    for b1 in leads:
        for b2 in range(0x40, 0xFD):
            if 0x7F <= b2 <= 0x80:
                continue
            try:
                ch = bytes([b1, b2]).decode("cp932")
            except UnicodeDecodeError:
                continue
            cp = ord(ch)
            if cp < 0x80:
                continue
            # keep first (canonical) mapping
            if cp not in pairs:
                pairs[cp] = (b1, b2)

    items = sorted(pairs.items())
    out_h = f"""/* Auto-generated by gen_sjis_table.py - Unicode -> Shift-JIS table */
#ifndef SJIS_TABLE_H
#define SJIS_TABLE_H

#include <stdint.h>

#define SJIS_TABLE_ENTRIES {len(items)}

/* Returns the 2-byte Shift-JIS encoding of `cp` (big-endian in the low 16
 * bits: (lead<<8)|trail), or 0 if unmappable. */
uint16_t sjis_from_unicode(uint32_t cp);

#endif
"""
    lines = [
        "/* Auto-generated by gen_sjis_table.py - Unicode -> Shift-JIS (CP932) */",
        '#include "sjis_table.h"',
        "",
        "static const struct { uint16_t uni; uint16_t sjis; } sjis_map[SJIS_TABLE_ENTRIES] = {",
    ]
    for cp, (b1, b2) in items:
        lines.append(f"    {{ 0x{cp:04X}, 0x{b1:02X}{b2:02X} }},")
    lines += [
        "};",
        "",
        "uint16_t sjis_from_unicode(uint32_t cp) {",
        "    int lo = 0, hi = SJIS_TABLE_ENTRIES - 1;",
        "    while (lo <= hi) {",
        "        int mid = (lo + hi) / 2;",
        "        if (sjis_map[mid].uni == cp) return sjis_map[mid].sjis;",
        "        if (sjis_map[mid].uni < cp) lo = mid + 1; else hi = mid - 1;",
        "    }",
        "    return 0;",
        "}",
    ]
    open("sjis_table.h", "w").write(out_h)
    open("sjis_table.c", "w").write("\n".join(lines) + "\n")
    print(f"entries: {len(items)}")

if __name__ == "__main__":
    main()
