// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod self_move_grants_heart06_until_live_end_test;
pub mod self_move_watch_cause_and_effect_only_flag_test;
pub mod self_move_watch_natural_move_and_turn_limit_edges_test;
pub mod self_or_opponent_move_grants_blade_test;
