// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod auto_system_stress_test;
pub mod chisato_pb1_003_both_stages_rotation_test;
pub mod debut_selected_member_fixed_center_test;
pub mod energy_return_cost_position_change_test;
pub mod formation_change_test;
pub mod group_only_debut_formation_move_subunit_gain_blades_test;
pub mod himeno_front_test;
pub mod live_start_subunit_threshold_formation_test;
pub mod love_wing_bell_test;
pub mod mill_three_self_position_change_q104_q234_test;
pub mod position_change_condition_test;
pub mod position_change_multi_test;
pub mod position_change_non_optional_test;
pub mod position_change_triggers_jidou_move_test;
pub mod self_control_position_change_test;
pub mod wien_bp5_test;
