#![recursion_limit = "512"]

pub mod card;
pub mod constants;
pub mod zones;
pub mod player;
pub mod game_state;
pub mod config;
pub mod mod_map;
pub mod types;
pub mod turn;
pub mod card_loader;
pub mod deck_builder;
pub mod deck_parser;
pub mod web_server;
pub mod bot;
pub mod game_setup;
pub mod ability;
pub mod ability_resolver;
pub mod ability_queue;
pub mod triggers;
pub mod display;
