// Auto-generated by build.rs — DO NOT EDIT.
// Regenerated from the directory listing at compile time.
pub mod hs_pb1_001_jidou_activated_energy_funds_live_start_payment_test;
pub mod hs_pb1_003_turn2_second_discard_event_grants_again_test;
pub mod hs_pb1_009_jidou_blades_charge_live_start_threshold_test;
pub mod rurino_stage_to_waitroom_watcher_baseline_test;
pub mod sp_bp5_005_mill_arms_jidou_recover_test;
pub mod yell_real_yell_no_blade_heart_grants_heart_test;
